### ISSUE TITLE
Assets for README

### ISSUE THREAD

**Issue by imfing** [whutug/whu-thesis#1]
This issue contains necessary assets

**Comment by mtobeiyf** [comment]
Sample pages
![example](https://user-images.githubusercontent.com/5097752/55679059-f250d300-5936-11e9-8dfe-937a64a0c6bf.png)

**Comment by mtobeiyf** [comment]
For wiki
![Snipaste_2019-04-10_20-59-45](https://user-images.githubusercontent.com/5097752/55880894-37ddfc00-5bd4-11e9-9760-9db15371d322.png)

**Comment by mtobeiyf** [comment]
For wiki
![VSCode](https://user-images.githubusercontent.com/5097752/55883625-3fec6a80-5bd9-11e9-80d3-d722b76bf9d6.png)
![image](https://user-images.githubusercontent.com/5097752/55884009-e46eac80-5bd9-11e9-8d5f-ad9086283341.png)

**Comment by mtobeiyf** [comment]
For wiki
![image](https://user-images.githubusercontent.com/5097752/56079052-87653780-5e21-11e9-929a-1119c9edfd28.png)

**Comment by mtobeiyf** [comment]
[附件：武汉大学本科生毕业论文（设计）工作管理办法及书写印制规范.pdf](https://github.com/mtobeiyf/whu-thesis/files/4638713/default.pdf)
