### ISSUE TITLE
数学字体更换

### ISSUE THREAD

**Issue by wzm2256** [whutug/whu-thesis#120]
请问我如何换回Latex默认的数学字体？
目前的字体问题有两个
1. mathca 和mathsrc显示无区别。
2. 和Latex默认字体不一样

根据这个回答 https://tex.stackexchange.com/questions/120065/xetex-what-happened-to-mathcal-and-mathscr ，
完整的解决这两个问题可能只需要去掉math-unicode，但是目前还做不到 https://github.com/whutug/whu-thesis/issues/94 

以下是我的解决方案：
第一个问题我摸索了一个多小时(不懂cls代码，纯靠摸索)。
把
```
\RequirePackage { unicode-math }
```
换成
```
\RequirePackage { unicode-math }
\setmathfont{LatinModernMath-Regular}
\setmathfont[range={\mathscr,\mathbfscr}]{XITSMath-Regular}
```
然后把下面所有行的带有math-font的行数全部注释掉。

第二个问题，应该换成什么数学字体才是Latex默认字体？（和之前发表的论文符号看上去一致）
这个目前还没找到答案。

**Comment by zepinglee** [comment]
1. 有的字体（比如 stix2, xits, newcm）都提供了 StylisticSet 选择 `\mathcal` 和 `\mathscr` 的样式。可以参考 <https://github.com/tuna/thuthesis/blob/ee4ca6a2a7e4af44414a63147ec149c79a7946e1/thuthesis.dtx#L2867-L2878>。
2. LaTeX 的默认字体 Computer Modern（简称 cm）是 Type 1 字体，跟调用 OpenType 字体的 `unicode-math` 属于两套系统。建议使用 [New Computer Modern](https://ctan.org/pkg/newcomputermodern)，该字体跟 cm 的字形基本一致，但属于 OpenType 字体，所以可以被 `unicode-math` 调用。不过需要考虑的一点是，数学字体跟正文的西文字体要搭配。如果正文西文要求使用 Times，数学字体再用 cm 就会很很可怕。

**Comment by wzm2256** [comment]
> 1. 有的字体（比如 stix2, xits, newcm）都提供了 StylisticSet 选择 `\mathcal` 和 `\mathscr` 的样式。可以参考 https://github.com/tuna/thuthesis/blob/ee4ca6a2a7e4af44414a63147ec149c79a7946e1/thuthesis.dtx#L2867-L2878。
> 2. LaTeX 的默认字体 Computer Modern（简称 cm）是 Type 1 字体，跟调用 OpenType 字体的 `unicode-math` 属于两套系统。建议使用 [New Computer Modern](https://ctan.org/pkg/newcomputermodern)，该字体跟 cm 的字形基本一致，但属于 OpenType 字体，所以可以被 `unicode-math` 调用。不过需要考虑的一点是，数学字体跟正文的西文字体要搭配。如果正文西文要求使用 Times，数学字体再用 cm 就会很很可怕。

多谢提供信息。。然而我并不知道如何解决问题（看不懂cls文件。。），我打算先搁置了。。
