### ISSUE TITLE
关于 `\mathcal{}` 公式的问题

### ISSUE THREAD

**Issue by HenryZhuHR** [whutug/whu-thesis#125]
## 检查

* [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

* 操作系统
  + [ ] Windows 10
  + [ ] Windows 8/8.1
  + [ ] Windows 7
  + [ ] 更早版本的 Windows
  + [x] macOS
  + [ ] Linux（请附发行版）

* TeX 发行版
  + [x] TeX Live 2021
  + [ ] MiKTeX 
  + [ ] CTeX 套装 2.9.2.164
  + [ ] 更早版本的 CTeX 套装

* whu-thesis 版本
v0.6d
  

## 描述问题

关于 `\mathcal{}` 公式渲染的问题:
``` latex
\begin{equation}
  \mathcal{L}
\end{equation}
```
可是渲染出来的是类似`\mathscr{L}`的花体，如下图：
![mathsrc](https://s3.bmp.ovh/imgs/2022/04/17/2be305d6af7ba75d.png)

该情况在 overleaf 和本地编译都如此，如果希望使用下图的 `\mathcal{L}` 应该怎么解决
![mathcal](https://s3.bmp.ovh/imgs/2022/04/17/e6ea028e4a5377d0.png)

**Comment by xkwxdyy** [comment]
`\mathsrc` 打错了，应该是 `\mathscr`

**Comment by xkwxdyy** [comment]
在 0.6e 发行版中已修复，请测试一下看有没有问题

**Comment by HenryZhuHR** [comment]
> 在 0.6e 发行版中已修复，请测试一下看有没有问题

正常了，`\mathscr` 和 `\mathcal` 都正确了

**Comment by HenryZhuHR** [comment]
> 在 0.6e 发行版中已修复，请测试一下看有没有问题

正常了，`\mathscr` 和 `\mathcal` 都正确了

**Comment by iNoak** [comment]
你好，我正在使用老版本的模板，能否指导一下怎么替换成上述的花体？谢谢。

**Comment by sikouhjw** [comment]
> 你好，我正在使用老版本的模板，能否指导一下怎么替换成上述的花体？谢谢。

参考
https://github.com/whutug/whu-thesis/blob/6f19c2e0d34bbfc752f86a7ea505154a185ff595/whu-thesis.cls#L637-L642
在导言区使用
```tex
\ExplSyntaxOn
\cs_set_protected:Npn \__whu_set_math_font_xits: 
  {
    \setmathfont { XITSMath-Regular.otf } 
      [ BoldFont = XITSMath-Bold.otf ] 
    \setmathfont{ XITSMath-Regular.otf }[range={cal,bfcal},StylisticSet=01] 
  }
\ExplSyntaxOff
```

**Comment by SwitWu** [comment]
`whu-thesis.cls` 里面都设置好了，你再设置一遍干什么
