### ISSUE TITLE
麻烦问一下前面这个顿号怎么去掉呢

### ISSUE THREAD

**Issue by zijuzhang** [whutug/whu-thesis#128]
![image](https://user-images.githubusercontent.com/14990346/164412888-29771747-e345-4bca-b2a7-827466e7cf95.png)

**Comment by tanukihee** [comment]
这不是要填两个吗，你只填了一个

**Comment by zijuzhang** [comment]
> 这不是要填两个吗，你只填了一个

多谢~我看到了 还有个whu-thesis.cls文件 我在这里面改好了已经 因为我们不需要填这个学科
