### ISSUE TITLE
如何在模板中的文献前加上编号呀

### ISSUE THREAD

**Issue by zijuzhang** [whutug/whu-thesis#129]
![image](https://user-images.githubusercontent.com/14990346/164460760-63701413-9b52-4029-8ef0-dcda1f408467.png)
能否在这个前面加上标号 [1] 在哪里调代码呢 麻烦了

**Comment by tanukihee** [comment]
依规范，硕博使用作者—年式的参考文献格式，是不需要标号的，如果需要改成顺序编号制，请自行查询文档「参考文献」相关内容

你图没传上来

**Comment by zijuzhang** [comment]
> 

好的 那就不管了~就按咱们这个模板来~ 嘿嘿 多谢

**Comment by zijuzhang** [comment]
> 依规范，硕博使用作者—年式的参考文献格式，是不需要标号的，如果需要改成顺序编号制，请自行查询文档「参考文献」相关内容
> 
> 你图没传上来

好的 那就不管了就按咱们这个模板来 嘿嘿 多谢
