### ISSUE TITLE
纸张尺寸问题

### ISSUE THREAD

**Issue by ConicalBanana** [whutug/whu-thesis#130]
目前的模板渲染出来不是a4大小，推测可能是whu-thesis.cls的206行缺少了参数：

`\RequirePackage { geometry }`

添加a4paper参数后打印出来尺寸就正常了

`\RequirePackage[a4paper]{ geometry }`

**Comment by tanukihee** [comment]
geometry 确实会更改纸张大小，但我忘了在引入 ctexbook 文档类的时候指定 a4paper 吗

请@xkwxdyy 佬看看

**Comment by xkwxdyy** [comment]
我测试了一下，`ctex` 的 `a4paper` 效果和 `geometry` 设置的是不同的，后者的版心貌似大一些

**Comment by ConicalBanana** [comment]
我用的 

> geometry 确实会更改纸张大小，但我在引入 ctexbook 文档类的时候指定 a4paper 了呀，难道 geometry 更新后还会覆盖这个值吗（至少旧版本不会
> 
> 请@xkwxdyy 佬看看

我用的去年四月装的texlive2021，宏包版本是geometry 5.9/ctex 2.5.8，刚渲染了以后发现页边距又不对了，在geometry的参数里修改也没有用，最后强行用`\newgeometry { a4paper, left = 3 cm ,  bottom = 2 cm , top = 2.5 cm , right = 3 cm }`调整了。

**Comment by tanukihee** [comment]
旧版本效果

https://github.com/CTeX-org/forum/issues/160

**Comment by xkwxdyy** [comment]
> 旧版本效果
> 
> [CTeX-org/forum#160](https://github.com/CTeX-org/forum/issues/160)

原来 Lee 佬很早就发现了类似的问题
