### ISSUE TITLE
如何增加超链接的红框（hyperref）

### ISSUE THREAD

**Issue by fyqqyf** [whutug/whu-thesis#132]
## 检查

* [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

* 操作系统
  + [ ] Windows 10
  + [ ] Windows 8/8.1
  + [ ] Windows 7
  + [ ] 更早版本的 Windows
  + [x] macOS
  + [ ] Linux（请附发行版）

* TeX 发行版
  + [x] TeX Live 
  + [ ] MiKTeX 
  + [ ] CTeX 套装 2.9.2.164
  + [ ] 更早版本的 CTeX 套装

* whu-thesis 版本

## 描述问题

导师觉得超链接没有红框不明显……想问一下怎么增加呢？直接删除`\hypersetup { hidelinks }`会报错。😢

报错为：
```
Undefined control sequence.
<recently read> \Hy@colorlink 
```

**Comment by tanukihee** [comment]
删掉辅助文件再编译呢？

**Comment by fyqqyf** [comment]
> 删掉辅助文件再编译呢？

删除了的以后编译的，您可以复现一下。（即只注释hidelinks)

**Comment by fyqqyf** [comment]
悲🥲🥲🥲
