### ISSUE TITLE
请问如何修改模板文件，使中英文摘要和目录页显示罗马数字页码

### ISSUE THREAD

**Issue by ZrW00** [whutug/whu-thesis#148]
## 检查

* [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

* 操作系统
  + [x] Windows 10
  + [ ] Windows 8/8.1
  + [ ] Windows 7
  + [ ] 更早版本的 Windows
  + [ ] macOS
  + [ ] Linux（请附发行版）

* TeX 发行版
  + [x] TeX Live <2021>
  + [ ] MiKTeX 
  + [ ] CTeX 套装 2.9.2.164
  + [ ] 更早版本的 CTeX 套装

* whu-thesis 版本

  <v0.6d>

## 描述问题
请问如何修改模板文件，使中英文摘要和目录页显示罗马数字页码（本科毕设论文）

**Comment by xkwxdyy** [comment]
https://github.com/whutug/whu-thesis/discussions/147
