### ISSUE TITLE
武大校徽更新

### ISSUE THREAD

**Issue by tanukihee** [whutug/whu-thesis#150]
武大校徽已经更新，模板里带的校徽图案应改为新版（谁来做个矢量图

http://mp.weixin.qq.com/s?__biz=MzA5MjM3MzUxMA==&mid=2655865346&idx=1&sn=6848a7d10534619cf20c42dcb4ce8c70&chksm=8bd7fd6bbca0747df356b687384460e16dd0fc7856a7cba78fbd0a822d6613f51e06a7a8f1bc&mpshare=1&scene=23&srcid=0601FKacAQ7NI7TuYzkUlTH1&sharer_sharetime=1654047632998&sharer_shareid=275559adb34c64b62cc9bd0d94175e7c#rd

**Comment by xkwxdyy** [comment]
我也看到了，这玩意怎么可能自己做（
不知道官方会不会放出啥原图
甚至那个推送里的校徽，单色的都比双色清晰（

**Comment by tanukihee** [comment]
> https://www.whu.edu.cn/xxgk/wdbs.htm
> 
> 武大官网已有新校徽标识相关的原始文件

竟然有 ai 文件，看来武带设计水平还是有点长进（

**Comment by SwitWu** [comment]
已更新 9d997967db8576af951ee849c72bccf31b0db2a3 ec1b0fc7fa53d219b91bcf6d569338faab70f77e
