### ISSUE TITLE
two-side 模式，确保章标题在奇数页的问题

### ISSUE THREAD

**Issue by lkyhfx** [whutug/whu-thesis#152]
想问一下，确保章标题在奇数页是哪里的要求？《武汉大学硕士学位论文印制规定》里并没有这项规定啊。因为图书馆要求不能有空白页，说要重新排页码，根本不知道有确保章标题在奇数页这回事。但是在研究生院的系统里已经提交模版生成的 two-side 的pdf。导致研究生院系统里的版本页码图书馆版本页码不同，也不知道以后会不会有影响。

**Comment by tanukihee** [comment]
不是哪里的要求，是长久以来的排版习惯
