### ISSUE TITLE
英文关键词的样式同本科毕业论文检查表中的样式不一致

### ISSUE THREAD

**Issue by firezl** [whutug/whu-thesis#158]
## 检查

* [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

* 操作系统
  + [x] Windows 10

* TeX 发行版
  + [x] MiKTeX 

* whu-thesis 版本
v0.6e - 2022-04-17
  

## 描述问题
英文关键词的样式同本科毕业论文检查表中的样式不一致。
![CD10UGGE)J$TDZCXL6$YZMU](https://user-images.githubusercontent.com/45823550/174127559-4a7e7007-5ebe-4742-a77a-8258a2e185d5.jpg)

目前模板编译出的英文关键词样式为:
![image](https://user-images.githubusercontent.com/45823550/174128289-72e93fcf-5727-48f2-a3e2-4a296569c705.png)

本科毕业论文检查表中要求的keywords应该没有空格

## 最小工作示例（MWE）

``` latex
\documentclass{whu-thesis}
\whusetup
{
    keywords*      = {Dummy1, Dummy2},
}
\begin{document}
Hello, \LaTex!
\end{document}
```

## 我还做了这些尝试
修改whu-thesis.cls中的第1410行：
![image](https://user-images.githubusercontent.com/45823550/174128766-f43c0a24-d280-4619-9775-a922ba913eb8.png)
修改为:
![image](https://user-images.githubusercontent.com/45823550/174128804-de1f82f5-431b-4565-aed9-53192d04aa59.png)

目前看起来是可以解决问题。

**Comment by xkwxdyy** [comment]
中间加空格这个应该是沿用了黄正华老师的模版设置。之后会修复
