### ISSUE TITLE
因为每一页的抬头下面没有横线被要求重新打印

### ISSUE THREAD

**Issue by MoeLeaf** [whutug/whu-thesis#159]
默认编译成
![image](https://user-images.githubusercontent.com/12065870/174213195-b356f99d-bd46-4f7f-8e39-20330affe3bb.png)

手动添加命令
`\renewcommand{\headrulewidth}{0.75pt}`
后变成

![image](https://user-images.githubusercontent.com/12065870/174213227-75aac147-9941-46dc-8048-1b0479d76fa3.png)

**Comment by xkwxdyy** [comment]
所以要求是需要横线是吧？因为这个在 https://gs.whu.edu.cn/info/1026/1096.htm 中并没有强制要求。之后会设计键值进行控制。

**Comment by theUanAsia** [comment]
有办法在cls文件中直接添加代码实现这一功能吗？

**Comment by sikouhjw** [comment]
> 有办法在cls文件中直接添加代码实现这一功能吗？

你没看到这条命令？
```tex
\renewcommand{\headrulewidth}{0.75pt}
```

**Comment by theUanAsia** [comment]
> 

十分感谢，好像在chapter1中加入的话，后面的也会有

**Comment by sikouhjw** [comment]
> 十分感谢，好像在chapter1中加入的话，后面的也会有

你没有说过这个需求
