### ISSUE TITLE
中文参考文献应该怎么添加bib？

### ISSUE THREAD

**Issue by liang3588** [whutug/whu-thesis#177]
我想添加中文参考文献，例如[1]高山,卢汉清,周万宁.基于细节的自适应网格简化[J].计算机辅助设计与图形学学报,2003(09):1122-1127.这样一篇文章，我该怎么写成bib格式呢？我写成了
@article{gap2003detail,
title={基于细节的自适应网格简化},
  author={高山 and 卢汉清 and 周万宁},
  journal={计算机辅助设计与图形学学报},
  volume={09},
  pages={1122-1127},
  year={2003}
}
<img width="552" alt="截屏2022-10-11 下午10 39 36" src="https://user-images.githubusercontent.com/82434236/195122166-a2a31cb8-6cd5-4a92-ad5b-7a828dd88a13.png">

但是这种格式明显不对，这应该怎么调整啊？

**Comment by sikouhjw** [comment]
你确定用的是这个模板？
