### ISSUE TITLE
参考文献没有序号

### ISSUE THREAD

**Issue by liang3588** [whutug/whu-thesis#179]
我用whu-thesis编译，为什么参考文献没有序号啊？这应该怎么加呢？
<img width="572" alt="截屏2022-10-23 上午11 15 49" src="https://user-images.githubusercontent.com/82434236/197371637-00cef82a-edd4-4fa0-819b-25720ba5dfdc.png">

而且参考文献四个字前面的空白好多，怎么能缩短啊？

**Comment by sikouhjw** [comment]
> 为什么参考文献没有序号啊？

看手册

**Comment by HenryZhuHR** [comment]
这个应该是硕士或者博士的模板，按照要求是没用序号，如果你想有序号，可以自己改成本科的格式

**Comment by xiayulu** [comment]
把论文模板第一行改成本科类型即可

```tex
\documentclass[type=bachelor]{whu-thesis}
```
