### ISSUE TITLE
overleaf上书脊怎么生成呢？

### ISSUE THREAD

**Issue by NingYuanxiang** [whutug/whu-thesis#181]
overleaf上书脊怎么生成呢？

**Comment by xkwxdyy** [comment]
一般你找打印店打印，他们会帮你弄书脊的

**Comment by NingYuanxiang** [comment]
模板中的spine怎么生成呢？

**Comment by sikouhjw** [comment]
https://github.com/whutug/whu-thesis/blob/6f19c2e0d34bbfc752f86a7ea505154a185ff595/whu-thesis-doc.tex#L97-L100
https://github.com/whutug/whu-thesis/blob/6f19c2e0d34bbfc752f86a7ea505154a185ff595/whu-thesis-doc.tex#L118

**Comment by NingYuanxiang** [comment]
\begin{shellexample}[morekeywords={latexmk},emph={-xelatex,-shell-escape}]
    latexmk -xelatex -shell-escape thesis
\end{shellexample}
 这个命令在overleaf怎么用呢？ 如果不能用的，请您说一下怎么用！谢谢！！ @

**Comment by SwitWu** [comment]
> \begin{shellexample}[morekeywords={latexmk},emph={-xelatex,-shell-escape}] latexmk -xelatex -shell-escape thesis \end{shellexample} 这个命令在overleaf怎么用呢？ 如果不能用的，请您说一下怎么用！谢谢！！ @

在本地用命令行弄。
