### ISSUE TITLE
图片索引后的空页怎么去除？

### ISSUE THREAD

**Issue by NingYuanxiang** [whutug/whu-thesis#182]
![image](https://user-images.githubusercontent.com/35770204/210176322-8ef5372e-6cae-4584-a7e1-11dbc75a894e.png)

**Comment by NingYuanxiang** [comment]
还有很多chapter后会出现空页，这怎么去掉呢？

**Comment by sikouhjw** [comment]
https://github.com/whutug/whu-thesis/blob/6f19c2e0d34bbfc752f86a7ea505154a185ff595/whu-thesis.cls#L132-L143
book 的 `\chapter` 从奇数页开始

**Comment by NingYuanxiang** [comment]
谢谢

**Comment by NingYuanxiang** [comment]
每一个chapter，如图片索引，上方的空白太多，如何减少呢？
