### ISSUE TITLE
如何实现目录多级标题的后移？

### ISSUE THREAD

**Issue by theUanAsia** [whutug/whu-thesis#189]
如题所示，请问如何实现目录更有层次的标题，比如说1.1.x 小节的标题的缩进比1.1小节更为靠后？

**Comment by HenryZhuHR** [comment]
首先，模板是按照学校给的格式做的，学校的模板内目录层次并没有要求缩进

如果仍然需要更改，我这里的做法是修改如下片段
https://github.com/whutug/whu-thesis/blob/6f19c2e0d34bbfc752f86a7ea505154a185ff595/whu-thesis.cls#L345-L353

修改为：
```cls
\clist_map_inline:nn { sec  }
  {
    \tl_set:cn { cft #1 font } { \zihao { -4 } }

    \tl_if_eq:NnF \g__whu_option_type_tl { doctor }
      { \tl_set:cn  { cft #1 page font } { \zihao { 5 } } }

    \dim_set:cn { cft #1 indent } { \parindent }
  }

\clist_map_inline:nn { subsec, subsubsec }
  {
    \tl_set:cn { cft #1 font } { \zihao { -4 } }

    \tl_if_eq:NnF \g__whu_option_type_tl { doctor }
      { \tl_set:cn  { cft #1 page font } { \zihao { 5 } } }

    \dim_set:cn { cft #1 indent } { 1.5\parindent }
  }
```

因为模板中将三个级别的标题 `{ sec , subsec , subsubsec }` 都统一对待了，因此没有缩进。所以可以把 `subsec , subsubsec` 单独移出另外设置缩进进行如下修改
```cls
% \dim_set:cn { cft #1 indent } { \parindent }
\dim_set:cn { cft #1 indent } { 1.5\parindent } % 修改
```
这个 1.5 就是缩进的倍数，默认是 1.0 ，修改此数值，就可以实现缩进

<img width="400" alt="截屏2023-03-01 15 31 01" src="https://user-images.githubusercontent.com/38650110/222072916-a6f106f3-a694-4328-8fd9-b3fad11ec9e9.png">
