### ISSUE TITLE
很简单的问题，模板改了，去年年底的博士毕业论文就变格式了

### ISSUE THREAD

**Issue by khf-big** [whutug/whu-thesis#190]
## 检查

* [ ] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

* 操作系统
  + [ ] Windows 10
  + [ ] Windows 8/8.1
  + [ ] Windows 7
  + [ ] 更早版本的 Windows
  + [ ] macOS
  + [ ] Linux（请附发行版）

* TeX 发行版
  + [ ] TeX Live 
  + [ ] MiKTeX 
  + [ ] CTeX 套装 2.9.2.164
  + [ ] 更早版本的 CTeX 套装

* whu-thesis 版本

  

## 最小工作示例（MWE）

``` latex
\documentclass{whu-thesis}
\begin{document}
Hello, \LaTex!
\end{document}
```

（用 XeLaTeX 编译后）输出

``` latex
! Undefined control sequence.
l.3 Hello, \LaTex
                 !
?
```

## 链接

* TeX. SX:
* GitHub:

**Comment by note286** [comment]
`\LaTeX{}!`

**Comment by khf-big** [comment]
我刚重新确认了一下，应该是物院的硕博word模板改了，改了比较多的内容。其他学院好像还暂时没改。
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "whutug/whu-thesis"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月6日(星期一) 晚上10:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [whutug/whu-thesis] 很简单的问题，模板改了，去年年底的博士毕业论文就变格式了 (Issue #190)





 
你的逻辑是错的，是『学校规定的格式』变了，『模板』才需要改动。
 
同时最好提供出处，也就是学校的新规定。
