### ISSUE TITLE
whu-thesis-doc.tex 编译不了

### ISSUE THREAD

**Issue by ItsBean** [whutug/whu-thesis#195]
按照overleaf文档的要求，我上传了zip和simsun和simhei。然后编译whu-thesis-doc.tex .但是编译不了。请问有人成功了吗

**Comment by tanukihee** [comment]
doc 不是给你编译的，是给你看的，请编译 main

**Comment by note286** [comment]
https://github.com/whutug/whu-thesis/blob/master/whu-thesis-demo.tex

**Comment by tanukihee** [comment]
`whu-thesis.demo.tex`

**Comment by tanukihee** [comment]
是 `DEMO` 不是 `DOC`

**Comment by tanukihee** [comment]
请提供失败报错

**Comment by tanukihee** [comment]
你还是编译的 doc。

哪里说了 doc 是本科论文，你真的认真看了文档吗

**Comment by tanukihee** [comment]
![image](https://user-images.githubusercontent.com/34062491/227758073-0d3555c0-be21-4250-bb8d-e1d0071a90f7.png)

**Comment by tanukihee** [comment]
请看文档第3页

**Comment by note286** [comment]
@ItsBean 
![image](https://user-images.githubusercontent.com/16207292/227758147-fa6ef2cf-0f3c-47ce-98a6-b5659cb7b3f7.png)

**Comment by tanukihee** [comment]
> 你真的认真看了文档吗

**Comment by tanukihee** [comment]
![image](https://user-images.githubusercontent.com/34062491/227758489-a1ca9df1-ff17-4049-beda-3a69f4a4c7b5.png)

**Comment by note286** [comment]
`\documentclass[type=bachelor]{whu-thesis}`

**Comment by note286** [comment]
磨刀不误砍柴工，认真读一遍文档。

**Comment by Terrence-zzh** [comment]
我也是傻逼，找了好久才在这里找到
