### ISSUE TITLE
老板，你们家的论文模板怎么加伪代码?

### ISSUE THREAD

**Issue by ItsBean** [whutug/whu-thesis#196]
为什么我添加pkg后会发生这种冲突
![image](https://user-images.githubusercontent.com/74498109/227877806-ee8e819c-c60a-407a-a425-ea66b5223a14.png)

**Comment by note286** [comment]
不要加载其他算法包，或者你从`.cls`里删除`algorithm2e`的包加载以及适配语句。

**Comment by UOBpo22145** [comment]
老板，除了右上角引用，最新论文规范里的第二种引用方式怎么实现？<img width="499" alt="截屏2023-03-29 01 44 16" src="https://user-images.githubusercontent.com/121206119/228397876-baea1ef4-df5d-4b33-a562-f504c8d4690b.png">

**Comment by note286** [comment]
@UOBpo22145 你的问题与当前主题不符，请单独提问。
