### ISSUE TITLE
本科毕业论文引用格式

### ISSUE THREAD

**Issue by UOBpo22145** [whutug/whu-thesis#199]
2023年测绘学院发布的毕业论文书写规范中提到了两种引用格式
<img width="499" alt="截屏2023-03-29 01 44 16" src="https://user-images.githubusercontent.com/121206119/228398794-dbaddde1-5dc3-414d-876e-ca2e00b6608f.png">
除了右上角引用，请问如何实现第二种引用格式？

**Comment by note286** [comment]
`biblatex`下可以直接使用`\parencite{}`。

**Comment by sikouhjw** [comment]
> 直接使用\parencite{}显示Undefined control sequence。 如果在chapter开头导入biblatex的包，显示LaTeX Error: Can be used only in preamble.

模板配置了 biblatex，请你选择使用 `biblatex` 选项

**Comment by UOBpo22145** [comment]
是在抱歉，问一下怎么使用这个选项？你们的写法太高级，我是小白看不懂

**Comment by note286** [comment]
看文档了吗？？？Ctrl+F`style/bib-backend`。

**Comment by sikouhjw** [comment]
https://github.com/whutug/whu-thesis/blob/6f19c2e0d34bbfc752f86a7ea505154a185ff595/whu-thesis-doc.tex#L464-L469
我不相信是基础问题，我相信是你没有看手册。

**Comment by note286** [comment]
已经麻木了，毕竟看手册的也不会来问。

**Comment by UOBpo22145** [comment]
好的感谢！已经解决了，我设置cite-style=numerical-inline，
然后对使用右上角标的使用：
\textsuperscript{\cite{}}

**Comment by note286** [comment]
(⊙o⊙)…，算了，你觉得可以就行。

**Comment by UOBpo22145** [comment]
因为尝试使用biblatex后，参考文献格式不符合要求。

**Comment by note286** [comment]
你看一下2005和2015的规范就知道了到底符合不符合了。

**Comment by note286** [comment]
`natbib`你可以`\NewDocumentCommand\parencite{m}{\begingroup\citestyle{numbers}\cite{#1}\endgroup}`。

**Comment by sikouhjw** [comment]
1. https://github.com/whutug/whu-thesis/blob/6f19c2e0d34bbfc752f86a7ea505154a185ff595/whu-thesis-doc.tex#L471
2. https://github.com/zepinglee/gbt7714-bibtex-style/issues/95#issuecomment-1067924571

**Comment by UOBpo22145** [comment]
好的感谢！成功解决
