### ISSUE TITLE
图片怎么加引用？

### ISSUE THREAD

**Issue by csj199813** [whutug/whu-thesis#205]
## 检查

* [ ] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

* 操作系统
  + [ ] Windows 10
  + [ ] Windows 8/8.1
  + [ ] Windows 7
  + [ ] 更早版本的 Windows
  + [ ] macOS
  + [ ] Linux（请附发行版）

* TeX 发行版
  + [ ] TeX Live 
  + [ ] MiKTeX 
  + [ ] CTeX 套装 2.9.2.164
  + [ ] 更早版本的 CTeX 套装

* whu-thesis 版本

  

## 最小工作示例（MWE）

``` latex
\documentclass{whu-thesis}
\begin{document}
Hello, \LaTex!
\end{document}
```

（用 XeLaTeX 编译后）输出

``` latex
! Undefined control sequence.
l.3 Hello, \LaTex
                 !
?
```

## 链接

* TeX. SX:
* GitHub:

**Comment by sikouhjw** [comment]
1. 请不要只把问题发在标题，而不修改正文内容
2. 问题太过基础，不予回答，请自行检索，这是最基本的检索能力
3. 建议你阅读 `texdoc lshort-zh-cn`

**Comment by csj199813** [comment]
抱歉，是我没有注意到，这里的引用是指在caption中加入参考文献的引用\cite会报错

**Comment by sikouhjw** [comment]
> 抱歉，是我没有注意到，这里的引用是指在caption中加入参考文献的引用\cite会报错

这是描述不够详细导致的，提问请给全信息。

你可以使用 `\caption[xxx]{xxx \cite{ref}}` 在 `\caption` 中引用参考文献。

**Comment by note286** [comment]
请给出能复现问题的代码。

**Comment by csj199813** [comment]
\caption{xxx\cite{ref}}这样就会报错

**Comment by note286** [comment]
> \caption{xxx\cite{ref}}这样就会报错

无法复现你的问题。

```latex
\documentclass{whu-thesis}
\begin{document}
\begin{figure}
\caption{sss\cite{xxx}xxx}
\end{figure}
\end{document}
```

**Comment by csj199813** [comment]
已解决，\caption[xxx]{xxx \cite{ref}}可以通过编译
