### ISSUE TITLE
无法引用学位论文的问题？

### ISSUE THREAD

**Issue by Dalabomba** [whutug/whu-thesis#206]
Windows11，TeX Live <2022>，最新版whu-thesis模板

文件属性是bachelor，bib-backend采用默认设置，即bibtex
element中bibliography选择ref/refs，这个refs是我自己重新写的文件，原先的refs被我移到了工作目录之外。

我在refs.bib中如是添入了我想要引用的文献：

@mastersthesis{SHI2018,
author={史洋洋},
title={Ebola和百日咳传染病模型的动力学研究},
school={北京建筑大学},
year={2018},
}

文件成功编译，无任何提示或报错，但这一篇文章的引用却并未出现，编译效果如下：
![image](https://user-images.githubusercontent.com/92942189/231926766-643cb154-d153-4327-848a-19251f414185.png)
后面的参考文献目录中也没有出现这一文献的对应条目，可以说这一引用完全没有被编译出来。

尝试将bib中的内容改成英文，以确定是否是中文兼容性的问题（因为在这篇文献之前我没有引用过中文文献），结果依然是如上的编译效果。

请教大佬这个应该怎么解决？

**Comment by note286** [comment]
你使用bibtex编译了吗

**Comment by Dalabomba** [comment]
我把原先的bbl删了重新用bibtex单独编译，问题解决了。谢谢大佬~
以前写文件都是直接编译没出过这种问题，养成习惯了，以后一定单独用bibtex编译。求轻喷。

**Comment by note286** [comment]
只要描述清楚，即使比较简单，也没关系。最讨厌描述不清楚的，互相浪费时间。
