### ISSUE TITLE
参考文献字体好像不是五号，求解决方法？

### ISSUE THREAD

**Issue by firefoxking** [whutug/whu-thesis#208]
## 检查

* [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

* 操作系统
  + [x] Windows 10
  + [ ] Windows 8/8.1
  + [ ] Windows 7
  + [ ] 更早版本的 Windows
  + [ ] macOS
  + [ ] Linux（请附发行版）

* TeX 发行版
  + [ ] TeX Live 
  + [x] MiKTeX 
  + [ ] CTeX 套装 2.9.2.164
  + [ ] 更早版本的 CTeX 套装

* whu-thesis 版本

  

## 描述问题

对于硕士论文，参考文献章节我发现“参考文献”四个字是用的加粗方式，不是标准的黑体。参考文献内容似乎也不是五号字体，请问怎么才可以修改成五号字体。
```
\tl_if_eq:NnT \g__whu_option_type_tl { doctor }
  {
    \tl_const:Nn \c__whu_heading_tl
      { \__whu_spread_with:nn { 博士学位论文 } { \quad } }
    \tl_set:Nn \bibname { \zihao { 4 } \textbf { 参考文献 } }
    \tl_set:Nn \bibliographytypesize { \zihao { 5 } }
  }

\tl_if_eq:NnT \g__whu_option_type_tl { master }
  {
    \tl_if_eq:NnT \g__whu_option_class_tl { academic }
      {
        \tl_const:Nn \c__whu_heading_tl
          { \__whu_spread_with:nn { 硕士学位论文 } { \quad } }
      }
    \tl_if_eq:NnT \g__whu_option_class_tl { professional }
      {
        \tl_const:Nn \c__whu_heading_tl
          { \__whu_spread_with:nn { 硕士专业学位论文 } { \enskip } }
      }
    % \tl_set:Nn \bibname { \zihao { 4 } \textbf { 参考文献 } }
    % \tl_set:Nn \bibliographytypesize { \zihao { 5 } }
    \tl_set:Nn \bibname { \heiti \zihao { 4 } 参考文献  }
    \tl_set:Nn \bibliographytypesize { \zihao { 5 } }
  }
```

**Comment by sikouhjw** [comment]
https://github.com/whutug/whu-thesis/blob/6f19c2e0d34bbfc752f86a7ea505154a185ff595/whu-thesis.cls#L155-L169
这不都设置好了是黑体和五号字吗？请你给出你的依据，比如用尺子量出确实不是五号字、给出黑体与模板参考文献字样的对比图，否则你就是没有任何依据的提问。

**Comment by firefoxking** [comment]
我开始以为是这段代码设置了五号
<img width="576" alt="联想截图_20230419125911" src="https://user-images.githubusercontent.com/43486841/232971129-81ed319f-96ec-4b0a-9192-3607bb75c6e4.png">

```
\tl_set:Nn \bibliographytypesize { \zihao { 5 } }
```
但是我把这段修改为：
```
<img width="562" alt="联想截图_20230419130053" src="https://user-images.githubusercontent.com/43486841/232971300-333b7949-b233-4160-95ee-4eae1d033b09.png">

\tl_set:Nn \bibliographytypesize { \zihao { 2 } }
```
生成的pdf还是跟之前一样的。我不知道是不是我理解有问题，谢谢

**Comment by sikouhjw** [comment]
在导言区加上
```tex
\renewcommand\bibfont{\zihao{5}}
```
就可以调成五号字。

参考文献是否为黑体的问题，模板用的是『黑体』+『加粗』，所以依然属于黑体的范畴，只是需不需要加粗需要看学校的规范文件才能判断。

**Comment by firefoxking** [comment]
我尝试了这个方法，但是会产生报错显示：
```latex
LaTeX Error: Command \bibfont undefined.
```
换成下面的命令没有效果
```latex
\newcommand\bibfont{\zihao{5}}
```

**Comment by sikouhjw** [comment]
> 我尝试了这个方法，但是会产生报错显示：
> 
> ```
> LaTeX Error: Command \bibfont undefined.
> ```
> 
> 换成下面的命令没有效果
> 
> ```
> \newcommand\bibfont{\zihao{5}}
> ```

我搞错了，放正文区任意位置都可以。

**Comment by firefoxking** [comment]
可以了，谢谢！

**Comment by imfing** [comment]
> 可以了，谢谢！
