### ISSUE TITLE
如何添加页眉与正文之间的横线

### ISSUE THREAD

**Issue by Doctor-Do** [whutug/whu-thesis#209]
## 检查

* [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

* 操作系统
  + [x] Windows 10
  + [ ] Windows 8/8.1
  + [ ] Windows 7
  + [ ] 更早版本的 Windows
  + [ ] macOS
  + [ ] Linux（请附发行版）

* TeX 发行版
  + [x] TeX Live 
  + [ ] MiKTeX 
  + [ ] CTeX 套装 2.9.2.164
  + [ ] 更早版本的 CTeX 套装

* whu-thesis 版本

  

## 描述问题

我注意到武大硕博论文库里很多论文在页眉下面均会有一条横线与正文部分隔开，请问如何在页眉与正文之间添加这样一条横线？在使用文档中似乎没有看到，感谢！

**Comment by Eliaul** [comment]
`\renewcommand{\headrulewidth}{0pt}`
