### ISSUE TITLE
图片标题caption内添加引用cite时报错

### ISSUE THREAD

**Issue by crml233** [whutug/whu-thesis#211]
加了\protect还是报错，将cite放在caption{}外面不报错了，但是编译后引用上标与标题不在同一行了

**Comment by xkwxdyy** [comment]
给代码，下次再这样提问直接删除。

**Comment by crml233** [comment]
\caption{CBAM子模块示意图\cite{woo2018cbam}}
\caption{CBAM子模块示意图 \protect\cite{woo2018cbam}}
均报错

**Comment by crml233** [comment]
Extra }, or forgotten \endgroup.
<argument> ...AM子模块示意图 \cite {woo2018cbam}\relax }

**Comment by xkwxdyy** [comment]
<img width="1082" alt="image" src="https://user-images.githubusercontent.com/87134063/235282477-d0c46221-e210-4033-beb4-6ae60f8a61d1.png">

**Comment by xkwxdyy** [comment]
顺便一提，github 里提issue提供了提问模版。
