### ISSUE TITLE
Error：网安学院的不要用LaTeX写

### ISSUE THREAD

**Issue by entr0pia** [whutug/whu-thesis#217]
## 检查

* [x] 已在 issues 中进行搜索（包括已关闭的问题）

在现场，被批了

**Comment by SwitWu** [comment]
不同学院要求不同，数院是可以用的

**Comment by Tisword** [comment]
+1，已经被网安的老师批麻了

**Comment by sikouhjw** [comment]
怎么被批的（

**Comment by entr0pia** [comment]
比如字体问题。算法里面的公式不用正文字体（宋体或Times New Roman）就是不对，截图（虽然是保存为PDF格式）里面不是正文字体就是不对。别反驳，反驳就是要挂你

**Comment by note286** [comment]
@entr0pia 你使用Times风格数学字体不就好了，有很多的。

**Comment by 4N4RCHY** [comment]
网安的兄弟放心，计院的兄弟也被批惨了。。。

**Comment by SwitWu** [comment]
> 网安的兄弟放心，计院的兄弟也被批惨了。。。

什么情况

**Comment by 4N4RCHY** [comment]
> 

计院硕士的话建议别用这个模板了，虽然确实符合官方但是和学院（或者说学院的老师）认知的格式差距还是有挺多区别的。如果是用的overleaf的话，建议直接用overleaf的template里这个作者上传的那个模板，不知道什么原因这两个有很多区别

**Comment by 4N4RCHY** [comment]
> > 网安的兄弟放心，计院的兄弟也被批惨了。。。
> 
> 什么情况

计院硕士的话建议别用这个模板了，虽然确实符合官方但是和学院（或者说学院的老师）认知的格式差距还是有挺多区别的。如果是用的overleaf的话，建议直接用overleaf的template里这个作者上传的那个模板，不知道什么原因这两个有很多区别

**Comment by SwitWu** [comment]
> > > 网安的兄弟放心，计院的兄弟也被批惨了。。。
> > 
> > 
> > 什么情况
> 
> 计院硕士的话建议别用这个模板了，虽然确实符合官方但是和学院（或者说学院的老师）认知的格式差距还是有挺多区别的。如果是用的overleaf的话，建议直接用overleaf的template里这个作者上传的那个模板，不知道什么原因这两个有很多区别

可以提供一些细节问题

**Comment by 4N4RCHY** [comment]
> > > > 网安的兄弟放心，计院的兄弟也被批惨了。。。
> > > 
> > > 
> > > 什么情况
> > 
> > 
> > 计院硕士的话建议别用这个模板了，虽然确实符合官方但是和学院（或者说学院的老师）认知的格式差距还是有挺多区别的。如果是用的overleaf的话，建议直接用overleaf的template里这个作者上传的那个模板，不知道什么原因这两个有很多区别
> 
> 可以提供一些细节问题

细节问题的话，这个模板下的英文封面和计院的要求完全不一致，然后页眉底下没有横线。这两条是我身边每一个用这个模板的都被批的。其次还有一些某场答辩的老师认为有问题的地方

**Comment by xkwxdyy** [comment]
> 细节问题的话，这个模板下的英文封面和计院的要求完全不一致，然后页眉底下没有横线。这两条是我身边每一个用这个模板的都被批的。其次还有一些某场答辩的老师认为有问题的地方

你提供的这些信息对优化模版并没有什么作用。我只从你们的回复看到吐槽，如果开这个issue只是为了说这个的话，大可不必。

**Comment by entr0pia** [comment]
> 你提供的这些信息对优化模版并没有什么作用。我只从你们的回复看到吐槽，如果开这个issue只是为了说这个的话，大可不必。

可以整理一个哪些学院接受或不能接受LaTeX的列表

**Comment by tanukihee** [comment]
我先关了，你们整理出来的话再开一个 issue

**Comment by xkwxdyy** [comment]
> 可以整理一个哪些学院接受或不能接受LaTeX的列表

https://github.com/whutug/whu-thesis/discussions/218

**Comment by 4N4RCHY** [comment]
> > 细节问题的话，这个模板下的英文封面和计院的要求完全不一致，然后页眉底下没有横线。这两条是我身边每一个用这个模板的都被批的。其次还有一些某场答辩的老师认为有问题的地方
> 
> 你提供的这些信息对优化模版并没有什么作用。我只从你们的回复看到吐槽，如果开这个issue只是为了说这个的话，大可不必。

那为什么overleaf上的模板会和github上的模板不一样呢？

**Comment by xkwxdyy** [comment]
> 那为什么overleaf上的模板会和github上的模板不一样呢？

![image](https://github.com/whutug/whu-thesis/assets/87134063/de2e4928-24e1-4a2c-89a0-5b0987153d43)

**Comment by 4N4RCHY** [comment]
> > 那为什么overleaf上的模板会和github上的模板不一样呢？
> 
> ![image](https://user-images.githubusercontent.com/87134063/241396370-de2e4928-24e1-4a2c-89a0-5b0987153d43.png)

是啊，这就很神奇，3年前的模板反而是符合计院老师以为的规范的。

比如说英文封面，按照学校的印制规范就应该只有两个信息，英文标题和作者。但是按照计院相关老师发的“推荐”规范以及计院老师的普遍认知，这个英文封面必须有：英文标题、作者、导师、学校、写作年月。

你说我没有提供优化模板的信息，我确实提供不出，因为我知道你们的模板是符合规定的但是老师就是不认同。

**Comment by note286** [comment]
@4N4RCHY 请你直接提供相关Microsoft Word模板或者其他规范说明文件。

**Comment by 4N4RCHY** [comment]
我不知道这个是否是可以公开的文件，你们可以给一个邮箱我私发

**Comment by note286** [comment]
一个学院毕业设计论文模板又不是什么机密？？？？？？

**Comment by entr0pia** [comment]
我都没有见到网安学院发模板, 学院的网站上也没搜到

**Comment by note286** [comment]
或者可以考虑把提到的老师赛博化。

**Comment by entr0pia** [comment]
> > > 那为什么overleaf上的模板会和github上的模板不一样呢？
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/87134063/241396370-de2e4928-24e1-4a2c-89a0-5b0987153d43.png)
> 
> 是啊，这就很神奇，3年前的模板反而是符合计院老师以为的规范的。
> 
> 比如说英文封面，按照学校的印制规范就应该只有两个信息，英文标题和作者。但是按照计院相关老师发的“推荐”规范以及计院老师的普遍认知，这个英文封面必须有：英文标题、作者、导师、学校、写作年月。
> 
> 你说我没有提供优化模板的信息，我确实提供不出，因为我知道你们的模板是符合规定的但是老师就是不认同。

未定义行为, 永远是你错

**Comment by 4N4RCHY** [comment]
> 我都没有见到网安学院发模板, 学院的网站上也没搜到

那种行政的老师怕担责任或者说怕麻烦是不肯发的，我这个也是同学发我的

**Comment by river-li** [comment]
网安院没有模板= = 然后又有一堆不成文的规矩

**Comment by SwitWu** [comment]
> 网安院没有模板= = 然后又有一堆不成文的规矩

对于这种情形，模版难以做到适配，建议 word :)

**Comment by tanukihee** [comment]
或者自己在 `ctexbook` 基础上写（

**Comment by wangzhankun** [comment]
可以对whu-thesis.cls进行如下修改，2024届，目前无法保证绝对能过

```patch
 
diff --git a/whu-thesis.cls b/whu-thesis.cls
index cc79025..665fb45 100644
--- a/whu-thesis.cls
+++ b/whu-thesis.cls
@@ -10,7 +10,7 @@
 \RequirePackage{expl3 , xparse , l3keys2e}
 \ProvidesExplClass{whu-thesis}{2021/05/20}{0.6d}
   {Wuhan University Thesis Template}
-
+\renewcommand{\cleardoublepage}{\clearpage}
 % 将编译命令限制为 XeLaTeX 和 LuaLaTeX
 \msg_new:nnn { whu-thesis } { EngineNotSupported }
   { whu-thesis~does~not~support~#1,~please~use~XeLaTeX~or~LuaLaTeX~instead. }
@@ -218,7 +218,7 @@
 % 草稿模式下，显示边框
 
 \RequirePackage { fancyhdr }        % 页眉页脚宏包
-\tl_set:Nn \headrulewidth { \c_zero_dim }  % 页眉线宽
+\tl_set:Nn \headrulewidth { 0.4pt }  % 页眉线宽
 \tl_set:Nn \footrulewidth { \c_zero_dim }  % 页脚线宽
 
 \AtEndPreamble
@@ -1233,13 +1233,28 @@
 \cs_new_protected:Npn \__whu_make_title_en:
   {
     \__whu_new_chapter_page:
+    \vspace*{4\baselineskip} % 插入4行的空白
     \begin { center }
       \zihao { 2 } \g__whu_info_title_en_tl
     \end { center }
-    \vfill
+    \vspace*{5\baselineskip} 
     \begin { center }
+      \zihao { 4 } By\\
       \zihao { 4 } \g__whu_info_author_en_tl
     \end { center }
+    \vspace*{2\baselineskip} 
+    \begin { center }
+      \zihao { 3 } Supervised by\\
+      Prof.\ Zhao\ Bo
+    \end { center }
+    \vfill
+    \begin{center}
+      % university name
+      \zihao { 3 } Wuhan\ University
+    \end{center}
+    \begin { center }
+      \zihao { 3 } May,\ 2024
+    \end { center }
     \__whu_new_chapter_page:
   }
 
-- 
2.34.1
```

**Comment by sikouhjw** [comment]
> 可以对whu-thesis.cls进行如下修改，2024届，目前无法保证绝对能过

针对网安学院的？

**Comment by wangzhankun** [comment]
> > 可以对whu-thesis.cls进行如下修改，2024届，目前无法保证绝对能过
> 
> 针对网安学院的？

是的。

**Comment by wangzhankun** [comment]
> > 可以对whu-thesis.cls进行如下修改，2024届，目前无法保证绝对能过
> 
> 针对网安学院的？

基本完成了所有修改。与往届学长论文对比基本一只。

**Comment by YuanJ-yj** [comment]
> 比如字体问题。算法里面的公式不用正文字体（宋体或Times New Roman）就是不对，截图（我是保存为PDF的矢量图）里面不是正文字体就是不对。别反驳，反驳就是要挂你

那正文里面的公式描述，也需要用正文字体吗？公式直接用latex出来的字体不是times

**Comment by wangzhankun** [comment]
> > > > 可以对whu-thesis.cls进行如下修改，2024届，目前无法保证绝对能过
> > > 
> > > 
> > > 针对网安学院的？
> > 
> > 
> > 基本完成了所有修改。与往届学长论文对比基本一只。
> 
> 求问最后能否通过

通过了

**Comment by joeCarf** [comment]
> > > > > 可以对whu-thesis.cls进行如下修改，2024届，目前无法保证绝对能过
> > > > 
> > > > 
> > > > 针对网安学院的？
> > > 
> > > 
> > > 基本完成了所有修改。与往届学长论文对比基本一只。
> > 
> > 
> > 求问最后能否通过
> 
> 通过了

大佬求问你这个pr合进来了嘛
