### ISSUE TITLE
目录中3级标题的缩进

### ISSUE THREAD

**Issue by paozhuanis1** [whutug/whu-thesis#237]
## 检查

* [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

* 操作系统
  + [x] Windows 10
  + [ ] Windows 8/8.1
  + [ ] Windows 7
  + [ ] 更早版本的 Windows
  + [ ] macOS
  + [ ] Linux（请附发行版）

  

## 描述问题

目录中3级标题给的定稿范例是在2级标题基础上还有缩进，如下图
![QQ图片20240124183431](https://github.com/whutug/whu-thesis/assets/86753693/3f8c5c60-0072-4773-9a8f-2a71e1fdf37d)

但是这个模板2级标题和3级标题的缩进是一样的，请问应该如何修改实现这个缩进

**Comment by SwitWu** [comment]
<img width="1074" alt="image" src="https://github.com/whutug/whu-thesis/assets/39337667/3580c9df-7ad4-4ba5-a13c-6fc7e6ffa23a">
我手上的版本是没有缩进的

**Comment by JindaiKanata** [comment]
![1](https://github.com/whutug/whu-thesis/assets/97715592/f1abe6f3-8a3a-48fd-8b7e-d34949781978)
这里的\hspace{}是空格长度，我选择的2\ccwd是两个中文字符，希望有帮助

**Comment by xkwxdyy** [comment]
> <img alt="image" width="1074" src="https://private-user-images.githubusercontent.com/39337667/299648497-3580c9df-7ad4-4ba5-a13c-6fc7e6ffa23a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5ODA0MDgsIm5iZiI6MTcxMjk4MDEwOCwicGF0aCI6Ii8zOTMzNzY2Ny8yOTk2NDg0OTctMzU4MGM5ZGYtN2FkNC00YmE1LWExM2MtNmZjN2U2ZmZhMjNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEzVDAzNDgyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0MTRlYjdhZmY1NjljNzRlMDM1MjUxOTI0YWNhYWMxODkxZjY5NzkyMjE4ZjlhNDA5OTliMDNkNjBlNDYzNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vODMos-7NmBnF_mprm9za4UNXi5ZUorcN7klQxjNHpg"> 我手上的版本是没有缩进的

最新的那个版本里面有缩进了。

**Comment by JindaiKanata** [comment]
> > <img alt="image" width="1074" src="https://private-user-images.githubusercontent.com/39337667/299648497-3580c9df-7ad4-4ba5-a13c-6fc7e6ffa23a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5ODA0MDgsIm5iZiI6MTcxMjk4MDEwOCwicGF0aCI6Ii8zOTMzNzY2Ny8yOTk2NDg0OTctMzU4MGM5ZGYtN2FkNC00YmE1LWExM2MtNmZjN2U2ZmZhMjNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEzVDAzNDgyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0MTRlYjdhZmY1NjljNzRlMDM1MjUxOTI0YWNhYWMxODkxZjY5NzkyMjE4ZjlhNDA5OTliMDNkNjBlNDYzNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vODMos-7NmBnF_mprm9za4UNXi5ZUorcN7klQxjNHpg"> 我手上的版本是没有缩进的
> 
> 最新的那个版本里面有缩进了，不过是本科的。这个 issue 怎么不提是哪个版本的。

![image](https://github.com/whutug/whu-thesis/assets/97715592/79d2d705-f9fa-4464-9d07-44405a3363a5)
我手上拿到过2008版本和你的一样

**Comment by SwitWu** [comment]
Completed in be97f00e8fd8d19a02c1b2ef9240a2941aa58cec
