### ISSUE TITLE
参考文献引用格式 数字编码

### ISSUE THREAD

**Issue by wangzhankun** [whutug/whu-thesis#238]
默认设置不是数字编码引用参考文献，而是作者年份。如需改成数字顺序编码的参考文献，需要在whu-thesis-demo.tex中添加如下信息：
<img width="522" alt="image" src="https://github.com/whutug/whu-thesis/assets/35724924/08ddbb1c-6f1c-458a-ba99-b6884b46e722">

其他的修改格式参见whu-thesis-doc.pdf：
<img width="440" alt="image" src="https://github.com/whutug/whu-thesis/assets/35724924/93d2273f-5bf5-40d8-95dc-bf80d7fd9a7c">

**Comment by sikouhjw** [comment]
手册内存在的内容就没必要再提 issue 了

**Comment by haohhhhh** [comment]
怎么同时使用上标和文内形式

**Comment by SwitWu** [comment]
> 怎么同时使用上标和文内形式

看手册
