### ISSUE TITLE
关于GB7714文献格式引用的问题。

### ISSUE THREAD

**Issue by wuchuanjun** [whutug/whu-thesis#240]
如题，打包文件里面的文献格式引用不对。武汉大学推荐使用author-year这种引用。打包文件里无法实现这种引用格式。 且引用格式正常是出现在正文括号里，包括人名与年份。
举个例子：

这是正文内容（zhang et al., 2009）.

这种才是正确的引用。如何实现呢？

**Comment by tanukihee** [comment]
默认即是作者-年样式，请阅读文档

**Comment by SHyeong1** [comment]
请问一下我引用默认是作者（年份），怎么变成 作者，年份，感激不尽

**Comment by wuchuanjun** [comment]
将\cite{}改成\citep{}

**Comment by SwitWu** [comment]
> 谢谢，找到了解决方案。 还有一个问题，仅有两位作者的文献，如何在引文中全部标注？

用的是 BibTeX 吗

**Comment by wuchuanjun** [comment]
是的。bibTex

**Comment by SwitWu** [comment]
`\citet*` 和 `\citep*` 都会列出全部作者

**Comment by wuchuanjun** [comment]
OK，意思就是需要自己调整是吧。就是你知道只有两个作者的 就是用上述两个去引用。明白了。感谢~
