### ISSUE TITLE
郑重声明的个人签名不能直接插入图片吗

### ISSUE THREAD

**Issue by Cang-yan** [whutug/whu-thesis#242]
## 检查

* [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

overleaf

## 描述问题

郑重声明的定义是.cls文件里，我想在“个人签名”处直接插入电子签名。但是.cls文件没有这样的操作吧。难道是只能后续通过pdf编辑软件插入电子签名吗

**Comment by SwitWu** [comment]
> 难道是只能后续通过pdf编辑软件插入电子签名吗

也可以制作电子签名的文件（png、PDF 等），然后修改 `.cls`，直接在 `.cls` 中插入

**Comment by Cang-yan** [comment]
请问如何插入呢？我没找到相关命令

**Comment by SwitWu** [comment]
https://github.com/whutug/whu-thesis/blob/03d58f0854fee63d5ff0dda00f40d02714bf41ce/whu-thesis.cls#L1261

**Comment by Cang-yan** [comment]
哦了解了，谢谢！

**Comment by Cang-yan** [comment]
哦了解了！  谢谢

**Comment by sikouhjw** [comment]
https://github.com/sikouhjw/gdutthesis/blob/67b44686baff01f29cf4d34c7659b9c110e6151f/main.tex#L118-L120
提供接口更方便点
