### ISSUE TITLE
将公式字体改为cambria

### ISSUE THREAD

**Issue by HElenZWHU** [whutug/whu-thesis#245]
按照 #232 中的改法，引入cambria.ttc以后，\boldsymbol加粗就失效了

**Comment by tanukihee** [comment]
cambria 不是 unicode-math 字体，cambria math 才是

**Comment by HElenZWHU** [comment]
从C:\Windows\Fonts中引入了cambria math对应的cambria.ttc文件，依旧不能使用\boldsymbol

**Comment by HElenZWHU** [comment]
而C:\Windows\Fonts中的cambria中有四个文件，一个ttc 还有三个ttf文件

**Comment by SwitWu** [comment]
用 `\symbfit` 试试

**Comment by SwitWu** [comment]
```tex
\documentclass{article}
\usepackage{unicode-math}
\usepackage{fontspec}
\setmainfont{Cambria}
\setmathfont{Cambria Math}
\begin{document}
This is some text
$\alpha\beta \symbfit{a\mu M\alpha}$

\end{document}
```
<img width="571" alt="image" src="https://github.com/whutug/whu-thesis/assets/39337667/9e76af0d-edee-4f03-b918-c953681440b9">

**Comment by HElenZWHU** [comment]
厉害！这个问题已解决，但是请问指示函数应该用哪个包？（Indicator function ）\mathbb现在的显示很奇怪

**Comment by SwitWu** [comment]
`\mathbb{1}`? 效果是怎么样的？

**Comment by HElenZWHU** [comment]
<img width="55" alt="捕获" src="https://github.com/whutug/whu-thesis/assets/43406963/77075b0a-e1f5-429c-aa8d-e4777b37cc0e">

**Comment by SwitWu** [comment]
> <img alt="捕获" width="55" src="https://private-user-images.githubusercontent.com/43406963/316482784-77075b0a-e1f5-429c-aa8d-e4777b37cc0e.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNjYwMjMsIm5iZiI6MTcxMTM2NTcyMywicGF0aCI6Ii80MzQwNjk2My8zMTY0ODI3ODQtNzcwNzViMGEtZTFmNS00MjljLWFhOGQtZTQ3NzdiMzdjYzBlLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDExMjIwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmYzM5OTJiMmIwYTllMWZkYjRmODlmMGFjZTcwNjc3Y2MyMDRiMGI4MGU0OWRkZjIwZWI5YjI4ZGUyNDc1OTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6rkWiW048-SxjzFWwjs4vChf6hQvdJmlV-oKU4rJr1o">

就是这样啊，你想要什么样的
