### ISSUE TITLE
参考文献列表里如何不显示未引用的文献

### ISSUE THREAD

**Issue by HElenZWHU** [whutug/whu-thesis#250]
目前的版本好像bib中的所有参考文献都会显示出来？

**Comment by SwitWu** [comment]
主文件中的 `\nocite{*}` 删掉

**Comment by HElenZWHU** [comment]
这个项目的主文件中没有这一行呀

**Comment by tanukihee** [comment]
https://github.com/whutug/whu-thesis/blob/f85241ad8e44f7bbb80d8043bfafc98c6a0f9fb6/pages/chapter3.tex#L12

**Comment by HElenZWHU** [comment]
收到！
