### ISSUE TITLE
希望维护者能够更新一下2024届的本科毕业论文模板

### ISSUE THREAD

**Issue by zhengxiongli08** [whutug/whu-thesis#252]
## 检查

* [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

* 操作系统
  + [x] Windows 10
  + [ ] Windows 8/8.1
  + [ ] Windows 7
  + [ ] 更早版本的 Windows
  + [ ] macOS
  + [ ] Linux（请附发行版）

* TeX 发行版
  + [x] TeX Live <2023>
  + [ ] MiKTeX 
  + [ ] CTeX 套装 2.9.2.164
  + [ ] 更早版本的 CTeX 套装

## 描述问题
学校已经更新了新的2024届本科生毕业论文模板，在封面以及前几页的排版布局方面有比较大的变化，希望维护者能够更新一下当前的本科论文模板。下附“武汉大学本科毕业论文（设计）书写印制规范（2024年版）”和“本科毕业论文（设计）模板”，以供参考。

我已经注意到pr里面有一位计院的同学尝试提交一个[更新](https://github.com/whutug/whu-thesis/pull/248)，不过已经close了。我是物院的，我们的模板和他们计院的是一样的，可以确认为是公用的模板。
[论文书写规范与参考模板-20240315.zip](https://github.com/whutug/whu-thesis/files/14884484/-20240315.zip)

**Comment by xkwxdyy** [comment]
是学院在群里发的吗？有没有教务处的链接

**Comment by xkwxdyy** [comment]
主要是不确定学院是否在这基础上改动了，所以最好能有教务处官方的 link

**Comment by xkwxdyy** [comment]
更新肯定是会更新的，不过不确保更新时间，你们是今年就要用吗？本科的毕业论文最迟什么时候上交

**Comment by zhengxiongli08** [comment]
> 是学院在群里发的吗？有没有教务处的链接

是学院在群里发布的，并没有发布网页链接。
![image](https://github.com/whutug/whu-thesis/assets/106097290/d951070b-2236-479d-857e-e5cd48ff172d)

而且按照“书写印制规范”该文件的抬头部分说明，是学校范围的。
![image](https://github.com/whutug/whu-thesis/assets/106097290/43b4548c-3698-4131-8b7a-b23e118fbb05)

**Comment by zhengxiongli08** [comment]
> 更新肯定是会更新的，不过不确保更新时间，你们是今年就要用吗？本科的毕业论文最迟什么时候上交

主要是标题、章节字体，学号的位置这种改动，其他变动不大。是今年2024届的标准，学校要求是4.20交初稿查重。

**Comment by xkwxdyy** [comment]
了解了。麻烦 @SwitWu 处理一下吧。

**Comment by zhengxiongli08** [comment]
> 了解了。麻烦 @SwitWu 处理一下吧。

我看到之前有一位计院的同学已经做了许多commits并提交了pr，https://github.com/whutug/whu-thesis/pull/248，或许可以merge一下？

**Comment by xkwxdyy** [comment]
@zhengxiongli08 我帮你修改了两次 md 链接了，不要直接粘贴链接，用 `[]()` 的样式。每次提交前点“Preview” 查看一下效果。

**Comment by zhengxiongli08** [comment]
> @zhengxiongli08 我帮你修改了两次 md 链接了，不要直接粘贴链接，用 `[]()` 的样式。每次提交前点“Preview” 查看一下效果。

学到了，不好意思，麻烦你了

**Comment by SwitWu** [comment]
> 了解了。麻烦 @SwitWu 处理一下吧。

好，我下午 merge 一下

**Comment by Cang-yan** [comment]
我想问一下新模板最后的封底空白页是什么，需要加吗
