### ISSUE TITLE
硕士毕业论文指导教师为空&目录出现两个中英文摘要

### ISSUE THREAD

**Issue by redwangwangwang** [whutug/whu-thesis#254]
设置\documentclass[type=master,oneside]{whu-thesis}，但是指导教师处填写内容不显示，中英文摘要在目录各出现两遍，请问如何解决：
![image](https://github.com/whutug/whu-thesis/assets/66422715/b1421a68-2683-4ecb-92e5-cf3c685106e1)
![image](https://github.com/whutug/whu-thesis/assets/66422715/a791f166-9580-48d2-b3f2-2a8e56225bcf)

**Comment by SwitWu** [comment]
用刚才更新的，`\whusetup` 中使用 `advisor = {张三, 教授}`
