### ISSUE TITLE
如何在摘要中进行引用

### ISSUE THREAD

**Issue by eraserqqq** [whutug/whu-thesis#255]
摘要貌似不在正文内容中，\cite会报错，有没有大佬知道怎么解决

**Comment by SwitWu** [comment]
1. 本科还是硕士？
2. 哪个分支？

**Comment by eraserqqq** [comment]
本科毕业论文 
main分支

**Comment by SwitWu** [comment]
你先用 biblatex，别用 bibtex

**Comment by SwitWu** [comment]
确实能够复现问题，我整理了一个 MWE，请 @zepinglee 李泽平老师看看这个问题的原因在哪儿

## MWE 文件
[MWE.zip](https://github.com/whutug/whu-thesis/files/14971221/MWE.zip)


其中 `c.tex` 是主文件，`abstract.tex` 是外部摘要文件（通过 `\file_input:n` 导入进主文件），运行 `xelatex + bibtex + xelatex * 2` 后 PDF 如下图
<img width="1204" alt="image" src="https://github.com/whutug/whu-thesis/assets/39337667/e8ba1287-c40a-4b02-bf0d-e15b4c96ae60">
其实第一次运行 `xelatex` 的时候就有警告 ```LaTeX Warning: Citation `[' on page 1 undefined on input line 1.```

**Comment by eraserqqq** [comment]
也许是因为摘要不是在\begin{document}中进行引入的？

**Comment by xkwxdyy** [comment]
> 确实能够复现问题，我整理了一个 MWE，请 @zepinglee 李泽平老师看看这个问题的原因在哪儿
> 
> ## MWE 文件
> [MWE.zip](https://github.com/whutug/whu-thesis/files/14971404/MWE.zip)
> 
> 其中 `c.tex` 是主文件，`abstract.tex` 是外部摘要文件（通过 `\file_input:n` 导入进主文件）
> 
> ## 复现步骤及结果
> 运行 `xelatex + bibtex + xelatex * 2` 后 PDF 如下图 <img alt="image" width="1204" src="https://private-user-images.githubusercontent.com/39337667/322284031-e8ba1287-c40a-4b02-bf0d-e15b4c96ae60.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNDMyODcsIm5iZiI6MTcxMzE0Mjk4NywicGF0aCI6Ii8zOTMzNzY2Ny8zMjIyODQwMzEtZThiYTEyODctYzQwYS00YjAyLWJmMGQtZTE1YjRjOTZhZTYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDAxMDMwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlMDlhMzc1ZWFmYzFlNmY2NzRlNDdlNDExM2U4NzZiMjA2YTZkODI2MTAwMWUzNzk0ZGIzNzkyNzdjMjI1NjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t9TmmmsaPO0FFh69BXkVWU_WE3sEoKvCX3dxA-ELdQw"> 其实第一次运行 `xelatex` 的时候就有警告 `` LaTeX Warning: Citation `[' on page 1 undefined on input line 1. ``

刚看了一下，我找到问题了，出在 cls 文件里的 `\AtBeginDocument`，改成 `\ctex_after_end_preamble:n` 即可：
```latex
% \AtBeginDocument { \__whu_make_abstract: }
\ctex_after_end_preamble:n { \__whu_make_abstract: }
```
<img width="500" alt="image" src="https://github.com/whutug/whu-thesis/assets/87134063/76509a2b-d644-463d-8a9f-1c69ca1a8128">

**Comment by xkwxdyy** [comment]
应该是 `\AtBeginDocument` 的钩子执行阶段还没有开始 `bibtex` 的设置之类的原因造成的，所以往后一点即可。

**Comment by xkwxdyy** [comment]
不用 `ctex` 的钩子，用 `begindocument/end` 也可以：
```latex
\AddToHook { begindocument / end } { \__whu_make_abstract: }
```

**Comment by xkwxdyy** [comment]
`lthooks-doc.pdf` 里也说了，`\AtBeginDocument` 钩子的内容不应该用来输出 typing 的东西：
<img width="1440" alt="image" src="https://github.com/whutug/whu-thesis/assets/87134063/b182dd11-8782-4a40-b0be-e4b69bf583e1">

**Comment by SwitWu** [comment]
行，那就先换成 `begindocument / end`

**Comment by eraserqqq** [comment]
感谢各位，完美解决了问题
