### ISSUE TITLE
为什么我编辑出来是研究生毕业论文

### ISSUE THREAD

**Issue by realwangjiahao** [whutug/whu-thesis#256]
我是写本科论文的，但是这个编译出来是研究生的，请问一下怎么操作

**Comment by SwitWu** [comment]
阅读[手册](https://github.com/whutug/whu-thesis/blob/main/whu-thesis-doc.pdf)

**Comment by nanbeiduoqilu** [comment]
似乎当前版本的手册被移除了

**Comment by SwitWu** [comment]
在 Release 中
