### ISSUE TITLE
专业硕士封面更新

### ISSUE THREAD

**Issue by chenghancc** [whutug/whu-thesis#257]
根据 [武汉大学硕士学位论文印制规定](https://gs.whu.edu.cn/info/1022/3235.htm)，专业硕士封面已经更新，希望能够同步一下最新的专业硕士封面，谢谢！

**Comment by xkwxdyy** [comment]
看了一下确实更新了，但是 title 这却没更新时间
<img width="424" alt="image" src="https://github.com/whutug/whu-thesis/assets/87134063/13d63ab8-8f70-4d9d-b251-64082ea218c2">
文件名也没写更新时间，文件里面才有时间，这不下载谁知道更新了（

**Comment by SwitWu** [comment]
博士论文的封面也更新了，见[武汉大学博士学位论文撰写及印制规格的规定](https://gs.whu.edu.cn/info/1022/3231.htm)。

**Comment by SwitWu** [comment]
@chenghancc 更新了封面，试一下效果

**Comment by AiberChou** [comment]
@SwitWu 更新之后，页眉不是“武汉大学硕士学位论文”和论文名交替出现了，同时去年的学术硕士英文封面是这个样子，麻烦您能更新一下
![image](https://github.com/whutug/whu-thesis/assets/113881643/f7554e90-7800-42b1-ba66-a25eb9e481e4)

**Comment by SwitWu** [comment]
我见过多个版本的英文封面，不确定哪一个才是官方认定的

**Comment by SwitWu** [comment]
> 页眉不是“武汉大学硕士学位论文”和论文名交替出现了

这个是因为开启了 `oneside` 选项

**Comment by SwitWu** [comment]
@AiberChou 你可以提供一份最新版的 word 文件吗（我主要用英文封面那一页

**Comment by SwitWu** [comment]
我手上有一份计算机学院的《研究生学位论文的写作要求与规范》，发布日期是2023年9月。其中的英文封面与@AiberChou 的截图大致相同，但仍有差别之处。

附件：
[计算机学院研究生学位论文写作要求与规范（2023-09）.pdf](https://github.com/whutug/whu-thesis/files/15026367/2023-09.pdf)

**Comment by SwitWu** [comment]
> @SwitWu 我也有这份计院规范，这是word版本 [硕士论文规范）.docx](https://github.com/whutug/whu-thesis/files/15026523/default.docx)

哪个是官方的？

**Comment by AiberChou** [comment]
> > @SwitWu 我也有这份计院规范，这是word版本 [硕士论文规范）.docx](https://github.com/whutug/whu-thesis/files/15026523/default.docx)
> 
> 哪个是官方的？

这个就不清楚了，这也是同学给的

**Comment by SwitWu** [comment]
研究生院对英文封面的要求是比较粗糙的，见[武汉大学硕士学位论文印制规定](https://gs.whu.edu.cn/info/1022/3235.htm)

> 论文英文题目（专用—页纸，上方为题目用宋体2号字，下方为研究生姓名宋体4号字、外文专业应有中文题目）

如果研究生院不给定一个统一的样式，那么各个院的英文封面很可能各不相同，我在想是否直接给用户一个接口，让用户自己单独制作英文封面放入项目文件夹，再由 cls 负责将该封面插入主文件。

**Comment by xkwxdyy** [comment]
> 研究生院对英文封面的要求是比较粗糙的，见[武汉大学硕士学位论文印制规定](https://gs.whu.edu.cn/info/1022/3235.htm)
> 
> > 论文英文题目（专用—页纸，上方为题目用宋体2号字，下方为研究生姓名宋体4号字、外文专业应有中文题目）
> 
> 如果研究生院不给定一个统一的样式，那么各个院的英文封面很可能各不相同，我在想是否直接给用户一个接口，让用户自己单独制作英文封面放入项目文件夹，再由 cls 负责将该封面插入主文件。

快用 `xtemplate` 写一个）

**Comment by Liuyerui** [comment]
现在有大佬更新封面了吗

**Comment by Liuyerui** [comment]
> <img alt="image" width="626" src="https://private-user-images.githubusercontent.com/39337667/324736315-237d4c12-dd1e-442b-be61-e4d9c8bde043.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NTc3NzIsIm5iZiI6MTcxMzg1NzQ3MiwicGF0aCI6Ii8zOTMzNzY2Ny8zMjQ3MzYzMTUtMjM3ZDRjMTItZGQxZS00NDJiLWJlNjEtZTRkOWM4YmRlMDQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDA3MzExMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1YWFmZWQ4MDI4YzJlYWI0ODAxMTA3OGZhOWRjOGZkNDE2YmZkZDQ1Yzg2MmY2ZmRkYTdiNGUyZGMwODYyOTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GmKj4-MYERuIhXt6TpLdaIuA4M8hF7SRUBq2rELVsdo">
> rebuild 分支设计了计算机学院的封面，有需求的直接用 rebuild 分支

好的谢谢

**Comment by SwitWu** [comment]
https://github.com/whutug/whu-thesis/blob/263ae9ace8f3f128350935535be8c3364126981c/demo.tex#L28

把这一行取消注释
