### ISSUE TITLE
部分导师只接受学生提交.docx文件

### ISSUE THREAD

**Issue by Crilliant** [whutug/whu-thesis#261]
同学们在决定使用latex写毕业论文之前，最好向导师问清楚是否可以向他提交pdf文件。比如，我的毕设指导老师要求学生必须提交word文件，以便于他的批注修订。

我在pdf转word后，发现论文格式很混乱，公式、引用等部分的格式必须手工校正。

**Comment by SwitWu** [comment]
这与本项目无关，如果既想使用 LaTeX，又想最终可到 word 文件，可以考虑使用一些转换工具（如 pandoc）。
