### ISSUE TITLE
请问博士论文摘要页页眉下方没有横线需要如何调整？

### ISSUE THREAD

**Issue by HN-Jiang** [whutug/whu-thesis#262]
![图片](https://github.com/whutug/whu-thesis/assets/53942586/0f6dad41-74cb-4e0b-813d-9f8549d3b2e8)
![图片](https://github.com/whutug/whu-thesis/assets/53942586/da38e132-03cb-41a2-8912-81063e7eb588)

**Comment by SwitWu** [comment]
确定使用的是最新版？

**Comment by HN-Jiang** [comment]
![图片](https://github.com/whutug/whu-thesis/assets/53942586/6582c4b2-d6e1-47cf-9781-cd58442ad2ba)
最新末班输出的结果也是一样，使用【type=doctor】

**Comment by SwitWu** [comment]
你在本地模版文件夹下运行 `git log`，我看看最新的 commit 是什么？

**Comment by SwitWu** [comment]
我使用最新版，摘要页是有页眉横线的
<img width="1213" alt="image" src="https://github.com/whutug/whu-thesis/assets/39337667/f701fc45-7cf5-4309-83c9-b7b0b6d4312b">
