### ISSUE TITLE
本科论文：页眉未居中；目录字体和字号错误

### ISSUE THREAD

**Issue by RemeaMiku** [whutug/whu-thesis#263]
仅针对本科模板
### 1. 页眉未居中
**目标样式：**
![image](https://github.com/whutug/whu-thesis/assets/73517033/d10879fe-1d0e-4153-a0f6-aa55af333c4c)
**实际样式：**
![image](https://github.com/whutug/whu-thesis/assets/73517033/a281dc5c-ef7b-4304-826d-89a2e6dc2730)
**可能的解决方案：**
将 244 行的 `\hbox_to_wd:nn { 9 cm }{武汉大学本科毕业论文（设计）}` 改为 `\makebox[8cm][s]{武汉大学本科毕业论文（设计）}`；第 269 行的 `\headrulewidth { 1pt } ` 改为 `\headrulewidth { 0.5pt }`
**修改后样式：**
![image](https://github.com/whutug/whu-thesis/assets/73517033/e9fde9d1-80ba-4d6a-934c-6488953af885)

### 2. 目录字体和字号错误
**目标样式：**
章的标题为宋体加粗小四号，其他内容为宋体小四号
![image](https://github.com/whutug/whu-thesis/assets/73517033/f7faa66d-9ffe-49c3-843d-44b51eea32fe)
**实际样式：**
![image](https://github.com/whutug/whu-thesis/assets/73517033/56362d78-684c-4ce2-a6c4-b4c2914814e8)
**可能的解决方案：**
将第 366 行的 `\zihao { 5 }` 改为 `\zihao { -4 }`；第 388 行的 `\heiti \zihao { 4 }` 改为 `\bfseries \zihao { -4 }`；第 389 行的 `\zihao { 5 }` 改为  `\zihao { -4 } `
**修改后样式：**
![image](https://github.com/whutug/whu-thesis/assets/73517033/0c99496b-5358-43a1-9962-7c630ca70759)

**Comment by xkwxdyy** [comment]
哪里获取的，release 还是某个分支

**Comment by RemeaMiku** [comment]
> 哪里获取的，release 还是某个分支

main

**Comment by SwitWu** [comment]
目录的问题我在 rebuild 分支改了，但是 main 没改

**Comment by RemeaMiku** [comment]
还有点小问题，我看规范里致谢和附录的标题中间是有间隔的，模板没有，可以考虑跟规范的一致

**Comment by xkwxdyy** [comment]
> 还有点小问题，我看规范里致谢和附录的标题中间是有间隔的，模板没有，可以考虑跟规范的一致

这个好改的，本科有完整的规范文件。硕博的就给封面、声明页这些文件，规范说明里又含糊不清。

**Comment by LinXu-LinXu** [comment]
页眉问题我也遇到了，可以更新tex版本到2023或者2024解决

**Comment by SwitWu** [comment]
rebuild 分支转为 main，此问题已解决
