### ISSUE TITLE
Overleaf上使用字体疑似不正确

### ISSUE THREAD

**Issue by ZhongYic00** [whutug/whu-thesis#264]
### 检查清单

- [X] 我已在 issues 中进行搜索（包括已关闭的问题）

### 操作系统

Overleaf

### TeX 发行版

Tex Live 2023

### 模板来源

main

### 描述 Bug

虽然有定义Overleaf环境下的字体，但判断系统环境处
https://github.com/whutug/whu-thesis/blob/8d8f434753641a23e8b920e4609812f6fbbb2939/whu-thesis.cls#L700
似乎只判了win、fandol和mac，导致未从上传字体文件中读取

**Comment by tanukihee** [comment]
![image](https://github.com/whutug/whu-thesis/assets/34062491/38d06e25-e422-43a0-b54d-956910c6a1bc)

**Comment by ZhongYic00** [comment]
thx，我之后有空再排查一下，碰到的具体症状是overleaf上它提示fandol中有找不到的字形所以怀疑这里没设overleaf默认到fandol了

**Comment by alicia2739** [comment]
救命，请问这个最好怎么解决了

**Comment by SwitWu** [comment]
> 救命，请问这个最好怎么解决了

用新版

**Comment by alicia2739** [comment]
View it on Github



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年05月01日 19:16 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [whutug/whu-thesis] Overleaf上使用字体疑似不正确 (Issue #264) |

Closed #264 as completed.
