### ISSUE TITLE
如何把中文引用的etal 修改为等

### ISSUE THREAD

**Issue by chenkang455** [whutug/whu-thesis#267]
### 检查清单

- [ ] #268

### 操作系统

win11

### TeX 发行版

overleaf

### 您使用的模版来源

main

### 描述 Bug

使用 `\citet` 时，如果是英文后面是 et al.，如何修改为`等`。
![image](https://github.com/whutug/whu-thesis/assets/72788314/4f193aee-2e04-45eb-84c5-1c55a6eda499)
![image](https://github.com/whutug/whu-thesis/assets/72788314/f9265e94-cc7e-4a18-bc09-27e98d67ad05)

**Comment by SwitWu** [comment]
用的是 BibTeX 吗

**Comment by SwitWu** [comment]
是的话在 bib 文件中加 `langid = {chinese}`

**Comment by chenkang455** [comment]
我直接用的overleaf，解决了，thx！

**Comment by chenkang455** [comment]
抱歉再打扰一下，这样好像会导致参考文献的etal变成等？是不是无法做到citet{}上显示英文，但参考文献是等

**Comment by SwitWu** [comment]
请描述清楚你的问题。
