### ISSUE TITLE
Release v1.0在在线Latex编辑器（TeXPage）中编译报错

### ISSUE THREAD

**Issue by zhengxiongli08** [whutug/whu-thesis#270]
### 检查清单

- [X] 我已在 issues 中进行搜索（包括已关闭的问题）

### 论文类型

本科毕业论文

### 学位类型

学术学位

### 操作系统

TeXPage

### TeX 发行版

TeX Live 2023

### 您使用的模版来源

Release v1.0

### 描述 Bug

因为在Overleaf中会编译超时，所以没有用Overleaf，而是采用了[TeXPage](https://www.texpage.com/console)。

我在TexPage中上传了Release v1.0的压缩包，把`\documentclass[type = doctor]{whu-thesis}`注释掉，并更换为本科的`\documentclass[type = bachelor]{whu-thesis}`，然后把`cjk-font = mac,`更换为`cjk-font = fandol,`。虽然能编译出一个PDF文件，但是有许多报错（见下图），并且PDF文件的排版也有问题，比如首页是一些奇怪的字符，并且封面页整体内容有点靠上。

![image](https://github.com/whutug/whu-thesis/assets/106097290/8662ea11-ee16-4709-8755-def86cf385b4)

编译出的PDF文件见，
[whuthesis.pdf](https://github.com/whutug/whu-thesis/files/15130879/whuthesis.pdf)

编译生成的.log文件见，
[output.log](https://github.com/whutug/whu-thesis/files/15130883/output.log)

我之前使用的是在rebuild分支合并到main之前的main版本，并没有出现上述问题。希望提供一些解决办法，使Release中的模板在这类在线编辑器上可用。

**Comment by SwitWu** [comment]
问题在于 LaTeX3 内核新增了 `\tl_if_eq:VnTF`，而 TeXPage 使用的发行版没有更新至最新版。

## 解决方案

在 `whu-thesis.cls` 里面（104 行，函数变体那里）加一句
```tex
\cs_generate_variant:Nn \tl_if_eq:nnTF { V }
```

**Comment by zhengxiongli08** [comment]
> 问题在于 LaTeX3 内核新增了 `\tl_if_eq:VnTF`，而 TeXPage 使用的发行版没有更新至最新版。
> 
> ## 解决方案
> 在 `whu-thesis.cls` 里面（104 行，函数变体那里）加一句
> 
> ```
> \cs_generate_variant:Nn \tl_if_eq:nnTF { V }
> ```

感谢，此问题已解决。但还有一些问题，

Release版本的封面页整体有些靠上，和官方参考模板有明显差距。两者的对比如下图所示，左侧为官方模板，右侧为Latex模板，
![图片1](https://github.com/whutug/whu-thesis/assets/106097290/c2d6d510-a8ac-4d95-8d0e-0a310ff957c7)

此外，在模板编译出的PDF文件中，超链接处（如目录，引用）会出现红框或绿框，我知道这是href的问题，但我不知道应该修改哪里，具体情况见下图，
![image](https://github.com/whutug/whu-thesis/assets/106097290/81392f24-6ec4-469d-b695-d3224926dfd4)
![image](https://github.com/whutug/whu-thesis/assets/106097290/e884f047-6ada-4d1d-a66f-31c82d306134)

希望得到帮助，感谢。

**Comment by SwitWu** [comment]
> Release版本的封面页整体有些靠上，和官方参考模板有明显差距。

感谢反馈，这个我得再确认一下

> 此外，在模板编译出的PDF文件中，超链接处（如目录，引用）会出现红框或绿框，我知道这是href的问题，但我不知道应该修改哪里，具体情况见下图

这些框最终不影响打印的。你是想要在 PDF 里去掉它们吗？

**Comment by SwitWu** [comment]
> Release版本的封面页整体有些靠上，和官方参考模板有明显差距。

这个原因找到了，已修复，请使用最新 Releases v1.0.1

> 是的，我希望去掉这个框。

在导言区声明 `\hypersetup{hidelinks}` 即可

**Comment by zhengxiongli08** [comment]
> > Release版本的封面页整体有些靠上，和官方参考模板有明显差距。
> 
> 已修复，请使用最新 Releases v1.0.1
> 
> > 是的，我希望去掉这个框。
> 
> 在导言区声明 `\hypersetup{hidelinks}` 即可

感谢，在Release v1.0.1中，问题已解决。
