### ISSUE TITLE
siunitx包缺失

### ISSUE THREAD

**Issue by zhengxiongli08** [whutug/whu-thesis#271]
### 检查清单

- [X] 我已在 issues 中进行搜索（包括已关闭的问题）

### 论文类型

本科毕业论文

### 学位类型

学术学位

### 操作系统

TeXPage

### TeX 发行版

TeX Live 2023

### 您使用的模版来源

Release v1.0.1

### 描述 Bug

在rebuild分支合并前的main分支中，是有siunitx包的。而在Release v1.0.1中，该包似乎不再默认包含。

可以在[此处](https://github.com/whutug/whu-thesis/blob/18a34be2799d484e2108e25c9ec296fd378d3a61/whu-thesis.cls#L436)添加以解决问题。

**Comment by SwitWu** [comment]
由于数院基本用不上这个包，所以写 cls 的时候没加进去，你在 demo 里面调用吧

**Comment by zhengxiongli08** [comment]
subfigure也没有了，我尝试着加了一下，但是不能正常工作。siunitx我已经自己加上了，这个子图功能能加回去吗？

**Comment by SwitWu** [comment]
> subfigure也没有了，我尝试着加了一下，但是不能正常工作

我建议用 `subcaption` 宏包，这个比 `subfigure` 新

**Comment by xkwxdyy** [comment]
目前模板的架构下，包调用就是需要 minimal，否则可能会有不必要的冲突和编译变慢。
