### ISSUE TITLE
如何页眉设置除封面外都存在

### ISSUE THREAD

**Issue by MarkosLEE** [whutug/whu-thesis#272]
### 检查清单

- [X] 我已在 issues 中进行搜索（包括已关闭的问题）

### 论文类型

本科毕业论文

### 学位类型

学术学位

### 操作系统

Windows

### TeX 发行版

1

### 您使用的模版来源

1

### 您遇到了什么问题？

学院要求页眉设置除封面外都存在，请问如何设置呀

**Comment by SwitWu** [comment]
1. 什么院系？
2. 页眉具体设置是什么样的？有没有官方文件？
3. 请规范提问

**Comment by MarkosLEE** [comment]
> 1. 什么院系？
> 2. 页眉具体设置是什么样的？有没有官方文件？
> 3. 请规范提问

1.网安院
2.有官方文件。页眉格式方面有两处不同的地方，我已经解决了一处，目前还剩如issue所说的问题，即如何设置除封面外都存在页眉（当前格式为，目录（不含）后的页才有页眉）
3.不好意思，辛苦了

**Comment by SwitWu** [comment]
> 有官方文件。

提供一下

**Comment by xkwxdyy** [comment]
@MarkosLEE 先等文件上传完再 comment，你的文件没成功上传。

**Comment by SwitWu** [comment]
@MarkosLEE 更新了，试试效果
