### ISSUE TITLE
字体缺失

### ISSUE THREAD

**Issue by forthemoon2026** [whutug/whu-thesis#273]
### 检查清单

- [X] 我已在 issues 中进行搜索（包括已关闭的问题）

### 论文类型

硕士学位论文

### 学位类型

学术学位

### 操作系统

win

### TeX 发行版

texlive2023

### 您使用的模版来源

main

### 您遇到了什么问题？

Package fontspec Error: The font "Songti SC Light" cannot be found.   Package fontspec Error: The font "Songti SC Bold" cannot be found. 请问遇到这种字体缺失 应该如何处理

**Comment by SwitWu** [comment]
看手册字体设置

**Comment by zhengxiongli08** [comment]
[这个地方](https://github.com/whutug/whu-thesis/blob/18a34be2799d484e2108e25c9ec296fd378d3a61/demo.tex#L35)改成windows试试
