### ISSUE TITLE
文献文中引用和参考文献顺序排列问题

### ISSUE THREAD

**Issue by alicia2739** [whutug/whu-thesis#274]
### 检查清单

- [X] 我已在 issues 中进行搜索（包括已关闭的问题）

### 论文类型

本科毕业论文

### 学位类型

学术学位

### 所在院系

经济与管理学院

### 操作系统

Overleaf

### TeX 发行版

Overleaf

### 您使用的模版来源

主页下载

### 您遇到了什么问题？

我希望在文中引用文献的时候使用，作者（年份）或者（作者年份的形式），所以我设置了bib-style为author-year-numberd，但是我发现这样参考文献就变成了：作者，年份，标题，出版刊物...的顺序，但是本科生给的要求是作者，标题，出版刊物，年份……的形式，请问应该怎么解决呢

**Comment by SwitWu** [comment]
最新模版并没有提供键值 `bib-style = author-year-numbered`

**Comment by SwitWu** [comment]
这个不是最新版

**Comment by alicia2739** [comment]
<img width="721" alt="image" src="https://github.com/whutug/whu-thesis/assets/141000245/b3021574-6973-4ba4-b3f5-8f000bb2d04e">
啊，但是我看最新一次更新是19hours前？

**Comment by alicia2739** [comment]
<img width="717" alt="image" src="https://github.com/whutug/whu-thesis/assets/141000245/caf06ac8-224a-4c0b-b15e-856810721c99">
这个最新一次更新不是在15hours之前吗？

**Comment by SwitWu** [comment]
搞半天，原来你用的是别人的仓库而不是本仓库。

**Comment by xkwxdyy** [comment]
> 搞半天，原来你用的是别人的仓库而不是本仓库。

6

**Comment by SwitWu** [comment]
@alicia2739 你要明白，任何从本仓库 folk 出去的库（包括你用的 https://github.com/cylqqqcyl/whu-thesis-2024）都与本仓库无关了，既然你用的是别的仓库，就在那里提 Issue。换言之，若你想在这里寻求帮助，就必须用本仓库提供的模版。

**Comment by alicia2739** [comment]
啊啊，不好意思，因为那个仓库下面issue的链接也到这里了，我也是才发现

**Comment by alicia2739** [comment]
已经解决了感谢各位大佬
