### ISSUE TITLE
关键词

### ISSUE THREAD

**Issue by alicia2739** [whutug/whu-thesis#275]
### 检查清单

- [X] 我已在 issues 中进行搜索（包括已关闭的问题）

### 论文类型

本科毕业论文

### 学位类型

学术学位

### 所在院系

经济与管理学院

### 操作系统

Overleaf

### TeX 发行版

Overleaf

### 您使用的模版来源

main分支

### 描述 Bug

本科论文模板要求摘要正文和关键词之间是挨着的，但是模板是空了一行好像，并且关键词换行要求顶格，模板的关键词换行之后第二行不会顶格，而是从上一行对应的keywords：后面开始，请问这个如何解决？

**Comment by SwitWu** [comment]
本模版提供了接口：
<img width="739" alt="image" src="https://github.com/whutug/whu-thesis/assets/39337667/64965795-f472-4d3e-9393-848bd2a12edd">

**Comment by alicia2739** [comment]
感谢
