### ISSUE TITLE
标题的英数字体好像不对

### ISSUE THREAD

**Issue by Stabilizer1071** [whutug/whu-thesis#278]
### 检查清单

- [X] 我已在 issues 中进行搜索（包括已关闭的问题）

### 论文类型

本科毕业论文

### 学位类型

学术学位

### 所在院系

电信

### 操作系统

Windows 11

### TeX 发行版

MiKTeX

### 您使用的模版来源

main分支

### 描述 Bug

RT，在设置 cjk-font = windows 时，标题的英数字体好像依然在使用 FandolHei
![image](https://github.com/whutug/whu-thesis/assets/72261964/7141eb43-90c6-4588-b33b-02b1762e11d6)

**Comment by SwitWu** [comment]
> 标题的英数字体好像依然在使用 FandolHei

这不是 FandolHei，而是 Latin Modern Sans

最新本科规定：

+ 目录中章节序号（Time New Roman 小四号）
+ 目录中章的标题（黑体四号）

只要求用黑体，所以没有将标题中的西文和阿拉伯数字改为 times 风格字体

**Comment by Stabilizer1071** [comment]
> > 标题的英数字体好像依然在使用 FandolHei
> 
> 这不是 FandolHei，而是 Latin Modern Sans
> 
> 最新本科规定：章节标题用黑体
> 
> 所以没有将标题中的西文和阿拉伯数字改为 times 风格字体

如果希望用 Times New Roman 的话应该怎么做呢

**Comment by SwitWu** [comment]
https://github.com/whutug/whu-thesis/blob/4b17a7d86f1efe5dd30d0ab28bb7f677d1984759/whu-thesis.cls#L843
https://github.com/whutug/whu-thesis/blob/4b17a7d86f1efe5dd30d0ab28bb7f677d1984759/whu-thesis.cls#L854
https://github.com/whutug/whu-thesis/blob/4b17a7d86f1efe5dd30d0ab28bb7f677d1984759/whu-thesis.cls#L862
https://github.com/whutug/whu-thesis/blob/4b17a7d86f1efe5dd30d0ab28bb7f677d1984759/whu-thesis.cls#L870

最简单的方式就是把这四处的 `\sffamily` 改为 `\heiti`。

**Comment by Stabilizer1071** [comment]
> https://github.com/whutug/whu-thesis/blob/4b17a7d86f1efe5dd30d0ab28bb7f677d1984759/whu-thesis.cls#L843
> 
> 
> https://github.com/whutug/whu-thesis/blob/4b17a7d86f1efe5dd30d0ab28bb7f677d1984759/whu-thesis.cls#L854
> 
> 
> https://github.com/whutug/whu-thesis/blob/4b17a7d86f1efe5dd30d0ab28bb7f677d1984759/whu-thesis.cls#L862
> 
> 
> https://github.com/whutug/whu-thesis/blob/4b17a7d86f1efe5dd30d0ab28bb7f677d1984759/whu-thesis.cls#L870
> 
> 最简单的方式就是把这四处的 `\sffamily` 改为 `\heiti`。

了解了，感谢🙏
