### ISSUE TITLE
标题中文字符编译出错

### ISSUE THREAD

**Issue by sspicyorange** [whutug/whu-thesis#280]
### 检查清单

- [X] 我已在 issues 中进行搜索（包括已关闭的问题）

### 论文类型

本科毕业论文

### 学位类型

学术学位

### 所在院系

网安

### 操作系统

Overleaf

### TeX 发行版

Tex Live version 2023

### 您使用的模版来源

main分支

### 描述 Bug

标题中输入“仓”，编译后显示“仑”

**Comment by SwitWu** [comment]
`cjk-font` 选择的是什么？

**Comment by SwitWu** [comment]
嗯，`cjk-font = fandol` 缺失复现了。

**Comment by SwitWu** [comment]
```tex
\documentclass[fontset=fandol]{ctexart}
\begin{document}
\kaishu 仓仑
\end{document}
```
<img width="358" alt="image" src="https://github.com/whutug/whu-thesis/assets/39337667/06121d61-be43-468e-bf40-c81384ce4117">

**Comment by SwitWu** [comment]
@sspicyorange 应该是字体原因，你换个字体吧
