### ISSUE TITLE
mac 提示字体缺失

### ISSUE THREAD

**Issue by WHUxzf** [whutug/whu-thesis#287]
### 检查清单

- [X] 我已在 issues 中进行搜索（包括已关闭的问题）

### 论文类型

硕士学位论文

### 学位类型

专业学位

### 所在院系

电信

### 操作系统

macOS 14.3

### TeX 发行版

TeX Live 2023

### 您使用的模版来源

main v2.1.0

### 您遇到了什么问题？

使用 XeLaTeX 编译报错, 按理说 mac 上应该有这些字体？但是不能编译成功
### demo.tex中的设置
```tex
style = {
    font = times,
    math-font = termes,
    cjk-font = mac,
    bib-backend = bibtex,
    bib-resource = {ref/bachelor-refs.bib}
  }
```
### 报错信息：
```
Package fontspec Error: The font "Songti SC Light" cannot be found.
‪./demo.tex, 44‬                                
Package fontspec Error: The font "Songti SC Bold" cannot be found.
Package fontspec Error: The font "Kaiti SC Regular" cannot be found.
Package fontspec Error: The font "STFangsong" cannot be found. 
```

**Comment by SwitWu** [comment]
去字体册看看有没有

+ 宋体-简
+ 楷体-简

**Comment by WHUxzf** [comment]
> 去字体册看看有没有
> 
> * 宋体-简
> * 楷体-简

宋体-简的文件路径为：/System/Library/Fonts/Supplemental/Songti.ttc

<img width="793" alt="iShot_2024-05-21_20 10 38" src="https://github.com/whutug/whu-thesis/assets/59534063/61c2bcea-9ea6-4c6d-8806-e3ccbe0f2923">

并没有看到Songti SC Light 可能应该使用 STKSongti-xxxx?

<img width="640" alt="iShot_2024-05-21_20 16 13" src="https://github.com/whutug/whu-thesis/assets/59534063/9d0d455d-9695-43bd-8902-eab608e26524">

**Comment by WHUxzf** [comment]
另外，将style中的 cjk-font =  windows，下载安装simsun.ttc、simheittf 并将这俩文件放在overleaf根目录也会报错缺少这两个字体。人麻了
设置 cjk-font =fandol 在两个系统上都能通过编译。

**Comment by zhengxiongli08** [comment]
> 另外，将style中的 cjk-font = windows，下载安装simsun.ttc、simheittf 并将这俩文件放在overleaf根目录也会报错缺少这两个字体。人麻了 设置 cjk-font =fandol 在两个系统上都能通过编译。

Fandol是Texlive自带的吧，所以跨系统没问题

**Comment by SwitWu** [comment]
@WHUxzf 你写一个最小测试代码试一下

**Comment by SwitWu** [comment]
@WHUxzf 在你的 mac 上用 `xelatex` 编译：
```tex
\documentclass{ctexart}
\setCJKmainfont{Songti SC Light}
\begin{document}
你好
\end{document}

**Comment by WHUxzf** [comment]
> @WHUxzf 在你的 mac 上用 `xelatex` 编译：
> 
> ```
> \documentclass{ctexart}
> \setCJKmainfont{Songti SC Light}
> \begin{document}
> 你好
> \end{document}
> ```

<img width="1157" alt="iShot_2024-05-21_23 57 40" src="https://github.com/whutug/whu-thesis/assets/59534063/20457b6a-6ab6-46f4-b79c-43006e5b72f4">

**Comment by zhengxiongli08** [comment]
> > @WHUxzf 在你的 mac 上用 `xelatex` 编译：
> > ```
> > \documentclass{ctexart}
> > \setCJKmainfont{Songti SC Light}
> > \begin{document}
> > 你好
> > \end{document}
> > ```
> 
> <img alt="iShot_2024-05-21_23 57 40" width="1157" src="https://private-user-images.githubusercontent.com/59534063/332496163-20457b6a-6ab6-46f4-b79c-43006e5b72f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzMDc1ODEsIm5iZiI6MTcxNjMwNzI4MSwicGF0aCI6Ii81OTUzNDA2My8zMzI0OTYxNjMtMjA0NTdiNmEtNmFiNi00NmY0LWI3OWMtNDMwMDZlNWI3MmY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDE2MDEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzMDk4OWFhNTQxMTYzMGVkNjY1NzE3YzBlNDUwZmFiYTZhZjhmOWYxY2ZkMGExYmU0YWE2ZTMzZTkwYzQ3NTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IltKeafTSfTeKiSVGoetYhSVKKv4sem37zCBeLNY3B0">

这怎么看着像Overleaf啊？不是mac吗？

**Comment by SwitWu** [comment]
@WHUxzf 在提问前，请你先仔细看看提问模版，操作系统那一项你应该写 Overleaf 啊，你写的是 macOS，我还以为你在本地编译。

Overleaf 的服务器用的是 ubuntu，所以设置 `cjk-font=mac` 或者 `cjk-font=windows` 都不行，`cjk-font=fandol` 可以。

**Comment by SwitWu** [comment]
如果你非要用 `cjk-font=mac` 的话，那你需要把

+ 宋体-简
+ 楷体-简
+ 黑体-简
+ STFangsong

上传到 Overleaf 的项目文件夹里面去。

**Comment by SwitWu** [comment]
我明天测试一下，电脑不在身旁

**Comment by SwitWu** [comment]
[whuthesis.pdf](https://github.com/whutug/whu-thesis/files/15397675/whuthesis.pdf)

@WHUxzf 按第八页的说明进行操作。

**Comment by SwitWu** [comment]
@WHUxzf 按照手册里的步骤操作还有没有问题，反馈一下。

**Comment by WHUxzf** [comment]
可以通过编译，之前的手册好像缺少你发的这个自定义字体的说明部分。

**Comment by SwitWu** [comment]
这部分是我补充的

**Comment by WHUxzf** [comment]
根据这部分在overleaf上使用自定义字体没啥问题。之前字体编译问题困扰几天了/(ㄒoㄒ)/~~非常感谢解答。

**Comment by cooper12121** [comment]
> [@WHUxzf](https://github.com/WHUxzf) 按照手册里的步骤操作还有没有问题，反馈一下。



> [@WHUxzf](https://github.com/WHUxzf) 按照手册里的步骤操作还有没有问题，反馈一下。

求问，mac 在overlear上传自定义字体如SongTi SC文件大小超过50MB无法上传，有什么解决办法吗

**Comment by SwitWu** [comment]
> 求问，mac 在 Overleaf 上传自定义字体如 SongTi SC 文件大小超过50MB无法上传，有什么解决办法吗

mac 干嘛不下载 MacTeX 呢，比 Overleaf 好用多了
