### ISSUE TITLE
缩略语对照表

### ISSUE THREAD

**Issue by suwenyinwuyan** [whutug/whu-thesis#289]
### 检查清单

- [X] 我已在 issues 中进行搜索（包括已关闭的问题）

### 论文类型

硕士学位论文

### 学位类型

学术学位

### 所在院系

电信院

### 操作系统

 Overleaf

### TeX 发行版

 Overleaf自带

### 您使用的模版来源

 Overleaf中的武大论文模板

### 您遇到了什么问题？

老师希望在目录后面绪论前面增加一页缩略语对照表，但我不知道应该怎么添加，可以请您提供相关的代码吗，缩略语对照表那一页需要是罗马字母，并且可以在目录中显示。麻烦您了

**Comment by SwitWu** [comment]
1. Overleaf 中的武大论文模版是指哪个？最新的模版并没有上传至 Overleaf
2. 新模版提供了 notation 环境，你看看可不可以。

**Comment by suwenyinwuyan** [comment]
就是我不知道怎么添加这一页，缩略语对照表那一页需要是罗马字母，并且可以在目录中显示。能不能请您帮忙看看（我之前用了这个模板，但参考文献一直没有标号，我就换成了overleaf比较早的那版）

**Comment by SwitWu** [comment]
请用最新版，旧版已经不维护了

**Comment by suwenyinwuyan** [comment]
我已经换成了这一版

**Comment by SwitWu** [comment]
### 新版效果

符号表
<img width="954" alt="image" src="https://github.com/whutug/whu-thesis/assets/39337667/731f5444-fa25-497d-968a-c4a2c6a1b202">
目录
<img width="1015" alt="image" src="https://github.com/whutug/whu-thesis/assets/39337667/f90f125f-f2ba-434b-81e6-f09f6646ee16">

**Comment by SwitWu** [comment]
可以给 notation 环境添加可选参数修改标题内容，例如：

```tex
\begin{notation}[缩略语对照表]
  $\omega_n$ & $n$-维欧氏空间中单位球的表面积 \\
  $\alpha_n$ & $n$-维欧氏空间中单位球的体积 \\
\end{notation}
```

效果：

<img width="776" alt="image" src="https://github.com/whutug/whu-thesis/assets/39337667/2b7cc286-caed-42cc-8519-cf6cf50d4c7c">

**Comment by SwitWu** [comment]
@suwenyinwuyan 这个效果可以吗？如果不行的话我可以再修改定制。

**Comment by suwenyinwuyan** [comment]
我在尝试

**Comment by suwenyinwuyan** [comment]
好像只能两列，不能三列

**Comment by SwitWu** [comment]
可以三列，如
```tex
\begin{notation}[缩略语对照表][lll]
  $\omega_n$ & alpha & $n$-维欧氏空间中单位球的表面积 \\
  $\alpha_n$ & beta & $n$-维欧氏空间中单位球的体积 \\
\end{notation}
```
其中第二个可选参数 `lll` 为列格式说明，关于怎么使用列格式，去看看 lshort-zh-cn。

效果：

<img width="796" alt="image" src="https://github.com/whutug/whu-thesis/assets/39337667/515bfe7e-ba2e-4971-b11b-5234aabf2edc">
