### ISSUE TITLE
docstrip 化与 LaTeX3 化

### ISSUE THREAD

**Issue by tanukihee** [whutug/whu-thesis#29]
如题，应该是个大工程，特别是后者……

**Comment by mtobeiyf** [comment]
Are they necessary? Seems LaTeX3 is still under development.

**Comment by tanukihee** [comment]
当个远期目标吧……docstrip 也许可以更优先一些

**Comment by tanukihee** [comment]
LaTeX3 化基本完成了，基本的接口也已给出。但 docstrip 估计遥遥无期……😂

**Comment by zepinglee** [comment]
我更建议去 `docstrip` 化，主要是因为代码更适合在编辑器里阅读而不是在 PDF 阅读器里读。

**Comment by tanukihee** [comment]
> 我更建议去 `docstrip` 化

CTAN 支持上传单个的 cls 吗？用 dtx 主要是为了将来上传 CTAN 着想…

**Comment by zepinglee** [comment]
> > 我更建议去 `docstrip` 化
> 
> CTAN 支持上传单个的 cls 吗？用 dtx 主要是为了将来上传 CTAN 着想…

当然支持，比如 biblatex。

另外我个人建议学位论文没必要传到 ctan 上。

**Comment by tanukihee** [comment]
好的，那就无限期搁置吧😂
