### ISSUE TITLE
硕士和博士论文每个章节标题所在页的页眉没有正确显示

### ISSUE THREAD

**Issue by cynthia-1999** [whutug/whu-thesis#291]
### 检查清单

- [X] 我已在 issues 中进行搜索（包括已关闭的问题）

### 论文类型

硕士学位论文

### 学位类型

学术学位

### 所在院系

网安

### 操作系统

macos

### TeX 发行版

TeX Live 2024

### 您使用的模版来源

main分支

### 描述 Bug

whu-thesos.cls文件中定义的\cs_new_protected:Npn \__whu_master_set_ctex_format:chapter样式缺少pagestyle    = master-mainmatter，以及\cs_new_protected:Npn \__whu_master_set_enumerate_format:chapter样式缺少pagestyle    = doctor-mainmatter, 导致每个章节首页的页眉不显示。

**Comment by SwitWu** [comment]
看手册，网安有特殊处理

**Comment by SwitWu** [comment]
请提供一份网安院硕博最新的论文书写印制规范

**Comment by cynthia-1999** [comment]
你好，我没有在手册里面搜到关于网安的特殊处理内容，你可以提供给我吗？



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年6月13日(星期四) 上午7:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [whutug/whu-thesis] 硕士和博士论文每个章节标题所在页的页眉没有正确显示 (Issue #291)














 
看手册，网安有特殊处理

**Comment by cynthia-1999** [comment]
网安学院没有官方的硕博论文书写印制规范，只有一份计算机学院的，里面没有说明关于页眉的，但是我在使用这份whu-thesis进行硕士论文撰写时发现了关于章节首页页眉不显示的问题，并通过添加pagestyle = master-mainmatter解决了这个问题。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "whutug/whu-thesis"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月13日(星期四) 中午11:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [whutug/whu-thesis] 硕士和博士论文每个章节标题所在页的页眉没有正确显示 (Issue #291)





 
请提供一份网安院硕博最新的论文书写印制规范

**Comment by cynthia-1999** [comment]
这个问题不是一个bug，是一个需要确认的规范，我之前的论文交上去被教学办的老师指出每章的第一页没有页眉的问题，他给出的原因是其他同学每章的第一页都有页眉，其他同学用word模版书写的确实都有页眉。我无法确定有页眉是不是正确的规范。

**Comment by SwitWu** [comment]
> 其他同学用word模版书写的确实都有页眉

提供一下这个 word 模版

**Comment by Chnja** [comment]
@SwitWu 是否可以考虑在whusetup.style里增加一个章节首页是否有页眉的设置？

**Comment by SwitWu** [comment]
2584c562826e618be8639c05542c2ccc4eb5eae9
