### ISSUE TITLE
如何设置\mathcal显示的字体为传统格式，而非花体？

### ISSUE THREAD

**Issue by dmybrown** [whutug/whu-thesis#292]
### 检查清单

- [X] 我已在 issues 中进行搜索（包括已关闭的问题）

### 论文类型

博士学位论文

### 学位类型

学术学位

### 所在院系

计算机

### 操作系统

Overleaf

### TeX 发行版

tex live 2023

### 您使用的模版来源

main 2024-03-27

### 描述 Bug

`\mathcal`和`\mathscr`生成的都是花体
![1718377575012](https://github.com/whutug/whu-thesis/assets/68623386/78aefc3b-a6dc-44e3-a4a6-b981ad50240f)
如何生成这种论文里正常的mathcal字体？
![1718377609678](https://github.com/whutug/whu-thesis/assets/68623386/0f2e4b21-c2d8-40c9-b32c-9a4137ed54e2)

试了其他`issues`中的方法，均无法完美解决。
+ #125 这里面说`0.6`版本已经修复了， 现在的版本是又回退回去了吗。不太可能仅仅因为这个问题用回到两年前的版本。
+ #232 这个第四点倒是可以生效，但是报错很多非法命令，好像下面第三行的命令行不合法。而且显示出来的L和G也不是常规的`mathcal`的`L`和`G`。上面是这里显示的，下面是之前用过的。
![1718378952476(1)](https://github.com/whutug/whu-thesis/assets/68623386/a530c288-6fbf-4154-896a-759b0b7e6ff5)
![1718379467710](https://github.com/whutug/whu-thesis/assets/68623386/bdb92a39-4d40-4a37-930d-836c47f50451)

第四点：首先先把Windows中的Cambria Math的字体文件放在项目目录中，然后修改cls文件中的数学字体设置，往其中的可选项中添加cambria.ttc:
```
math-font .choices:nn =
      { xits , termes , cambria.ttc, none }
      { \__whu_math_fontset:n { \l_keys_choice_tl } },
    % 数学字体
```
+ #120 这里面讲了很多，但是没说简单可操作的解决方法

多方尝试无果，遂来求助，能否让`mathcal` 不要显示花体。

而且我看`demo.pdf`中的`mathcal`和`mathscr`显示的也是一模一样，这个可否在正式发行版里解决掉，让`demo.pdf`中显示正常的`\mathcal`。

**Comment by SwitWu** [comment]
用 `math-font = xits`

**Comment by SwitWu** [comment]
如果你非要用「常规」的 `\mathcal{L}` 和 `\mathcal{G}`，那就用 `math-font = default`，此时用的数学字体就是经典的 Computer Modern 字体，但是正文西文字体也需要改为 `font = default`，只有这样才能看起来比较协调。

**Comment by dmybrown** [comment]
> 如果你非要用「常规」的 `\mathcal{L}` 和 `\mathcal{G}`，那就用 `math-font = default`，此时用的数学字体就是经典的 Computer Modern 字体，但是正文西文字体也需要改为 `font = default`，只有这样才能看起来比较协调。

非常@SwitWu 的解答！字体终于看起来舒服了。
小小总结一下，避免后面同学踩坑。如果你是`cls`小白，习惯于AI领域会议论文（不了解其他领域习惯）的符号体系，并且使用Overleaf为主力，可以看一下
+ 首先，尽量用最新发行版。e.g., v2.2.0。有时候更新一下版本问题就没有了。
+ 不要试图动`cls`文件里的`math-font`设置， #125 #232 里面的设置**统统都过时**了，更不要试图采用什么上传`cambria.ttc`等骚操作，越改只会越乱。加之本人不熟悉`cls`语法，链接到什么`THU`，`XJTU`的`Issues`，问`ChatGPT`，耗费一天多，踩坑无数。
+ 直接改`demo.tex`里面的`math-font`为`default`即可。`xits`的显示也很奇怪，不推荐。这样的话`math`符号就是所谓的“经典的 Computer Modern 字体”，经典的就是最好的！正文西文可以根据上面建议改为`font=default`，这个`default`比`times`和`termes`宽一点。不过我个人不改感觉也没关系，之前投稿目测都是数学符号`Computer Modern`，正文`Times`。先这样，如果后面有问题再改为default。
