### ISSUE TITLE
章节标题编号怎么修改哦？

### ISSUE THREAD

**Issue by jacksparrow-firstmate** [whutug/whu-thesis#296]
### 检查清单

- [X] 我已在 issues 中进行搜索（包括已关闭的问题）

### 论文类型

博士学位论文

### 学位类型

专业学位

### 所在院系

计算机院

### 操作系统

windows

### TeX 发行版

Tex Live 2024

### 您使用的模版来源

main分支

### 您遇到了什么问题？

标题序号怎么改啊？请问，现在的标题为1，2，3开头，在哪可以改为第一章，第二章.....这样的？cls文件找了一下，没找到

**Comment by SwitWu** [comment]
直接在导言区使用 ctex 宏包提供的接口：

```tex
\ctexset{
  chapter = {
    name = {第,章},
    number = \chinese{chapter},
    format += \centering,
  }
}
```

**Comment by jacksparrow-firstmate** [comment]
\ctexset
      {
        chapter        =
          {
            format     = { \centering \heiti \zihao { -2 } },
            % number     = { \arabic { chapter }             },
            number     = { \chinese {chapter}             },
            name       = { 第,章                               },
            beforeskip = { 0.8 \c__whu_baseline_skip       },
            afterskip  = { 0.5 \c__whu_baseline_skip       },
          }  % 各章标题 黑体小 2 号
      }
刚解决了，非常感谢，早点休息哦亲

**Comment by GoForLunch** [comment]
为什么我mac系统设置\heiti和原来的宋体效果一样呢😂

**Comment by GoForLunch** [comment]
我是mac系统，为什么设置\heiti和原来的宋体效果一样呢😂

**Comment by SwitWu** [comment]
> 我是mac系统，为什么设置\heiti和原来的宋体效果一样呢😂

`cjk-font` 用的是什么
