### ISSUE TITLE
添加博士与硕士论文支持

### ISSUE THREAD

**Issue by tanukihee** [whutug/whu-thesis#33]
我找到了博士与硕士论文的印制规范了
https://info.whu.edu.cn/info/2056/151891.htm
https://info.whu.edu.cn/info/2056/151893.htm

准备加进 whu-thesis 中，但似乎他们的参考文献规范与本科不太一样……

**Comment by mtobeiyf** [comment]
这个应该没关系，可以魔改引用的style

**Comment by tanukihee** [comment]
> 这个应该没关系，可以魔改引用的style

就是因为不太会所以才加help-wanted😂

**Comment by tanukihee** [comment]
bibtex 上，gbt7714 有 2005 的支持，biblatex 上，虽然没有，但似乎差别不大

见 https://github.com/hushidong/biblatex-gb7714-2015/issues/85 与 https://github.com/TheNetAdmin/zjuthesis/issues/23
