### ISSUE TITLE
运行WHU-thesis-demo时，在没有任何修改的情况下，编译错误

### ISSUE THREAD

**Issue by YLW730** [whutug/whu-thesis#37]
win10，sublime text3+latextools+Texlive2020。
没有任何修改，下载了zip后就用Xelatex编译了WHU-thesis-demo，但出现以下问题：
Errors:

D:\whu-thesis-master\whu-thesis.cls:103: Undefined control sequence. [\tl_if_eq:NnT]
D:\whu-thesis-master\whu-thesis.cls:103: LaTeX Error: Missing \begin{document}. [\tl_if_eq:NnT \g__whu_option_type_tl]
D:\whu-thesis-master\whu-thesis.cls:110: Undefined control sequence. [\tl_if_eq:NnT]
D:\whu-thesis-master\whu-thesis.cls:141: Undefined control sequence. [\tl_if_eq:NnTF]
D:\whu-thesis-master\whu-thesis.cls:141: LaTeX Error: Missing \begin{document}. [\tl_if_eq:NnTF \g__whu_option_type_tl]
d:\Program Files\texlive\2020\texmf-dist\tex\xelatex\xecjk\xeCJK.sty:656: TeX capacity exceeded, sorry [save size=80000]. [\xeCJKResetCharClass]

请问是什么原因？该如何解决呢？

**Comment by tanukihee** [comment]
使用 `tlmgr update --self --all` 更新所有宏包

**Comment by tanukihee** [comment]
详见 #35
