### ISSUE TITLE
Mac 楷体报错

### ISSUE THREAD

**Issue by Chuhan1112** [whutug/whu-thesis#39]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [ ] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [x] macOS
  - [ ] Linux（请附发行版）

- TeX 发行版
  - [x] TeX Live 
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 描述问题

本地编译，楷体报错 出现报错 “Can't find the font 'Kaiti'”
## 最小工作示例（MWE）

```latex
\documentclass{whu-thesis}
\begin{document}
Hello, \LaTex!
\end{document}
```

（用 XeLaTeX 编译后）输出

```latex
! Undefined control sequence.
l.3 Hello, \LaTex
                 !
?
```

## 链接

- TeX.SX:
- GitHub:

## 我还做了这些尝试

将whu-thesis.cls 第565行改为 将 STKaiti ~ SC ~ Regular 改为 STKaiti 问题解决

## 附件

<img width="396" alt="截屏2021-03-06 下午8 24 03" src="https://user-images.githubusercontent.com/35064712/110206643-e753a400-7eb9-11eb-9fa2-08999991c0f5.png">

**Comment by tanukihee** [comment]
我在 532dd8b 里改了改，但我没有 mac 设备，测试是在装了苹果的华文字体的 windows 下进行的……

**Comment by mtobeiyf** [comment]
我今天在Mac下测试也遇到了字体识别的问题 `! Package fontspec Error: The font "STFangsong" cannot be found.`。我的测试环境是 MiKTeX，用 `xelatex` 编译文件。系统 Font Book 中显示有 STFangsong，毕竟是默认的字体嘛，应该是 `miktex-maketfm` 没能找到字体路径。
```
! Package fontspec Error: The font "STFangsong" cannot be found.

For immediate help type H <return>.
 ...                                              
                                                  
l.45 \begin{document}
                     
? 
```

解决方法：
* 从 Font Book 中导出 STFangsong 和 Kaiti SC Regular 字体
* 将导出的 `Kaiti.ttc` 和 `STFANGSO.ttf` 拷贝到 `/Libaray/Fonts/` 目录下
* 重新运行 `xelatex` 命令
