### ISSUE TITLE
在编译出来的pdf里，每一个章节结束的下一页是一页空页，而且有页码

### ISSUE THREAD

**Issue by HenryZhuHR** [whutug/whu-thesis#44]
如题

**Comment by mtobeiyf** [comment]
应该默认是双页打印模式，可以去手册里看一下开启单页打印模式

**Comment by tanukihee** [comment]
这个也算常见问题了，因为是双页打印，所以章节要求右开（在右边，即在奇数页上），空白页就是这么来的。

至于页码，我看各大兄弟院校有留的有不留的，但不留的就是纯空白页了，可能会被当成pdf格式错误，再加上懒，就把页码留着了。

本科单双页打印都可，硕博是必须双页打印的。如果想要单页，可以加 `oneside` 选项。

**Comment by HenryZhuHR** [comment]
是在这里修改吗



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月11日(星期四) 中午11:23
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [whutug/whu-thesis] 在编译出来的pdf里，每一个章节结束的下一页是一页空页，而且有页码 (#44)





 
应该默认是双页打印模式，可以去手册里看一下开启单页打印模式

**Comment by tanukihee** [comment]
> 是在这里修改吗
 

你图没有传上来，不过看文档吧，文档里有介绍

**Comment by HenryZhuHR** [comment]
&nbsp;&nbsp;&nbsp;&nbsp;oneside&nbsp;.value_forbidden:n&nbsp;=&nbsp;true,
&nbsp;&nbsp;&nbsp;&nbsp;twoside&nbsp;.value_forbidden:n&nbsp;=&nbsp;true,
&nbsp;&nbsp;&nbsp;&nbsp;oneside&nbsp;.code:n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\bool_gset_false:N&nbsp;&nbsp;&nbsp;\g__whu_option_twoside_bool
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\clist_gput_right:Nn&nbsp;\g__whu_option_to_class_clist&nbsp;{&nbsp;oneside&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;},
&nbsp;&nbsp;&nbsp;&nbsp;twoside&nbsp;.code:n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\bool_gset_true:N&nbsp;&nbsp;&nbsp;&nbsp;\g__whu_option_twoside_bool
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\clist_gput_right:Nn&nbsp;\g__whu_option_to_class_clist&nbsp;{&nbsp;twoside&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;},
&nbsp;&nbsp;&nbsp;&nbsp;%&nbsp;单双页模式


这里吗？






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月11日(星期四) 中午12:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [whutug/whu-thesis] 在编译出来的pdf里，每一个章节结束的下一页是一页空页，而且有页码 (#44)





  
是在这里修改吗
  
你图没有传上来，不过看文档吧，文档里有介绍

**Comment by tanukihee** [comment]
我建议
1. 不要直接在邮件里回复，而是在网页上回复
2. 文档里给了接口，请阅读文档，不要直接改cls

**Comment by HenryZhuHR** [comment]
> 我建议
> 
> 1. 不要直接在邮件里回复，而是在网页上回复
> 2. 文档里给了接口，请阅读文档，不要直接改cls

\documentclass[type=bachelor,oneside]{whu-thesis}，直接在接口里加 oneside就可以了，谢谢大佬

**Comment by earthmoon** [comment]
> 这个也算常见问题了，因为是双页打印，所以章节要求右开（在右边，即在奇数页上），空白页就是这么来的。
> 
> 至于页码，我看各大兄弟院校有留的有不留的，但不留的就是纯空白页了，可能会被当成pdf格式错误，再加上懒，就把页码留着了。
> 
> 本科单双页打印都可，硕博是必须双页打印的。如果想要单页，可以加 `oneside` 选项。

我想请问下，这个每章右开的规定在哪呢。我似乎没有找到。谢谢。
