### ISSUE TITLE
LaTeX排版的查重问题

### ISSUE THREAD

**Issue by WHU-Tan** [whutug/whu-thesis#45]
在网上看到有反馈说LaTeX生成的PDF查重的时候会出现问题（e.g. 参考文献不能识别、公式可能会乱码），大家之前是否有经验。

**Comment by FrankBlood** [comment]
我的是在mac上用latex生成的pdf，现在在淘宝买的服务上查重，出现因乱码导致的查重失败问题。

**Comment by WHU-Tan** [comment]
我在网上检索之后找到了一个自行判断能否查重的方式：
新建一个.txt文档，将文章中的内容复制进文档中，保存后如果出现乱码则不能查重，反之则可以。
我测试之后发现，中文部分可以完整显示。英文部分由于是UTF-8编码而不是ANSI编码（知网查重是ANSI编码）会乱码。
我的环境是Windows，XeLaTeX编译。

**Comment by FrankBlood** [comment]
我购买的淘宝服务（声称也是知网）说需要把pdf转成txt，如果没有乱码，那可以正常提交pdf查询。
首先，我在mac上测试了Xelatex编译的pdf，将其用sublime打开之后，出现乱码。
然后，我又在mac上测试了新建一个word文档，随便敲点中文进去，保存为pdf。然后将之用sublime打开，仍然显示乱码。
所以我裂开了。

**Comment by sikouhjw** [comment]
> 
> 
> 我购买的淘宝服务（声称也是知网）说需要把pdf转成txt，如果没有乱码，那可以正常提交pdf查询。
> 首先，我在mac上测试了Xelatex编译的pdf，将其用sublime打开之后，出现乱码。
> 然后，我又在mac上测试了新建一个word文档，随便敲点中文进去，保存为pdf。然后将之用sublime打开，仍然显示乱码。
> 所以我裂开了。

并不是「转成」，而是「复制」

**Comment by FrankBlood** [comment]
> > 我购买的淘宝服务（声称也是知网）说需要把pdf转成txt，如果没有乱码，那可以正常提交pdf查询。
> > 首先，我在mac上测试了Xelatex编译的pdf，将其用sublime打开之后，出现乱码。
> > 然后，我又在mac上测试了新建一个word文档，随便敲点中文进去，保存为pdf。然后将之用sublime打开，仍然显示乱码。
> > 所以我裂开了。
> 
> 并不是「转成」，而是「复制」

复制本身没问题的。我所用的淘宝服务说的是“转成”。事实证明都不行。

**Comment by FrankBlood** [comment]
我把latex文件上传到overleaf，然后用overleaf生成pdf。然后把该pdf从mac上传到检测系统。结果通过了。
供参考！

**Comment by sikouhjw** [comment]
> 
> 
> > > 我购买的淘宝服务（声称也是知网）说需要把pdf转成txt，如果没有乱码，那可以正常提交pdf查询。
> > > 首先，我在mac上测试了Xelatex编译的pdf，将其用sublime打开之后，出现乱码。
> > > 然后，我又在mac上测试了新建一个word文档，随便敲点中文进去，保存为pdf。然后将之用sublime打开，仍然显示乱码。
> > > 所以我裂开了。
> > 
> > 
> > 并不是「转成」，而是「复制」
> 
> 复制本身没问题的。我所用的淘宝服务说的是“转成”。事实证明都不行。

淘宝懂个*

**Comment by sikouhjw** [comment]
> 
> 
> 我把latex文件上传到overleaf，然后用overleaf生成pdf。然后把该pdf从mac上传到检测系统。结果通过了。
> 供参考！

提供发行版信息，很可能是发行版的问题

**Comment by FrankBlood** [comment]
> > > > 我购买的淘宝服务（声称也是知网）说需要把pdf转成txt，如果没有乱码，那可以正常提交pdf查询。
> > > > 首先，我在mac上测试了Xelatex编译的pdf，将其用sublime打开之后，出现乱码。
> > > > 然后，我又在mac上测试了新建一个word文档，随便敲点中文进去，保存为pdf。然后将之用sublime打开，仍然显示乱码。
> > > > 所以我裂开了。
> > > 
> > > 
> > > 并不是「转成」，而是「复制」
> > 
> > 
> > 复制本身没问题的。我所用的淘宝服务说的是“转成”。事实证明都不行。
> 
> 淘宝懂个*

哈哈哈哈，暴躁老哥。淘宝开店的应该是不知道怎么获得知网账号的服务老师，所以未必是啥都不懂的。

**Comment by sikouhjw** [comment]
> 
> 
> > 我把latex文件上传到overleaf，然后用overleaf生成pdf。然后把该pdf从mac上传到检测系统。结果通过了。
> > 供参考！
> 
> 提供发行版信息，很可能是发行版的问题

[为什么从生成的pdf复制文本都是乱码且查重无法正确识别文本内容](https://github.com/x-magus/ThesisUESTC/blob/master/README.md#%E4%B8%BA%E4%BB%80%E4%B9%88%E4%BB%8E%E7%94%9F%E6%88%90%E7%9A%84pdf%E5%A4%8D%E5%88%B6%E6%96%87%E6%9C%AC%E9%83%BD%E6%98%AF%E4%B9%B1%E7%A0%81%E4%B8%94%E6%9F%A5%E9%87%8D%E6%97%A0%E6%B3%95%E6%AD%A3%E7%A1%AE%E8%AF%86%E5%88%AB%E6%96%87%E6%9C%AC%E5%86%85%E5%AE%B9)

**Comment by FrankBlood** [comment]
> > > 我把latex文件上传到overleaf，然后用overleaf生成pdf。然后把该pdf从mac上传到检测系统。结果通过了。
> > > 供参考！
> > 
> > 
> > 提供发行版信息，很可能是发行版的问题
> 
> [为什么从生成的pdf复制文本都是乱码且查重无法正确识别文本内容](https://github.com/x-magus/ThesisUESTC/blob/master/README.md#%E4%B8%BA%E4%BB%80%E4%B9%88%E4%BB%8E%E7%94%9F%E6%88%90%E7%9A%84pdf%E5%A4%8D%E5%88%B6%E6%96%87%E6%9C%AC%E9%83%BD%E6%98%AF%E4%B9%B1%E7%A0%81%E4%B8%94%E6%9F%A5%E9%87%8D%E6%97%A0%E6%B3%95%E6%AD%A3%E7%A1%AE%E8%AF%86%E5%88%AB%E6%96%87%E6%9C%AC%E5%86%85%E5%AE%B9)

这个解释或许是比较合理的。我的overleaf的版本是2020。
