### ISSUE TITLE
参考文献格式问题

### ISSUE THREAD

**Issue by Daisy-7** [whutug/whu-thesis#46]
你好，感谢提供Latex模板！
在使用时发现参考文献引用时，人名和年份之间的空格很宽（如下图），请问该如何调整？在word中使用文献管理器自带的2015版GB就没问题，是否与GB版本有关？
![QQ截图20210321164404](https://user-images.githubusercontent.com/48400510/111899150-a9cc4a80-8a65-11eb-975b-266e174e7d72.png)

**Comment by tanukihee** [comment]
倒不是与版本有关，只是我设置了引用时使用中文标点。但 natbib 又会在标点后面加空格……

干脆全部用西文标点吧，你可以先用 biblatex 凑合一下

**Comment by Daisy-7** [comment]
> 倒不是与版本有关，只是我设置了引用时使用中文标点。但 natbib 又会在标点后面加空格……
> 
> 干脆全部用西文标点吧，你可以先用 biblatex 凑合一下

好的，谢谢！另外中文文献引用时人名和等之间也会出现空格。
![QQ截图20210321180811](https://user-images.githubusercontent.com/48400510/111900986-6deab280-8a70-11eb-90a4-ab3ed665d37a.png)

**Comment by tanukihee** [comment]
> 好的，谢谢！另外中文文献引用时人名和等之间也会出现空格。

这个不太好解决😂

**Comment by tanukihee** [comment]
fixed via 1157b4c

**Comment by zepinglee** [comment]
> 另外中文文献引用时人名和等之间也会出现空格。

这个是国标要求的。
<img width="725" alt="Screen Shot 2021-03-26 at 11 03 40" src="https://user-images.githubusercontent.com/12290822/112571416-ee1f6800-8e22-11eb-92dc-171dd26cf5cb.png">
