### ISSUE TITLE
\rightarrow和\prime在标题和摘要中显示出错

### ISSUE THREAD

**Issue by AmaiAya** [whutug/whu-thesis#47]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [ ] macOS
  - [ ] Linux（请附发行版）

- TeX 发行版
  - [x] TeX Live 2020
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 描述问题

\rightarrow（右箭头），\prime（角分符号）在标题和摘要中会分别显示为感叹号和0。两边的字体似乎都不是Times New Roman。

## 最小工作示例（MWE）

下载v0.6b版本，在whu-thesis-demo中仅修改titile为：
```latex
title          = {$ \psi (2S) \rightarrow \omega \eta^{\prime} $},
```
在pages\abstract.tex中增加一行：
```latex
$$ \psi (2S) \rightarrow \omega \eta^{\prime} $$
```

用 LuaLaTeX 编译后输出：
标题：
![image](https://user-images.githubusercontent.com/61894565/112709041-f0e88e80-8ef0-11eb-829e-c646b4b06e80.png)
摘要：
![image](https://user-images.githubusercontent.com/61894565/112709054-06f64f00-8ef1-11eb-8408-3973a0aeb230.png)
本地编译和Overleaf编译结果相同。

## 我还做了这些尝试
在正文中可以正常显示前述两个符号，字体为Times New Roman：
![image](https://user-images.githubusercontent.com/61894565/112709060-14abd480-8ef1-11eb-9bf1-4bd06fea74d9.png)
使用2020年12月31日下载的旧版本编译，可以在标题和摘要中正常显示前述两个符号，字体为Times New Roman，不过prime符号似乎离字母有点远：
![image](https://user-images.githubusercontent.com/61894565/112709108-6fddc700-8ef1-11eb-92e2-3be4cb9908ff.png)

**Comment by tanukihee** [comment]
你的字体设置是什么？`style/font` 和 `style/math-font`

**Comment by tanukihee** [comment]
可以复现，不用提供log了

**Comment by tanukihee** [comment]
用 `newtx` 可以解决，先凑合一下吧

**Comment by tanukihee** [comment]
似乎是 `newtx` 引入的问题…暂时先去掉了

**Comment by tanukihee** [comment]
> 不过prime符号似乎离字母有点远：
> ![image](https://user-images.githubusercontent.com/61894565/112709108-6fddc700-8ef1-11eb-92e2-3be4cb9908ff.png)

这个是似乎是字号的问题

**Comment by tanukihee** [comment]
> 不过prime符号似乎离字母有点远：
> ![image](https://user-images.githubusercontent.com/61894565/112709108-6fddc700-8ef1-11eb-92e2-3be4cb9908ff.png)

https://github.com/CTeX-org/forum/issues/191

**Comment by tanukihee** [comment]
https://github.com/wspr/unicode-math/issues/528
