### ISSUE TITLE
硕士期间研究成果怎么添加

### ISSUE THREAD

**Issue by tulipper** [whutug/whu-thesis#48]
只有当类型为doctor时会添加achievement,当选则类型为master时不会。
请问怎么添加硕士旗舰研究成果

**Comment by tanukihee** [comment]
规范里没要求，有说应该加在哪儿吗？没有的话我就加在和博士一样的位置了

**Comment by tanukihee** [comment]
将 `\__whu_make_achievements:` 添加到
https://github.com/whutug/whu-thesis/blob/4a80330530d23340402f814a2e30e442b62b16f6/whu-thesis.cls#L1389-L1394
之间，同时修改
https://github.com/whutug/whu-thesis/blob/4a80330530d23340402f814a2e30e442b62b16f6/whu-thesis.cls#L1443-L1445
的「攻博期间发表的科研成果目录」

**Comment by tanukihee** [comment]
同 #67，推荐在附录里列出

**Comment by sikouhjw** [comment]
我这边倒是有说在哪加，我是在前面抑制了编号，然后直接写的
https://github.com/sikouhjw/gdutthesis/blob/153c7085032222a22db76c77532df1ca6ee08b05/main.tex#L158-L175

**Comment by tanukihee** [comment]
像 thu 那样单独写一个环境当然是最方便的了。我校只对博士有研究成果章节的要求，其他都没有。他们要加的话我也只推荐在附录里加了

**Comment by wzm2256** [comment]
开个问题太复杂了。。。我就在这问好了，achievement能否支持bibentry？现在是直接要在item里面粘贴引文格式，感觉有点麻烦。

**Comment by xkwxdyy** [comment]
> 开个问题太复杂了。。。我就在这问好了，achievement能否支持bibentry？现在是直接要在item里面粘贴引文格式，感觉有点麻烦。

如果用了 bibentry，那么你的文献会出现在“参考文献”中，这显然并不合理。

**Comment by wzm2256** [comment]
> > 开个问题太复杂了。。。我就在这问好了，achievement能否支持bibentry？现在是直接要在item里面粘贴引文格式，感觉有点麻烦。
> 
> 如果用了 bibentry，那么你的文献会出现在“参考文献”中，这显然并不合理。

理论上可以用一个 \nobibliography{}， 当然还是要改cls文件，而且我当时没有成功。但是无所谓了，我已经毕业了，这个问题留给师弟师妹们操心吧。
