### ISSUE TITLE
目录缩进问题

### ISSUE THREAD

**Issue by ccjjxx99** [whutug/whu-thesis#51]
![image](https://user-images.githubusercontent.com/32434705/114125914-f2bb4480-9929-11eb-8cfa-424c610789e4.png)
这是学校给的word模板要求，对section的下一级是需要再多两个字的缩进的，而现在的本科模板缩进全是相同的

**Comment by tanukihee** [comment]
是本科的吗？我研究一下

你先用​ `\renewcommand​\cftsubsecindent​{4em}` 顶一下

**Comment by ccjjxx99** [comment]
> 是本科的吗？我研究一下
> 
> 你先用​ `\renewcommand​\cftsubsecindent​{4em}` 顶一下

是本科，这个命令写在哪里呢

**Comment by sikouhjw** [comment]
> 
> 
> > 是本科的吗？我研究一下
> > 你先用​ `\renewcommand​\cftsubsecindent​{4em}` 顶一下
> 
> 是本科，这个命令写在哪里呢

导言区，那么导言区又在哪呢？

**Comment by tanukihee** [comment]
> ![image](https://user-images.githubusercontent.com/32434705/114125914-f2bb4480-9929-11eb-8cfa-424c610789e4.png)
> 这是学校给的word模板要求，对section的下一级是需要再多两个字的缩进的，而现在的本科模板缩进全是相同的

你能提供一下模板的地址吗，我这里学院的要求是不缩进的

**Comment by tanukihee** [comment]
> 是本科，这个命令写在哪里呢

导言区，`\documentclass` 后，`\begin{document}` 前

**Comment by ccjjxx99** [comment]
> > ![image](https://user-images.githubusercontent.com/32434705/114125914-f2bb4480-9929-11eb-8cfa-424c610789e4.png)
> > 这是学校给的word模板要求，对section的下一级是需要再多两个字的缩进的，而现在的本科模板缩进全是相同的
> 
> 你能提供一下模板的地址吗，我这里学院的要求是不缩进的
> 
> ![image](https://user-images.githubusercontent.com/34062491/114134582-91e83800-993a-11eb-89f1-5bd3fa3a8eca.png)

谢谢你，好像确实不需要缩进，我看的这个模板有点旧，刚刚去官网看了今年的要求是没问题的

**Comment by tulipper** [comment]
> > ![image](https://user-images.githubusercontent.com/32434705/114125914-f2bb4480-9929-11eb-8cfa-424c610789e4.png)
> > 这是学校给的word模板要求，对section的下一级是需要再多两个字的缩进的，而现在的本科模板缩进全是相同的
> 
> 你能提供一下模板的地址吗，我这里学院的要求是不缩进的
> 
> ![image](https://user-images.githubusercontent.com/34062491/114134582-91e83800-993a-11eb-89f1-5bd3fa3a8eca.png)

请问有像这种的详细格式文档吗，硕士论文的。

**Comment by tanukihee** [comment]
> 请问有像这种的详细格式文档吗，硕士论文的。

没有，只有本科有

硕士博士我是参照 https://gs.whu.edu.cn/info/1026/1096.htm 与 https://gs.whu.edu.cn/info/1026/1100.htm 写的

**Comment by earthmoon** [comment]
> \renewcommand​\cftsubsecindent​{4em}

你好，我增加了这一行，但是报错，怎么办呢？我写的是博士论文。

**Comment by yemanzhongting** [comment]
空格删除就行了

**Comment by earthmoon** [comment]
> \renewcommand​\cftsubsecindent​{4em}

此问题已解决，千万不要在字符中留空格。
