### ISSUE TITLE
公式错误编译出现错误Extended mathchar used as mathchar (14799924).

### ISSUE THREAD

**Issue by phoenixsfly** [whutug/whu-thesis#52]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [ ] macOS
  - [ ] Linux（请附发行版）

- TeX 发行版
  - [x] TeX Live  2020
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 描述问题

使用demo给出的公式代码
```latex
\begin{equation}
    \vb*{A} =
    \begin{bmatrix}
        1  & 2  & 3  & 4  \\
        11 & 22 & 33 & 44 \\
    \end{bmatrix} \times
    \begin{bmatrix}
        22 & 24 \\
        32 & 34 \\
        42 & 44 \\
        52 & 54 \\
    \end{bmatrix}
\end{equation}
```

（用 XeLaTeX 编译后）输出

```latex
 Extended mathchar used as mathchar (14799924).
<to be read again> 
                   \relax 
l.9     \vb*{A}
                =
A mathchar number must be between 0 and "7FFF.
I changed this one to zero.

Missing character: There is no ^^@ in font [XITSMath-Bold.otf]/OT:script=math;language=dflt;!
) [11]
\openout2 = `pages/chapter4.aux'.
```
似乎是\vb*出现了问题？

**Comment by tanukihee** [comment]
TeX Live 2021 并不能复现……你可以试试直接 clone 仓库而不是使用 release

**Comment by phoenixsfly** [comment]
找到问题原因了
之前在开头引入了宏包\usepackage{bm}，将其删除即可

**Comment by tanukihee** [comment]
> 找到问题原因了
> 之前在开头引入了宏包\usepackage{bm}，将其删除即可
> 

unicode-math 可以直接用 \symbf 之类的命令

如果要兼容 bm 的话感觉可以学 thu 重定义一下那几个命令
