### ISSUE TITLE
自定义参考文献格式

### ISSUE THREAD

**Issue by Daisy-7** [whutug/whu-thesis#53]
给老板看了初稿，嫌弃参考文献格式排版混乱，需要在作者年份引用情况下，对文献编号并修改缩进(奇怪的要求)，如下图所示。请问要修改应该如何改正？十分感谢！
![QQ截图20210410104526](https://user-images.githubusercontent.com/48400510/114256098-5b69f600-99ea-11eb-8030-576216b4b14c.png)

**Comment by tanukihee** [comment]
没法直接改，但可以使用 biblatex。设置 `style/bib-style=numerical`，并将 cls 的第 952 行的 `citestyle` 改为 `gb7714-2015ay` 即可

我会在后续版本添加接口的

**Comment by sikouhjw** [comment]
考虑一下像 https://github.com/stone-zeng/fduthesis 那样提供接口给用户怎么样（

**Comment by tanukihee** [comment]
> 考虑一下像 https://github.com/stone-zeng/fduthesis 那样提供接口给用户怎么样（

整个 whu-thesis 就是抄 fduthesis 的🤣🤣🤣规范里没那么多要求我当初就没抄完整

现在看来还是有必要的🤣🤣🤣

**Comment by zepinglee** [comment]
> 没法直接改，但可以使用 biblatex。设置 `style/bib-style=numerical`，并将 cls 的第 952 行的 `citestyle` 设置为 `gb7714-2015ay`

`style/bib-style=numerical` 这样会导致参考文献表中年份的位置不对。

**Comment by zepinglee** [comment]
用 BibTeX 的话可以设置 `style/bib-style = author-year`，并且在 `\end{document}` 前设置 `\setcitestyle{numbers}`。

**Comment by tanukihee** [comment]
> `style/bib-style=numerical` 这样会导致参考文献表中年份的位置不对。

fduthesis 问过一样的问题
 https://github.com/stone-zeng/fduthesis/issues/183

我还全程围观了来着…

**Comment by zepinglee** [comment]
https://github.com/stone-zeng/fduthesis/issues/183#issuecomment-793875997 也没完全解决。

我的意思是 author-year 的参考文献表是「作者, 年份. 标题」的格式，其中年份紧跟作者。而用 `style/bib-style=numerical` 得到的是「作者. 标题.  出版地: 出版社, 年份」。

**Comment by Daisy-7** [comment]
> 用 BibTeX 的话可以设置 `style/bib-style = author-year`，并且在 `\end{document}` 前设置 `\setcitestyle{numbers}`。

直接在`\end{document}` 前设置 `\setcitestyle{numbers}`可以满足我的要求，万分感谢！

**Comment by tanukihee** [comment]
> https://github.com/stone-zeng/fduthesis/issues/183#issuecomment-793875997 也没完全解决。
> 
> 我的意思是 author-year 的参考文献表是「作者, 年份. 标题」的格式，其中年份紧跟作者。而用 `style/bib-style=numerical` 得到的是「作者. 标题.  出版地: 出版社, 年份」。

https://github.com/hushidong/biblatex-gb7714-2015/issues/90

**Comment by Daisy-7** [comment]
在这个格式中还有一个问题想请教一下各位，如何在列表里只将作者名首字母大写，其余部分小写，并且在三个以上作者时列出全部作者名。

**Comment by zepinglee** [comment]
BibTeX 的话，https://github.com/whutug/whu-thesis/blob/e0953c7e1cc85c435dfd6b218db2be0795466306/data/gbt7714-2005-author-year.bst#L65 改成 `#0`。

BibLaTeX 参考 `biblatex-gb7714` 的文档。
