### ISSUE TITLE
bibtex编译报错

### ISSUE THREAD

**Issue by pangbobi** [whutug/whu-thesis#54]
* 操作系统
  + [ ] Windows 10

* TeX 发行版
  winedt最新，宏包最新

* whu-thesis 版本
你昨天更新的还未正式发布的

修改如图模板参数后，xelatex一次编译后，bibtex编译失败

![20210411004651](https://user-images.githubusercontent.com/49721270/114278034-6495aa00-9a60-11eb-94c3-5ff345172ea0.png)

**Comment by tanukihee** [comment]
winEDT 只是编辑器，如果你使用的是 CTeX 套装的话，whu-thesis 不支持，也不计划支持 CTeX 套装，请使用 TeX Live 2021

**Comment by pangbobi** [comment]
好的，谢谢你的帮助

**Comment by tanukihee** [comment]
请检查是否有 `\cite` 命令或 `\nocite` 命令（pages/chapter3.tex 里有，你是不是注释掉了？），尝试删除所有辅助文件并重新编译

另外 winEDT 只是编辑器，你的发行版是 MiKTeX 21.3

**Comment by pangbobi** [comment]
> 请检查是否有 `\cite` 命令或 `\nocite` 命令（pages/chapter3.tex 里有，你是不是注释掉了 `\include`？），尝试删除所有辅助文件并重新编译
> 
> 另外 winEDT 只是编辑器，你的发行版是 MiKTeX 21.3

不是这个原因，在你给我发消息之前，我下载了v0.6b，什么也没改，winedt中bibtex编译会出现同意的错误

**Comment by tanukihee** [comment]
使用命令行编译也会提示同样的错误吗

在命令行输入
```bash
xelatex whu-thesis-demo
bibtex whu-thesis-demo
```

**Comment by pangbobi** [comment]
> 使用命令行编译也会提示同样的错误吗
> 
> 在命令行输入
> 
> ```shell
> xelatex whu-thesis-demo
> bibtex whu-thesis-demo
> ```
> 
> 或者使用 latexmk
> 在命令行输入
> 
> ```shell
> latexmk -xelatex whu-thesis-demo
> ```

命令行没问题，装了半天tex live装不上，索性用自带的texworks编译了，没有问题。应该是winedt编辑器的问题。

**Comment by tanukihee** [comment]
> 命令行没问题，装了半天tex live装不上，索性用自带的texworks编译了，没有问题。应该是winedt编辑器的问题。

那我就关了
