### ISSUE TITLE
在caption里插入reference

### ISSUE THREAD

**Issue by skelviper** [whutug/whu-thesis#55]
## 检查

* [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

* 操作系统
  + [x] Windows 10
  + [ ] Windows 8/8.1
  + [ ] Windows 7
  + [ ] 更早版本的 Windows
  + [ ] macOS
  + [ ] Linux（请附发行版）

* TeX 发行版
  + [x] TeX Live 
  + [ ] MiKTeX 
  + [ ] CTeX 套装 2.9.2.164
  + [ ] 更早版本的 CTeX 套装

* whu-thesis 版本

  

## 描述问题

您好：
感谢您提供的whu-thesis模板，给我的毕设帮助很大。

我希望能在图片的caption里面加入citation，但是直接使用\cite{} 无法通过编译。在google上查过有人添加\protect 但是也不能解决。
添加\protect 后 result.tex 报错 Citation `ZhouMa-125' on page 13 undefined. 
在whu-thesis.tex（就那个主要的文件里） 报Missing } inserted.
在whu-thesis.lof 里报Extra }, or forgotten \endgroup.<argument> ...orespaces \cite {ZhouMa-125}\relax }

而我在refs.bib 里确实添加了这个文献，在\caption 外使用也没有问题。

## 下面是我用的code

``` latex
\begin{figure}
    \centering
    \includegraphics[width=\textwidth]{figures/fig1.jpg}
    \caption{\protect\cite{ZhouMa-125}}
    \label{fig:fig1}
\end{figure}
```

麻烦您看看是哪里的问题，非常感谢！

**Comment by sikouhjw** [comment]
这样写 https://tex.stackexchange.com/a/227840/209043
```tex
\caption[test]{test\cite{ZhouMa-125}}
```
