### ISSUE TITLE
overleaf编译得到的pdf中逗号字体不对

### ISSUE THREAD

**Issue by XZZong** [whutug/whu-thesis#56]
## 检查

* [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境
* TeX 发行版
  + [x] TeX Live 2020
  + [ ] MiKTeX 
  + [ ] CTeX 套装 2.9.2.164
  + [ ] 更早版本的 CTeX 套装

* whu-thesis 版本

  
0.6c
## 描述问题
前面有人提到使用本地编译在查重时会存在[问题](https://github.com/whutug/whu-thesis/issues/45)，用overleaf可以。overleaf使用的编译器是XeLaTex，TeX Live 2020，最终编译得到的pdf中逗号显示结果与提供的demo很不同，明显不是宋体，怀疑是半角与全角的区别，没找到解决方案。
![overleaf逗号](https://github.com/XZZong/latex/blob/main/overleaf.jpg)
图片链接：https://github.com/XZZong/latex/blob/main/overleaf.jpg

**Comment by sikouhjw** [comment]
是「宋体」，FandolSong 也是「宋体」。
你说的区别是「中易宋体」和「FandolSong」的区别。
你可以自己上传字体然后指定字体，也可以用 Overleaf 自带的字体，参考 https://sikouhjw.gitee.io/2021/02/14/2021-02-14-fontset-overleaf/

**Comment by sikouhjw** [comment]
其次，只有 texlive 2017 之类的老版本才会有查重的问题，要透过现象看本质，我感觉你是「没有病乱投医」，你连自己的发行版都没说，怎么能确定本地不行呢？再说了安装 texlive 2021 不就什么事都没了

**Comment by tanukihee** [comment]
需要在 overleaf 使用中易字体时，请在目录下上传中易的宋黑仿楷四个字体（windows下的「宋体」「黑体」「仿宋」「楷体」），然后在 `\whusetup` 里指定 `style/cjk-font = overleaf`。详情请查看文档。

**Comment by sikouhjw** [comment]
> 需要在 overleaf 使用中易字体时，请在目录下上传中易的宋黑仿楷四个字体（windows下的「宋体」「黑体」「仿宋」「楷体」），然后在 `\whusetup` 里指定 `style/cjk-font = overleaf`。详情请查看文档。

我感觉这样设置好怪，Overleaf 却不用 Overleaf 的字体（

**Comment by tanukihee** [comment]
> > 需要在 overleaf 使用中易字体时，请在目录下上传中易的宋黑仿楷四个字体（windows下的「宋体」「黑体」「仿宋」「楷体」），然后在 `\whusetup` 里指定 `style/cjk-font = overleaf`。详情请查看文档。
> 
> 我感觉这样设置好怪，Overleaf 却不用 Overleaf 的字体（

其实老版本就是指定用 `windows` 的，但由于 unix 和 windows 的字体调用问题（字体名与文件名），不得已才拆成两份

**Comment by sikouhjw** [comment]
> > > 需要在 overleaf 使用中易字体时，请在目录下上传中易的宋黑仿楷四个字体（windows下的「宋体」「黑体」「仿宋」「楷体」），然后在 `\whusetup` 里指定 `style/cjk-font = overleaf`。详情请查看文档。
> > 
> > 
> > 我感觉这样设置好怪，Overleaf 却不用 Overleaf 的字体（
> 
> 其实老版本就是指定用 `windows` 的，但由于 unix 和 windows 的字体调用问题（字体名与文件名），不得已才拆成两份。反正大家也只需要 win 下的结果（

打倒中易字库，复兴开源字体（

**Comment by tanukihee** [comment]
> 是「宋体」，FandolSong 也是「宋体」。
> 你说的区别是「中易宋体」和「FandolSong」的区别。
> 你可以自己上传字体然后指定字体，也可以用 Overleaf 自带的字体，参考 https://sikouhjw.gitee.io/2021/02/14/2021-02-14-fontset-overleaf/

@XZZong 这是标答，关了
