### ISSUE TITLE
Clone 下来之后未做任何修改但编译失败

### ISSUE THREAD

**Issue by cycychenyi** [whutug/whu-thesis#57]
## 检查

* [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

* 操作系统
  + [x] Windows 10
  + [ ] Windows 8/8.1
  + [ ] Windows 7
  + [ ] 更早版本的 Windows
  + [ ] macOS
  + [ ] Linux（请附发行版）

* TeX 发行版
  + [x] TeX Live 2020 
  + [ ] MiKTeX 
  + [ ] CTeX 套装 2.9.2.164
  + [ ] 更早版本的 CTeX 套装

* whu-thesis 版本

  0.6c 

## 描述问题

 1. 描述出现的情况
   ![image](https://user-images.githubusercontent.com/48085050/115559366-39278080-a2e6-11eb-8585-1739773bf81a.png)
 2. 给出复现步骤
    - 按照文档说明安装 VSCode 的插件 LaTex Workshop
    - 将仓库 clone 下来之后用 VSCode 打开项目
    - 打开 whu-thesis-demo.tex 文件，点击左下角的 √，执行 Build LaTex Project 命令
 3. 给出您解决问题所进行的尝试
    - 我询问了一个同学，她和我的操作一样，可以编译成功。
    - 重新 clone 仓库，再进行一遍操作，仍然失败。

我对 Tex 不是很熟悉，请问接下来应该怎么排查呀？希望能尽快得到答复，十分感谢！

**Comment by sikouhjw** [comment]
用命令行编译
```
cd /d <工作目录>
xelatex whu-thesis-demo.tex
```

**Comment by cycychenyi** [comment]
> 用命令行编译
> 
> ```
> cd /d <工作目录>
> xelatex whu-thesis-demo.tex
> ```

感谢！我问了一下同学，她用的是 Tex Live 2021，我现在卸载了 2020，在重新安装。

**Comment by cycychenyi** [comment]
有另一个同学她也是在 Tex Live 2020 上遇到了同样的问题，重新安装 Tex Live 2021 后编译成功。等我安装成功了试一下，如果可以就关闭。

**Comment by tanukihee** [comment]
是版本的问题，见#35，关了
