### ISSUE TITLE
编译警告 "\fancyhead's `E' option without twoside option is useless."

### ISSUE THREAD

**Issue by chirsz-ever** [whutug/whu-thesis#58]
## 检查

* [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

* 操作系统
  + [ ] Windows 10
  + [ ] Windows 8/8.1
  + [ ] Windows 7
  + [ ] 更早版本的 Windows
  + [ ] macOS
  + [x] ArchLinux

* TeX 发行版
  + [x] TeX Live 2021
  + [ ] MiKTeX 
  + [ ] CTeX 套装 2.9.2.164
  + [ ] 更早版本的 CTeX 套装

* whu-thesis 版本

  v0.6c
## 描述问题

使用 `oneside` 文档选项，编译时会出现多条警告 "\fancyhead's `E' option without twoside option is useless."

## 最小工作示例（MWE）

略

## 我还做了这些尝试

修改第 260 行，在有 `oneside` 选项时不提供 `E` 应该就行了。

https://github.com/whutug/whu-thesis/blob/b706a3e561c22f14653ea3055711767adbe0b796/whu-thesis.cls#L259-L261

**Comment by tanukihee** [comment]
`oneside` 只在本科下能用，硕博是规定双面打印的

而本科又没有页眉，所以这个 warning 我就没管…

**Comment by chirsz-ever** [comment]
怎么关了？好像没修啊……

**Comment by tanukihee** [comment]
> 怎么关了？好像没修啊……

完全无害的警告，懒得修了……
