### ISSUE TITLE
参考文献的引用问题

### ISSUE THREAD

**Issue by pangbobi** [whutug/whu-thesis#61]
在不改变作者，文献名等顺序的情况下，怎么自定义按原来bibtex的大小写格式？例如我只想要人名首字母大写，文献名就按照bibtex里的大小写格式

**Comment by zepinglee** [comment]
对应 `.bst` 文件的 `#1 uppercase.name :=` 改为 `#0`。

**Comment by pangbobi** [comment]
好嘞

**Comment by LeoJackkk** [comment]
改了并没有变化
