### ISSUE TITLE
插入图片后如何取消的caption中文字自动加粗的效果

### ISSUE THREAD

**Issue by qqqqxxyy** [whutug/whu-thesis#62]
目前插入图片后caption有加粗效果，请问怎么操作可以取消加粗效果
![image](https://user-images.githubusercontent.com/37565300/116957669-02c90880-accb-11eb-9cff-8eec13470f26.png)

**Comment by sikouhjw** [comment]
规范怎么写的？

**Comment by qqqqxxyy** [comment]
规范上写的是小四号宋体
![image](https://user-images.githubusercontent.com/37565300/116958658-ebd7e580-accd-11eb-9cc2-828e2f9807e7.png)

**Comment by sikouhjw** [comment]
我看 cls 里没错啊，是「插图才加粗」，「不插图就没事」吗？

**Comment by qqqqxxyy** [comment]
哦哦我发现了，如果用caption 添加文字，会自动加粗，如果直接用大括号就不会加粗
![image](https://user-images.githubusercontent.com/37565300/116959471-512cd600-acd0-11eb-9a05-b9f31802c736.png)
![image](https://user-images.githubusercontent.com/37565300/116959487-5853e400-acd0-11eb-8bba-737b05828157.png)
那这样我的问题应该算是解决了

**Comment by sikouhjw** [comment]
问题并没有解决，请提供发行版、模板版本、编译方式、log 文件等信息

**Comment by tanukihee** [comment]
你用的版本是啥，overleaf 上的那个 0.1 好久没更新了…

以及你为什么要这样写 `\caption`

**Comment by qqqqxxyy** [comment]
我用的是overleaf
![image](https://user-images.githubusercontent.com/37565300/117099043-bb15b000-ada2-11eb-9d1c-2b0bf3e807b2.png)
模板是最新版本应该，四月初刚下载的

**Comment by tanukihee** [comment]
版本号？

**Comment by qqqqxxyy** [comment]
那个宋体是我后来百度加的，发现没啥用。
版本号是v0.1
![image](https://user-images.githubusercontent.com/37565300/117099297-6161b580-ada3-11eb-9aac-514ef8a254b1.png)

**Comment by tanukihee** [comment]
太太太太太太老了

**Comment by qqqqxxyy** [comment]
好的，感谢！
