### ISSUE TITLE
参考文献中作者人名含重音

### ISSUE THREAD

**Issue by SwitWu** [whutug/whu-thesis#63]
参考文献中作者名含有重音导致出现下面的情况
![屏幕截图 2021-05-05 082152](https://user-images.githubusercontent.com/39337667/117084907-f8664780-ad7a-11eb-8224-8625d9a5e197.png)
请问这样符合标准吗？

**Comment by tanukihee** [comment]
7714 中似乎没有出现过带重音符号的外文人名，但我猜这里的字母也需要转为大写（这一点需要与 @zepinglee 老师确认）

测试发现，如果使用 bibtex，只有使用 `\"o` 之类的转义符号（而不是直接使用 ö），可以自动转为大写；同时，如果使用 biblatex，则无论使用转义还是直接使用 ö，都能自动转为大写

![image](https://user-images.githubusercontent.com/34062491/117100596-b3580a80-ada6-11eb-9b33-ebd5a067ae3b.png)

**Comment by SwitWu** [comment]
> 7714 中似乎没有出现过带重音符号的外文人名，但我猜这里的字母也需要转为大写（这一点需要与 @zepinglee 老师确认）
> 
> 测试发现，如果使用 bibtex，只有使用 `\"o` 之类的转义符号（而不是直接使用 ö）才可以自动转为大写；同时，如果使用 biblatex，则无论使用转义还是直接使用 ö，都能自动转为大写
> 
> ![image](https://user-images.githubusercontent.com/34062491/117100596-b3580a80-ada6-11eb-9b33-ebd5a067ae3b.png)

**Comment by SwitWu** [comment]
直接使用转义符号确实变为大写，感谢。

**Comment by zepinglee** [comment]
BibTeX 不支持 unicode，所以只有用 `\"o` 才能转换大小写。

**Comment by SwitWu** [comment]
明白了，谢谢解答！
