### ISSUE TITLE
图片的caption无法正常显示

### ISSUE THREAD

**Issue by FelliYang** [whutug/whu-thesis#64]
## 检查

* [ ] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

* 操作系统
  + [x] Windows 10
  + [ ] Windows 8/8.1
  + [ ] Windows 7
  + [ ] 更早版本的 Windows
  + [ ] macOS
  + [ ] Linux（请附发行版）

* TeX 发行版
  + [ ] TeX Live 
  + [x] MiKTeX 21.2
  + [ ] CTeX 套装 2.9.2.164
  + [ ] 更早版本的 CTeX 套装

* whu-thesis 版本

  v0.6

## 描述问题

我想2x2显示4张图片，但是排列后发现caption无法正常显示
![image](https://user-images.githubusercontent.com/38461329/118354033-ad7ada00-b59b-11eb-8b90-be2ebf93a308.png)
然而，当我使用同样代码，应用在其他四张图片时，一切又正常显示了。
![image](https://user-images.githubusercontent.com/38461329/118354083-e4e98680-b59b-11eb-8890-19c7353057a0.png)

## 最小工作示例（MWE）

\documentclass[type=bachelor,oneside]{whu-thesis}
\whusetup
  {
    info               =
      {
        title          = {XXX},
        student-number = {XXX},
        school         = {XXX},
        author         = {XXX},
        % subject        = {XXX},
        major          = {XXX},
        advisor        = {XX , XX},
        % direction      = {研究方向},
        % date           = {2021/4},
        keywords       = {XXX},
        keywords*      = {XXX},
      },
    style              =
      {
        graphics-path  = {{figures/}{data/}},
        % list-of-figures,
        % list-of-tables,
      },
    element            =
      {
        % innovation     = {pages/innovation},
        abstract       = {pages/abstract},
        abstract*      = {pages/enabstract},
        bibliography   = {ref/ref},
        achievements   = {pages/achievements},
        thanks         = {pages/thanks},
        % appendix       = {pages/appendix}
      }
  }
\renewcommand\cftsubsecindent{4em}

\begin{document}
%%----------- 主体部分 ----------- %%
% \include{pages/chapter1}
% \include{pages/chapter2}
% \include{pages/chapter3}
% \include{pages/chapter4}

\begin{figure}[htb]
  \centering
  \begin{subfigure}{0.45\textwidth}
      \includegraphics[width=\linewidth]{match_result_a.png}
      \caption{视频第2帧}
      \label{fig:match_result_a}
  \end{subfigure}\ 
  \begin{subfigure}{0.45\textwidth}
      \includegraphics[width=\linewidth]{match_result_b.png} 
      \caption{视频第8帧}
      \label{fig:match_result_b}
  \end{subfigure}

  \begin{subfigure}{0.45\textwidth}
      \includegraphics[width=\linewidth]{match_result_c.png} 
      \caption{视频第14帧}
      \label{fig:match_result_c}
  \end{subfigure}\ 
  \begin{subfigure}{0.45\textwidth}
      \includegraphics[width=\linewidth]{match_result_d.png} 
      \caption{视频第18帧} 
      \label{fig:match_result_d}
  \end{subfigure}

  \caption{视频线段跟踪效果图1}
  \label{fig:match_result}
\end{figure}

\begin{figure}[htb]
  \centering
  \begin{subfigure}{0.45\textwidth}
      \includegraphics[width=\linewidth]{tracking_demo1_a.png}
      \caption{视频第2帧}
      \label{fig:tracking_demo1_a}
  \end{subfigure}\ 
  \begin{subfigure}{0.45\textwidth}
      \includegraphics[width=\linewidth]{tracking_demo1_b.png} 
      \caption{视频第8帧}
      \label{fig:tracking_demo1_b}
  \end{subfigure}

  \begin{subfigure}{0.45\textwidth}
      \includegraphics[width=\linewidth]{tracking_demo1_c.png} 
      \caption{视频第14帧}
      \label{fig:tracking_demo1_c}
  \end{subfigure}\ 
  \begin{subfigure}{0.45\textwidth}
      \includegraphics[width=\linewidth]{tracking_demo1_d.png} 
      \caption{视频第18帧} 
      \label{fig:tracking_demo1_d}
  \end{subfigure}

  \caption{视频线段跟踪效果图1}
  \label{fig:tracking_demo1}
\end{figure}

\end{document}

## 链接

* TeX. SX:
* GitHub:

**Comment by tanukihee** [comment]
暂不清楚是不是你图片的问题，不过你可以试试在第二章图后使用 `\\[<length>]` 来换行

**Comment by FelliYang** [comment]
谢谢！刚刚试了一下这个解决方案，设置为2em可以解决我的问题。在这里，提供一下原图，方便复现，找到可能的问题。
![match_result_b](https://user-images.githubusercontent.com/38461329/118365829-dd90a000-b5d0-11eb-948b-7f37e5b55c49.png)
![match_result_c](https://user-images.githubusercontent.com/38461329/118365835-e4b7ae00-b5d0-11eb-8a9c-f739ef05fadc.png)
![match_result_d](https://user-images.githubusercontent.com/38461329/118365837-e84b3500-b5d0-11eb-9b8d-aa8ecf373aa6.png)
![match_result_a](https://user-images.githubusercontent.com/38461329/118365842-ea14f880-b5d0-11eb-8050-c4e1fdbd2db0.png)

**Comment by sikouhjw** [comment]
（跑题：图片上的宿舍楼我之前比赛还去转过）

**Comment by FelliYang** [comment]
哈哈哈，比赛？这里不是桂院食堂嘛，天天都可以看到。

**Comment by sikouhjw** [comment]
> 
> 
> 哈哈哈，比赛？这里不是桂院食堂嘛，天天都可以看到。

（我是外校的，跑路）

**Comment by tanukihee** [comment]
无法复现

**Comment by FelliYang** [comment]
啊这，只是在我的电脑上会这样吗？我在上面放的代码中，demo是另外几张没有问题的图，所以没有放上去。这几张图片就是第一个大图中的4张子图，用这个代码段，作者生成的图片是正常的吗？
\begin{figure}[htb]
\centering
\begin{subfigure}{0.45\textwidth}
\includegraphics[width=\linewidth]{match_result_a.png}
\caption{视频第2帧}
\label{fig:match_result_a}
\end{subfigure}\
\begin{subfigure}{0.45\textwidth}
\includegraphics[width=\linewidth]{match_result_b.png}
\caption{视频第8帧}
\label{fig:match_result_b}
\end{subfigure}

\begin{subfigure}{0.45\textwidth}
\includegraphics[width=\linewidth]{match_result_c.png}
\caption{视频第14帧}
\label{fig:match_result_c}
\end{subfigure}\
\begin{subfigure}{0.45\textwidth}
\includegraphics[width=\linewidth]{match_result_d.png}
\caption{视频第18帧}
\label{fig:match_result_d}
\end{subfigure}

\caption{视频线段跟踪效果图1}
\label{fig:match_result}
\end{figure}

**Comment by FelliYang** [comment]
第一张图片时match_a,第四张图片时match_b, 第二张和第三章非别是match_c和match_d

**Comment by tanukihee** [comment]
![image](https://user-images.githubusercontent.com/34062491/118370270-8511d080-b5d9-11eb-83ad-239bd207a100.png)
你传的 4 张图片都是 16:9 的，但是你给出的结果中，只有第二张图是 16:9，第一张不是的


> ![image](https://user-images.githubusercontent.com/38461329/118354033-ad7ada00-b59b-11eb-8b90-be2ebf93a308.png)

> ![image](https://user-images.githubusercontent.com/38461329/118354083-e4e98680-b59b-11eb-8890-19c7353057a0.png)

**Comment by FelliYang** [comment]
这几张图是我在代码中的原图，输出的宽度一样，是因为latex把每一张图片的width都缩放成了0.45\linewidth。图片是否是16:9应该不会有影响啊？

**Comment by FelliYang** [comment]
另外，我还做了一些其他测试以供研究。
例如
![image](https://user-images.githubusercontent.com/38461329/118370703-8217df80-b5db-11eb-96bd-b997a8f18cde.png)
代码：
\begin{figure}[htb]
  \centering
  \begin{subfigure}{0.45\textwidth}
  \includegraphics[width=\linewidth]{match_result_a.png}
  % \caption{视频第2帧}
  % \label{fig:match_result_a}
  \end{subfigure}
  \begin{subfigure}{0.45\textwidth}
  \includegraphics[width=\linewidth]{match_result_b.png}
  % \caption{视频第8帧}
  % \label{fig:match_result_b}
  \end{subfigure}
  
  \begin{subfigure}{0.45\textwidth}
  \includegraphics[width=\linewidth]{match_result_c.png}
  \caption{视频第14帧}
  \label{fig:match_result_c}
  \end{subfigure}
  \begin{subfigure}{0.45\textwidth}
  \includegraphics[width=\linewidth]{match_result_d.png}
  \caption{视频第18帧}
  \label{fig:match_result_d}
  \end{subfigure}
  
  \caption{视频线段跟踪效果图1}
  \label{fig:match_result}
\end{figure}

这里就是简单地使用\enter符来分行(使用\\分行也测试, 不含有[]参数)，发现这种默认分行方式会导致下面的子图覆盖上面的图片，出现奇怪的遮挡现象。

**Comment by tanukihee** [comment]
不负责任地猜测一下，是你图片的参数有问题，而上传 gh 后 gh 帮你修正了

TeX 读取了错误的宽度数据，所以使图片变大，覆盖住底下的图注了

你可以试试对图片进行重新处理（比如 png 换 jpg）试试

**Comment by xkwxdyy** [comment]
> 另外代码请放进代码块（三个`）里

我刚帮他加了（
