### ISSUE TITLE
siunitx 宏包的升级带来的改变

### ISSUE THREAD

**Issue by SwitWu** [whutug/whu-thesis#65]
5月19日 ctan 发布了新版的 siunitx 宏包，需要修改 `whu-thesis.cls` 文件的相关代码进行适配。

**Comment by tanukihee** [comment]
好的，我看一看

具体有什么问题可以列一下吗？

如果影响使用，可以暂时先回退版本

**Comment by tanukihee** [comment]
目前看来是删掉了那几个 whu-thesis 里调用的选项

考虑到这是个大改，暂时准备在 whu-thesis 里删掉选项配置，让用户自己配置

**Comment by SwitWu** [comment]
嗯，先这样处理比较好。

**Comment by tanukihee** [comment]
少年，有意愿参与维护工作吗（

**Comment by SwitWu** [comment]
虽然有兴趣，但少平不够啊，高纳德的 TeXbook 看了一点就搁置了，哈哈。

**Comment by tanukihee** [comment]
不打紧，可以先看 l3，没有历史包袱（

**Comment by SwitWu** [comment]
嗯，那我加入一个吧

**Comment by tanukihee** [comment]
好的，我联系一下 @mtobeiyf
