### ISSUE TITLE
目录中三级标题缩进

### ISSUE THREAD

**Issue by wasPrime** [whutug/whu-thesis#66]
## 检查

* [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

* 操作系统
  + [x] Windows 10

* TeX 发行版
  + [x] TeX Live 2021

* whu-thesis 版本
  v0.6c(commit: e8bb70049b3c421a7fd7fb5cdd656c5c17495a3e)

## 描述问题

想要实现目录中三级标题缩进。

## 最小工作示例（MWE）

在导言区尝试过添加如下语句：

``` latex
\renewcommand​\cftsubsecindent​{4em}
```

（在 VSCode 中用 XeLaTeX 编译后）输出报错

``` latex
Command ​ undefined.

Missing control sequence inserted.
<inserted text> 

Missing \begin{document}.
```

看起来像是 `\renewcommand​` 尚未定义的报错……

**Comment by tanukihee** [comment]
不清楚什么原因，先用 `\def` 顶一下

**Comment by tanukihee** [comment]
猜测是 l3 更新的，对长度进行了保护，通用的解决方法是同 cls 中使用 `\dim_set:`

在导言区设置
```
\ExplSyntaxOn
  \dim_set:Nn \cftsubsecindent { <length> }
\ExplSyntaxOff
```

**Comment by tanukihee** [comment]
> ``` latex
> \renewcommand​\cftsubsecindent​{4em}
> ```

这一句里似乎有不可见的控制字符（U+200B，零宽空格）

你试试手动输入？

**Comment by wasPrime** [comment]
> > ```
> > \renewcommand​\cftsubsecindent​{4em}
> > ```
> 
> 这一句里似乎有不可见的控制字符（U+200B，零宽空格）
> 
> 你试试手动输入？

手动输入后就正常了。

用正则表达式 `\u200B` 进行匹配，的确可以匹配到 `\renewcommand​` 后和 `\cftsubsecindent​` 后是有 `\u200B` 零宽空格……

我当初是根据 VSCode 的自动提示输入的，这零宽字符咋来的……

**Comment by tanukihee** [comment]
哈哈，我也不知道怎么来的，最开始我还以为是 l3 的问题呢，先关了

**Comment by chirsz-ever** [comment]
我使用的方案：

```latex
\setlength{\cftsubsecindent}{\cftsubsecindent+2em}
```

**Comment by wzm2256** [comment]
> > ```
> > \renewcommand​\cftsubsecindent​{4em}
> > ```
> 
> 这一句里似乎有不可见的控制字符（U+200B，零宽空格）
> 
> 你试试手动输入？

手动输入就正常了
