### ISSUE TITLE
achievements在本科毕设论文模板中如何使用？

### ISSUE THREAD

**Issue by Sugar-Coder** [whutug/whu-thesis#67]
## 检查

* [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

* 操作系统
  + [ ] Windows 10
  + [ ] Windows 8/8.1
  + [ ] Windows 7
  + [ ] 更早版本的 Windows
  + [x] macOS
  + [ ] Linux（请附发行版）

* TeX 发行版
  + [x] TeX Live <2020>
  + [ ] MiKTeX 
  + [ ] CTeX 套装 2.9.2.164
  + [ ] 更早版本的 CTeX 套装

* whu-thesis 版本

  <v0.6>

## 描述问题
我选用的是本科生模板，想在论文里展示之前发表的成果，但是似乎achievements只能在博士论文里使用？如何修改呢？

```latex
element            =
      {
        % innovation     = {pages/innovation},
        abstract       = {mypages/abstract},
        abstract*      = {mypages/enabstract},
        bibliography   = {ref/myrefs},
        achievements   = {mypages/achievements},
        thanks         = {mypages/thanks}
        % appendix       = {pages/appendix}
      }
```

**Comment by Sugar-Coder** [comment]
哈哈哈，我自己搞定了😅，在.cls文件里面
<img width="658" alt="82A68E189CDC37D81334A114FBDCB8CD" src="https://user-images.githubusercontent.com/46956540/119646216-7b962d00-be51-11eb-80b0-7195adfe8230.png">
把doctor的那一行加到bachelor里面就行了
再把相关的标题改一下就行了

**Comment by tanukihee** [comment]
#48。话说这个需求广泛吗？

**Comment by Sugar-Coder** [comment]
其实不广泛，我最后把成果写在附录里了，这样更更方便，也不用改cls了😄
