### ISSUE TITLE
参考文献引用的问题

### ISSUE THREAD

**Issue by fpGHwd** [whutug/whu-thesis#68]
请问支持国内标准的论文引用格式吗？例如下面这样
![image](https://user-images.githubusercontent.com/11605000/119882368-eeda9480-bf60-11eb-8c73-67ab6af5001f.png)
![image](https://user-images.githubusercontent.com/11605000/119882469-07e34580-bf61-11eb-9662-697d8bc5b124.png)

非常需要这样的格式啊

**Comment by sikouhjw** [comment]
「这样」是哪样？「标准的论文引用格式」是 `GB/T 7714-2015`？

**Comment by tanukihee** [comment]
现在就是符合标准的。

你得先说明现有的格式与你所需要的格式有什么不同

我除了看到西文姓名没有全大写之外，没什么不同——这个还可以通过搜索历史 issue 改

难道你是硕博，默认作者-年，想改成顺序编码？

不管如何，需要提供更多信息

**Comment by fpGHwd** [comment]
抱歉之前没有仔细看文档，已经根据文档设置好了。之前不知道上标编号引用和按顺序排列引用的设置方法。谢谢！
