### ISSUE TITLE
建议：对 \figureautorefname 等命令进行重定义

### ISSUE THREAD

**Issue by chirsz-ever** [whutug/whu-thesis#71]
目前使用 hyperref 包的 `\autoref` 命令进行交叉引用时，引用 figure 环境产生的结果是 `Figure. xxx`，模板里只重定义了 `\figurename` 和 `\tablename` 而没有重定义 `\figureautorefname` 和 `\tableautorefname`。

**Comment by tanukihee** [comment]
> 模板里只重定义了 `\figurename` 和 `\tablename`

这个是 ctex 干的
