### ISSUE TITLE
建议：支持思源系列字体

### ISSUE THREAD

**Issue by chirsz-ever** [whutug/whu-thesis#72]
类似 `\ctexset` 中 `fontset` 的 `ubuntu` 选项。

参考 ctex，还可以允许设置 `cjk-font` 为 `none` 并允许用户自定义字体。

**Comment by sikouhjw** [comment]
https://github.com/whutug/whu-thesis/issues/56#issuecomment-821925942

其次思源有两个，又要考虑跨平台调用，适配起来很麻烦

**Comment by chirsz-ever** [comment]
我在 CTeX 那边也找到了相关问题：https://github.com/CTeX-org/ctex-kit/issues/203#issuecomment-292058099

甚至一度想不再支持 `fontset` 选项：https://github.com/CTeX-org/ctex-kit/pull/480/commits/f772d34f22e72876bcc05f94e032f6083fa1afeb

但目前 whu-thesis 没有指定 ctex 预设字体或者自定义中文字体的方式，可以加一个 `none` 选项，然后用户可以 `\ctexset{fontset = ubuntu}`  或者 `\setCJKmainfont ...`。还可以支持载入 `ctex-fontset-*.def`

**Comment by sikouhjw** [comment]
> 但目前 whu-thesis 没有指定 ctex 预设字体或者自定义中文字体的方式，可以加一个 `none` 选项，然后用户可以 `\ctexset{fontset = ubuntu}` 或者 `\setCJKmainfont ...`。还可以支持载入 `ctex-fontset-*.def`

这部分确实抄代码没抄到位

**Comment by tanukihee** [comment]
思源没有仿楷，不打算加思源

就学位论文格式审查老师的眼睛，你用华文或者 fandol 都有可能给你打回来，让你改用中易…

**Comment by tanukihee** [comment]
古早版本只有中易，华文和 fandol 是为了跨平台加的。所以也不会打算加 adobe 和方正

`none` 选项可能以后会加

**Comment by chirsz-ever** [comment]
e9919615 有一个问题，使用者指定 `cjk-font=none` 后除了自定义宋黑仿楷还需要自定义 `tablecap` 字体类和命令，建议想办法将之隐式化。

**Comment by tanukihee** [comment]
嗯……是个问题（这种表标题也太蛋疼了

**Comment by tanukihee** [comment]
暂时似乎没有什么优雅的解决方法……我先在文档里说明一下吧

**Comment by tanukihee** [comment]
当然最好的方法的就是劝大家不要改（

**Comment by sikouhjw** [comment]
定义一个 `\setwhuCJKsansfont` 怎么样
用户手册说一下就好

**Comment by sikouhjw** [comment]
这样写怎么样？
```tex
\documentclass{whu-thesis}
\whusetup
  {
    style              =
      {
        cjk-font=none,
      },
  }
\ExplSyntaxOn
\NewDocumentCommand \setwhuCJKmainfont { m o }
  {
    \__whu_set_cjk_font_song:nn{#1}{#2}
  }
\NewDocumentCommand \setwhuCJKsansfont { m o }
  {
    \__whu_set_cjk_font_hei:nn{#1}{#2}
  }
\NewDocumentCommand \setwhuCJKmonofont { m o }
  {
    \__whu_set_cjk_font_fang:nn{#1}{#2}
  }
\NewDocumentCommand \setwhuCJKkaifont { m o }
  {
    \__whu_set_cjk_font_kai:nn{#1}{#2}
  }
\ExplSyntaxOff
\setwhuCJKmainfont{SimSun}[AutoFakeBold = 4, AutoFakeSlant = 0.167]
\setwhuCJKsansfont{SimHei}[AutoFakeBold = 4, AutoFakeSlant = 0.167]
\setwhuCJKmonofont{FangSong}[AutoFakeBold = 4, AutoFakeSlant = 0.167]
\setwhuCJKkaifont{KaiTi}[AutoFakeBold = 4, AutoFakeSlant = 0.167]
\begin{document}
宋体\quad \textbf{粗体}\quad \textit{斜体}\quad \textbf{\textit{粗斜体}}。

{\heiti 黑体\quad \textbf{粗体}\quad \textit{斜体}\quad \textbf{\textit{粗斜体}}}。

{\fangsong 仿宋\quad \textbf{粗体}\quad \textit{斜体}\quad \textbf{\textit{粗斜体}}}。

{\kaishu 楷书\quad \textbf{粗体}\quad \textit{斜体}\quad \textbf{\textit{粗斜体}}}。

Serif\quad \textit{Italic}\quad \textbf{Bold}\quad \textbf{\textit{BoldItalic}}

{\sffamily Sans\quad \textit{Italic}\quad \textbf{Bold}\quad \textbf{\textit{BoldItalic}}}

{\ttfamily Mono\quad \textit{Italic}\quad \textbf{Bold}\quad \textbf{\textit{BoldItalic}}}
\end{document}
```

**Comment by tanukihee** [comment]
默认大家都会 l3，把 `__whu_set_cjk_font_xx:nn` 设为 public 得了（

**Comment by sikouhjw** [comment]
> 
> 
> 默认大家都会 l3，把 `\__whu_set_cjk_font_xx:nn` 设为 public，即 `\whu_set_cjk_font_xx:nn` 得了（

默认都不会 l3（

**Comment by tanukihee** [comment]
https://www.zhihu.com/question/463975644

😥😥😥

**Comment by tanukihee** [comment]
https://www.zhihu.com/question/463975644

😥😥😥

**Comment by chirsz-ever** [comment]
> https://www.zhihu.com/question/463975644
> 
> 😥😥😥

我提的（逃

**Comment by tanukihee** [comment]
> 我提的（逃

发到 CTeX-org/forum 吧，那里大神多
