### ISSUE TITLE
使用 XeLaTeX 编译时出现警告“It seems that you have not declare a CJKfamily. (xeCJK)”

### ISSUE THREAD

**Issue by chirsz-ever** [whutug/whu-thesis#74]
## 检查

* [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

* 操作系统
  + [ ] Windows 10
  + [ ] Windows 8/8.1
  + [ ] Windows 7
  + [ ] 更早版本的 Windows
  + [ ] macOS
  + [x] Linux（Arch Linux）

* TeX 发行版
  + [x] TeX Live 2021
  + [ ] MiKTeX 
  + [ ] CTeX 套装 2.9.2.164
  + [ ] 更早版本的 CTeX 套装

* whu-thesis 版本

v0.6d

## 描述问题

使用 XeLaTeX 编译时出现警告：

```
It seems that you have not declare a CJKfamily.
(xeCJK)	If you want to use xeCJK in the right way, you should
(xeCJK)	use
(xeCJK)	
(xeCJK)	`\setCJKmainfont[...]{...}'
(xeCJK)	
(xeCJK)	in the preamble to declare the default CJKfamily.
(xeCJK)	
```

## 最小工作示例（MWE）

``` latex
\documentclass{whu-thesis}
%\whusetup{ style/cjk-font = fandol }
\begin{document}
\end{document}
```

用 XeLaTeX 编译后出现如上警告，加入 `\whusetup{ style/cjk-font = fandol }` 仍然会出现警告。

猜测原因是使用 ctexhook 设置的 `\__xeCJK_at_end_preamble:n` 先于 `\AtEndPreamble` 设置的 `\__whu_set_xxx_font:` 执行。

不影响使用的小问题。

**Comment by tanukihee** [comment]
不对，这个问题来自于另一个方面，待会详细说明

**Comment by sikouhjw** [comment]
https://github.com/stone-zeng/fduthesis/issues/77

**Comment by sikouhjw** [comment]
等 fdu 修好再抄（逃

**Comment by tanukihee** [comment]
试了试，还是等着抄 fdu 了（逃

**Comment by stone-zeng** [comment]
改好了（逃
