### ISSUE TITLE
参考文献可以用[1]这样上标吗？

### ISSUE THREAD

**Issue by earthmoon** [whutug/whu-thesis#76]
### Discussed in https://github.com/whutug/whu-thesis/discussions/75

<div type='discussions-op-text'>

<sup>Originally posted by **earthmoon** July  1, 2021</sup>
因为我看武大的要求是要上标的，但是我看模板没有上标。</div>

**Comment by tanukihee** [comment]
硕博是要求用作者-年的，其他的在讨论里解决了

**Comment by earthmoon** [comment]
> 硕博是要求用作者-年的，其他的在讨论里解决了

能给个链接吗？硕博没有说要求**作者-年**的。只是说推荐使用**作者-年**。

**Comment by tanukihee** [comment]
确实是**推荐**而不是**要求**，我更正我的说法

**Comment by earthmoon** [comment]
> 确实是**推荐**而不是**要求**，我更正我的说法

即便是使用**作者-年**，在讨论中出现的引用一本书的页码，如果这本书只出现一次，应当把页码放在参考文献里，如果出现2次或者2次以上，参考文献里的这本书不出现页码，并且每次这本书出现的地方要在括号内输入页码。这个问题好像解决不了。

**Comment by tanukihee** [comment]
> 正文中的标注方式分两种：其一，正文里已出现著作者姓名的，在其后用圆括号附上出版年份即可；其二，正文里仅提及有关的资料内容而未提到著作者，则在相应文句处用圆括号标注著作者姓名和出版年份，两者之间加逗号。
>
> 引用同一著者在同一年份出版的多篇文献时，在出版年份之后用英文小写字母a、b、c……区别。如：（王平，2005a）；（王平，2005b）
>
> 引用多位著者的文献时，对欧美著者只需标注第一个著者的姓，其后附“et al.”或“等”,仅两位作者的也可全部注出,中间用“and”或“和”；对中国著者应该标注第一著者的姓名，其后附“等”字，例如：……（王平等，2005） ……。
同一处引用多篇文献时，按出版年份由早期到近期依次标注，中间用分号分开。

武大标准里似乎没有提到要标页码，示例中也没有给出

**Comment by earthmoon** [comment]
> > 正文中的标注方式分两种：其一，正文里已出现著作者姓名的，在其后用圆括号附上出版年份即可；其二，正文里仅提及有关的资料内容而未提到著作者，则在相应文句处用圆括号标注著作者姓名和出版年份，两者之间加逗号。
> > 引用同一著者在同一年份出版的多篇文献时，在出版年份之后用英文小写字母a、b、c……区别。如：（王平，2005a）；（王平，2005b）
> > 引用多位著者的文献时，对欧美著者只需标注第一个著者的姓，其后附“et al.”或“等”,仅两位作者的也可全部注出,中间用“and”或“和”；对中国著者应该标注第一著者的姓名，其后附“等”字，例如：……（王平等，2005） ……。
> > 同一处引用多篇文献时，按出版年份由早期到近期依次标注，中间用分号分开。
> 
> 武大标准里似乎没有提到要标页码，示例中也没有给出
我是看国标的，里面有这个。

**Comment by earthmoon** [comment]
> > 正文中的标注方式分两种：其一，正文里已出现著作者姓名的，在其后用圆括号附上出版年份即可；其二，正文里仅提及有关的资料内容而未提到著作者，则在相应文句处用圆括号标注著作者姓名和出版年份，两者之间加逗号。
> > 引用同一著者在同一年份出版的多篇文献时，在出版年份之后用英文小写字母a、b、c……区别。如：（王平，2005a）；（王平，2005b）
> > 引用多位著者的文献时，对欧美著者只需标注第一个著者的姓，其后附“et al.”或“等”,仅两位作者的也可全部注出,中间用“and”或“和”；对中国著者应该标注第一著者的姓名，其后附“等”字，例如：……（王平等，2005） ……。
> > 同一处引用多篇文献时，按出版年份由早期到近期依次标注，中间用分号分开。
> 
> 武大标准里似乎没有提到要标页码，示例中也没有给出

我是看国标的，里面有这个。

**Comment by tanukihee** [comment]
各高校魔改国标是常事，当然要首先按学校标准来。学校标准也没说按国标严格执行

**Comment by earthmoon** [comment]
> 各高校魔改国标是常事，当然要首先按学校标准来。学校标准也没说按国标严格执行

好吧，我也没有能力去制作一个符合国标的。

**Comment by zepinglee** [comment]
> > 确实是**推荐**而不是**要求**，我更正我的说法
> 
> 即便是使用**作者-年**，在讨论中出现的引用一本书的页码，如果这本书只出现一次，应当把页码放在参考文献里，如果出现2次或者2次以上，参考文献里的这本书不出现页码，并且每次这本书出现的地方要在括号内输入页码。这个问题好像解决不了。

`\cite[page]{key}`

**Comment by earthmoon** [comment]
> > > 确实是**推荐**而不是**要求**，我更正我的说法
> > 
> > 
> > 即便是使用**作者-年**，在讨论中出现的引用一本书的页码，如果这本书只出现一次，应当把页码放在参考文献里，如果出现2次或者2次以上，参考文献里的这本书不出现页码，并且每次这本书出现的地方要在括号内输入页码。这个问题好像解决不了。
> 
> `\cite[page]{key}`
这个解决不了问题。
