### ISSUE TITLE
clone下来在vscode里使用LaTeX插件编译出现如下警告，是否有影响？

### ISSUE THREAD

**Issue by TianshuDing** [whutug/whu-thesis#79]
It seems that you have not declare a CJKfamily.
(xeCJK)	If you want to use xeCJK in the right way, you should
(xeCJK)	use
(xeCJK)	
(xeCJK)	`\setCJKmainfont[...]{...}'
(xeCJK)	
(xeCJK)	in the preamble to declare the default CJKfamily.
(xeCJK)	

Font "FandolSong-Regular" does not contain requested
(fontspec)	Script "CJK".

Using \overbracket and \underbracket from
(unicode-math)	`mathtools' package.
(unicode-math)	
(unicode-math)	Use \Uoverbracket and \Uunderbracket for
(unicode-math)	original `unicode-math' definition.

I'm going to overwrite the following commands
(unicode-math)	from the `mathtools' package: 
(unicode-math)	
(unicode-math)	\dblcolon, \coloneqq, \Coloneqq, \eqqcolon.
(unicode-math)	
(unicode-math)	
(unicode-math)	Note that since I won't overwrite the other
(unicode-math)	colon-like commands, using them will lead to
(unicode-math)	inconsistencies.

Font "FandolFang-Regular" does not contain requested
(fontspec)	Script "CJK".

Font "FandolKai-Regular" does not contain requested
(fontspec)	Script "CJK".

Font "FandolHei-Regular" does not contain requested
(fontspec)	Script "CJK".

**Comment by sikouhjw** [comment]
1. https://github.com/whutug/whu-thesis/issues/74
2. https://zhuanlan.zhihu.com/p/145429470
3. https://tex.stackexchange.com/questions/570548/suppress-warning-by-unicode-math-regarding-mathtools

**Comment by TianshuDing** [comment]
有交流群嘛？

**Comment by sikouhjw** [comment]
> 有交流群嘛？

没有，也低效
