### ISSUE TITLE
引用网页时模版输出格式与规定不符

### ISSUE THREAD

**Issue by nirvanaxiao6** [whutug/whu-thesis#80]
## 检查

* [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

* 操作系统
  + [x] Windows 10
  + [ ] Windows 8/8.1
  + [ ] Windows 7
  + [ ] 更早版本的 Windows
  + [ ] macOS
  + [ ] Linux（请附发行版）

* TeX 发行版
  + [x] TeX Live 2021
  + [ ] MiKTeX 
  + [ ] CTeX 套装 2.9.2.164
  + [ ] 更早版本的 CTeX 套装

* whu-thesis 版本

 v0.4

## 描述问题

在引用网页时，编译输出的引文格式与武大毕业论文规定中格式不相符。

这里是我引用的网页的bib格式引文：
@online{murmannADCPerformanceSurvey2021,
  title = {{{ADC Performance Survey}} 1997-2021},
  author = {Murmann, Boris},
  date = {2021-06-28},
  url = {https://web.stanford.edu/~murmann/adcsurvey.html},
  urldate = {2021-12-26},
  langid = {english}
}

编译后生成引文格式为：
MURMANN B. ADC Performance Survey 1997-2021[EB/OL]. .https://web.stanford.edu/~murmann/adcsurvey.html.

但按照规定格式，应生成为：
MURMANN B. ADC Performance Survey 1997-2021[EB/OL].https://web.stanford.edu/~murmann/adcsurvey.html, 2021-06-28.
（
1.[EB/OL]后应只有一个点，通过阅览.bst文件后我认为这里是输出year时空缺导致多了一个点；
2.最后应有更新日期。
）

我尝试修改gb7714-2005-whu.bst文件如下操作：
在FUNCTION(online)中：
1.将1692行, true output.year改为false;
2.在1695行后新添加一行true output.date

随后编译输出格式为：
MURMANN B. ADC Performance Survey 1997-2021[EB/OL]. .https://web.stanford.edu/~murmann/adcsurvey.html2021-06-28.

可以看到，EB/OL后的两个点依然没有变成一个点，且链接与日期之间未出现逗号。

所以，请问该如何修改使得生成的格式与规定格式相符？

**Comment by sikouhjw** [comment]
很遗憾，在我这里输出为
```
MURMANN B. ADC Performance Survey 1997-2021[EB/OL]. (2021-06-28) [2021-12-26]. https://web.stanford.edu/~murmann/adcsurvey.html.
```
请你检查模板是否为最新版。

**Comment by nirvanaxiao6** [comment]
> 很遗憾，在我这里输出为
> 
> ```
> MURMANN B. ADC Performance Survey 1997-2021[EB/OL]. (2021-06-28) [2021-12-26]. https://web.stanford.edu/~murmann/adcsurvey.html.
> ```
> 
> 请你检查模板是否为最新版。

非常感谢。我已经将模版更新到了最新版，并输出了和你一样的结果。

但如你所见，这里输出的格式依然不符合武大所规定的参考文献格式（日期的位置应在链接之后而非之前），请问应该如何修改以符合格式呢

**Comment by tanukihee** [comment]
![image](https://user-images.githubusercontent.com/34062491/147480374-7f8d6cbb-ca15-46b6-9457-ff2a20f9b990.png)

**Comment by nirvanaxiao6** [comment]
![image](https://user-images.githubusercontent.com/13258510/147482047-65bdb169-c8d6-4d41-b23e-5f4c5ae4ea15.png)

来自《武汉大学本科生毕业论文（设计）书写印制规范》

**Comment by zepinglee** [comment]
> 来自《武汉大学本科生毕业论文（设计）书写印制规范》

这是在国标的基础上进行了额外的修改。

能发个《规范》的链接吗？我可以帮你们定制一份 bst。

**Comment by nirvanaxiao6** [comment]
> 

十分感谢您！
另外，如果我想了解.bst文件的编写结构，尝试编写.bst文件，我可以通过哪些文档来了解呢？如果不嫌麻烦的话希望能推荐一些比较成熟的文档，再次感谢。

**Comment by zepinglee** [comment]
> 十分感谢您！ 另外，如果我想了解.bst文件的编写结构，尝试编写.bst文件，我可以通过哪些文档来了解呢？如果不嫌麻烦的话希望能推荐一些比较成熟的文档，再次感谢。

- [btxhak](http://mirrors.ctan.org/biblio/bibtex/base/btxhak.pdf)
- [ttb](http://mirrors.ctan.org/info/bibtex/tamethebeast/ttb_en.pdf)

**Comment by tanukihee** [comment]
> 来自《武汉大学本科生毕业论文（设计）书写印制规范》

原来是本科吗……看到作者—年就以为是硕博了😂

**Comment by zepinglee** [comment]
@tanukihee [whutug/whu-thesis/data/](https://github.com/whutug/whu-thesis/tree/master/data) 有三个 bst，哪个是本科生的？

我稍微看了一下研究生的要求，虽然也是在 GB/T 7714—2005 的基础上改编的，但是跟本科生的有很大区别。

**Comment by tanukihee** [comment]
> @tanukihee [whutug/whu-thesis/data/](https://github.com/whutug/whu-thesis/tree/master/data) 有三个 bst，哪个是本科生的？
> 
> 我稍微看了一下研究生的要求，虽然也是在 GB/T 7714—2005 的基础上改编的，但是跟本科生的有很大区别。

因为我院对参考文献格式并没有狠抓，所以我当时直接用了 2005-numerical。而且观察到上如果直接复制知网的 2015 格式也不会被抓出来，所以并没有对参考文献样式严格地按照标准进行客制化😂

不知道其他院对参考文献的管理有多么严格，如果可以的话，可能本科研究生的 bst 都要重新写😂

**Comment by zepinglee** [comment]
本科生的 bst 已经改好了（[whu-bst-example.zip](https://github.com/whutug/whu-thesis/files/7798590/whu-bst-example.zip)），你们决定怎么整合到项目里。

**Comment by SwitWu** [comment]
最新的《本科生毕业论文（设计）书写印制规范》采用 GB/T 7714-2015，格式：主要责任者.题名:其他题名信息[文献类型标志/文献载体标志].出版地:出版者，出版年(更新或修改日期).获取和访问路径.
