### ISSUE TITLE
英文封面只有题目和作者名字，怎么加内容啊？

### ISSUE THREAD

**Issue by sz94** [whutug/whu-thesis#81]

**Comment by sikouhjw** [comment]
在哪里看到的要用英文封面？我从模板里找不到相关内容。

**Comment by sz94** [comment]
> 在哪里看到的要用英文封面？我从模板里找不到相关内容。

我指的是模板里中文封面后面的那个，就是原创性声明之前。

**Comment by sikouhjw** [comment]
[武汉大学博士学位论文撰写及印制规格的规定](https://gs.whu.edu.cn/info/1026/1100.htm)
> 四、论文英文题目
>
> 论文英文题目专用一页纸，“英文题目”用Times New Roman字体二号字，其下“研究生姓名”用Times New Roman字体四号字；外语专业应为中文题目。

**Comment by sz94** [comment]
> [武汉大学博士学位论文撰写及印制规格的规定](https://gs.whu.edu.cn/info/1026/1100.htm)
> 
> > 四、论文英文题目
> > 论文英文题目专用一页纸，“英文题目”用Times New Roman字体二号字，其下“研究生姓名”用Times New Roman字体四号字；外语专业应为中文题目。

谢谢了哦，主要是这样看着好简单，看到的论文这一页都像黄老师模板那样丰富些，哈哈哈哈

**Comment by sikouhjw** [comment]
> > [武汉大学博士学位论文撰写及印制规格的规定](https://gs.whu.edu.cn/info/1026/1100.htm)
> > > 四、论文英文题目
> > > 论文英文题目专用一页纸，“英文题目”用Times New Roman字体二号字，其下“研究生姓名”用Times New Roman字体四号字；外语专业应为中文题目。
> 
> 谢谢了哦，主要是这样看着好简单，看到的论文这一页都像黄老师模板那样丰富些，哈哈哈哈

你应该举报他们不遵守规范

**Comment by sz94** [comment]
> > > [武汉大学博士学位论文撰写及印制规格的规定](https://gs.whu.edu.cn/info/1026/1100.htm)
> > > > 四、论文英文题目
> > > > 论文英文题目专用一页纸，“英文题目”用Times New Roman字体二号字，其下“研究生姓名”用Times New Roman字体四号字；外语专业应为中文题目。
> > 
> > 
> > 谢谢了哦，主要是这样看着好简单，看到的论文这一页都像黄老师模板那样丰富些，哈哈哈哈
> 
> 你应该举报他们不遵守规范

厉害了
