### ISSUE TITLE
正文引用参考文献处格式的问题

### ISSUE THREAD

**Issue by lkyhfx** [whutug/whu-thesis#85]
>正文中的标注方式分两种：其一，正文里已出现著作者姓名的，在其后用圆括号附上出版年份即可；其二，正文里仅提及有关的资料内容而未提到著作者，则在相应文句处用圆括号标注著作者姓名和出版年份，两者之间加逗号。
例如：
Park et al.(1995)根据Laurentia西缘放射状基性岩墙的研究以及与地幔柱有关的澳大利亚Gairdner岩墙群的研究，首次提出约780Ma地幔柱导致Rodinia超大陆的裂解。
其中关于成冰系顶底界时限和冰川活动年龄、超大陆裂解的起始时间和持续时间……是当前中国地球科学界十分活跃并得到迅速发展的研究领域(王平，2003)。

请问如何使用第二种标注方式？

**Comment by tanukihee** [comment]
![image](https://user-images.githubusercontent.com/34062491/154008082-67d07b9a-2d23-45f3-a48b-2cf8f44b9b75.png)

**Comment by lkyhfx** [comment]
![截屏2022-02-15 下午3 00 45](https://user-images.githubusercontent.com/30225731/154009500-9fc52775-2ec2-4fec-90d1-5b6ae268410a.png)

我用的是硕士模版，默认已经是 author-year 的样式，我需要的是 `Rifai et al., 2011` `王平，2003` 这样的格式

**Comment by tanukihee** [comment]
![image](https://user-images.githubusercontent.com/34062491/154010040-e727ee64-d4fd-4ebc-9457-40e6160c6501.png)
来自 natbib 文档（如果你使用的是 bibtex）
