### ISSUE TITLE
书签（bookmark）优化

### ISSUE THREAD

**Issue by MoeLeaf** [whutug/whu-thesis#91]
系统：macOS monterey
Tex发行版：MacTex2021
pdf阅读器：skim

1. 编译得到的pdf只从绪论开始才有书签（bookmark），绪论前面的前面的封面到目录部分实际上也有10页，这部分如果也加上bookmark可以增加翻页时的体验。
2. 附录的bookmark只有\chapter{xxx}中的xxx，如下图中附录的标签名称只有“数据”，而不是“附录A 数据”。没有明确标识出来这是附录，容易引起迷惑。

![image](https://user-images.githubusercontent.com/12065870/158300934-c8698528-f98b-455d-b522-be927f393d07.png)

**Comment by fyqqyf** [comment]
看到你是monterey，想问一下字体问题是如何解决的？🫡

**Comment by NoName1022** [comment]
> 看到你是monterey，想问一下字体问题是如何解决的？🫡

没有遇到字体问题，whu-thesis-doc.tex这个文件我编译不了，但是自己的论文没有问题，如果缺字体可以试试下载字体文件直接打开，给mac安装字体。

**Comment by fyqqyf** [comment]
> 

你复制黑体会出现乱码吗（比如每一章的标题）

**Comment by zhangdoudou** [comment]
同样遇到这个问题，目前是通过手动添加书签解决的

**Comment by SwitWu** [comment]
已完成 218984df47b9fa6d5a29f446937d59d3ec99b41a
