### ISSUE TITLE
Achievement 去掉所有格式

### ISSUE THREAD

**Issue by wzm2256** [whutug/whu-thesis#92]
## 检查

* [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

* 操作系统
  + [x] Windows 10
  + [ ] Windows 8/8.1
  + [ ] Windows 7
  + [ ] 更早版本的 Windows
  + [ ] macOS
  + [ ] Linux（请附发行版）

* TeX 发行版
  + [x] TeX Live <2021>
  + [ ] MiKTeX 
  + [ ] CTeX 套装 2.9.2.164
  + [ ] 更早版本的 CTeX 套装

* whu-thesis 版本

  <master>

## 描述问题

如何在achievments章节内增加bibtex引用？
或者去掉所有该章节的格式？

## 最小工作示例（MWE）

只在achievement章节内输入以下内容
``` latex
\item aa
\item bb
\item cc

```
（用 XeLaTeX 编译后）输出

aa
bb
cc
每一项前面都无编号。

预期输出1
1.aa
2.bb
3.cc

预期2：
去掉cls中该章节内所有格式，允许直接在该章节中输入
```latex
\nobibliography{pub} 
\begin{enumerate}
\item \bibentry{wang2022partial}
\end{enumerate}
```

或者允许在章节里使用enumerate，至少能加个编号吧。

## 链接

* TeX. SX:
* GitHub:

**Comment by wzm2256** [comment]
在改cls之前我先补救一下吧。用嵌套列表的形式可以勉强达到我的要求。
```latex
\item 
\begin{enumerate}
    \item[1. ]aaa aaaaaaaaaa aaaaaa aaaaaaaaaaaaa aaaaaaa aaaaaa aaaaaaaaaaaaaaaaaaa aaaaa aaaaaaa aaaa aa aaaa aaaa aaaa aaaaaa 
    \item[2. ]bbbbb bbbbbbbbbb bbbbbbbbbbbbbb bbbbbbb bbb bbbb bbbbbbb bbbbb  
    \item[3. ]cccc ccccc cccccc  c
\end{enumerate}
```
先用一个规定的\item, 在item中嵌套一个新的列表，从而达到正确的列表格式，换行对齐啥的都正确。
![image](https://user-images.githubusercontent.com/24223188/159147317-881d6da2-2d0c-4237-a310-a4f24e4b5dc5.png)

如果直接用默认的单层enumerate
要么无序号
```
\item aaa aaaaaaaaaa aaaaaa aaaaaaaaaaaaa aaaaaaa aaaaaa aaaaaaaaaaaaaaaaaaa aaaaa aaaaaaa aaaa aa aaaa aaaa aaaa aaaaaa 
\item bbbbb bbbbbbbbbb bbbbbbbbbbbbbb bbbbbbb bbb bbbb bbbbbbb bbbbb  
\item cccc ccccc cccccc  c
```
![image](https://user-images.githubusercontent.com/24223188/159147414-e3bebf42-e042-4020-bec7-623122c01336.png)

加上序号后报错
```
\item[1. ]aaa aaaaaaaaaa aaaaaa aaaaaaaaaaaaa aaaaaaa aaaaaa aaaaaaaaaaaaaaaaaaa aaaaa aaaaaaa aaaa aa aaaa aaaa aaaa aaaaaa 
\item[2. ]bbbbb bbbbbbbbbb bbbbbbbbbbbbbb bbbbbbb bbb bbbb bbbbbbb bbbbb  
\item[3. ]cccc ccccc cccccc  c
```
Package fontspec: The font "Iosevka Slab Light" cannot be found.
Undefined control sequence.
<argument> \LaTeX3 error: 


目前还没试\bibentry，就先把refrence直接粘过来。

**Comment by tanukihee** [comment]
你先用 enumitem 的 `\begin{enumerate}[label = xxx]` 试试吧

**Comment by wzm2256** [comment]
> 你先用 enumitem 的 `\begin{enumerate}[label = xxx]` 试试吧

试过，不行。会报错。

我的建议还是把achievement所有格式删掉。
在那之前用我上面说的嵌套enmuerate能补救一下。

**Comment by tanukihee** [comment]
achievements 本身就是一个 enumerate 环境，本意是让你里面直接用 `\item` 写的，至于为什么没有序号，是因为硕博默认的 author-year 就是没有序号的，这里让 achievements 的样式和参考文献列表样式相同了而已

**Comment by tanukihee** [comment]
> 加上序号后报错
> ```
> \item[1. ]aaa aaaaaaaaaa aaaaaa aaaaaaaaaaaaa aaaaaaa aaaaaa aaaaaaaaaaaaaaaaaaa aaaaa aaaaaaa aaaa aa aaaa aaaa aaaa aaaaaa 
> \item[2. ]bbbbb bbbbbbbbbb bbbbbbbbbbbbbb bbbbbbb bbb bbbb bbbbbbb bbbbb  
> \item[3. ]cccc ccccc cccccc  c
> ```
> Package fontspec: The font "Iosevka Slab Light" cannot be found.
> Undefined control sequence.
> <argument> \LaTeX3 error: 
> 
> 
> 目前还没试\bibentry，就先把refrence直接粘过来。
> 

奇怪，这里怎么会用到 iosevka…

**Comment by wzm2256** [comment]
> achievements 本身就是一个 enumerate 环境，本意是让你里面直接用 `\item` 写的，至于为什么没有序号，是因为硕博默认的 author-year 就是没有序号的，这里让 achievements 的样式和参考文献列表样式相同了而已

行，那就先这样吧。
等我这阵子整完我再开个issue细说一下。我还遇到一些兼容性的问题，之前的文章用latex写的，环境和模板里的有冲突，我自己在cls文件里照葫芦画瓢改了一点，供参考吧。

**Comment by tanukihee** [comment]
> >> 你先用 enumitem 的 `\begin{enumerate}[label = xxx]` 试试吧
> 
> > 试过，不行。会报错。
> 
> 是在 `\item` 后面用，形成一个类似于嵌套 enumerate 的结构

草，引用按成编辑了，抱歉

**Comment by wzm2256** [comment]
> > > > 你先用 enumitem 的 `\begin{enumerate}[label = xxx]` 试试吧
> > 
> > 
> > > 试过，不行。会报错。
> > 
> > 
> > 是在 `\item` 后面用，形成一个类似于嵌套 enumerate 的结构
> 
> 草，引用按成编辑了，抱歉

没事，问题不大。
