### ISSUE TITLE
本科生毕业论文好像没有英文标题和姓名那一页？

### ISSUE THREAD

**Issue by WangYong-Design** [whutug/whu-thesis#93]
## 检查

* [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

* 操作系统
  + [x] Windows 10
  + [ ] Windows 8/8.1
  + [ ] Windows 7
  + [ ] 更早版本的 Windows
  + [ ] macOS
  + [ ] Linux（请附发行版）

* TeX 发行版
  + [x] TeX Live 
  + [ ] MiKTeX 
  + [ ] CTeX 套装 2.9.2.164
  + [ ] 更早版本的 CTeX 套装

* whu-thesis 版本

  

## 最小工作示例（MWE）

``` latex
\documentclass{whu-thesis}
\begin{document}
Hello, \LaTex!
\end{document}
```

（用 XeLaTeX 编译后）输出

``` latex
! Undefined control sequence.
l.3 Hello, \LaTex
                 !
?
```

## 链接

* TeX. SX:
* GitHub:

**Comment by tanukihee** [comment]
似乎除了外院，并没有要求本科生要有英文（外文）封面的

外院模板摸了（

**Comment by WangYong-Design** [comment]
![image](https://user-images.githubusercontent.com/71626073/160230997-3713e8be-616d-4dae-a1c8-00c088e2ff9b.png)
是这个模板比较早嘛？

**Comment by tanukihee** [comment]
…这是英文摘要，不是英文封面啊🧐

**Comment by WangYong-Design** [comment]
![image](https://user-images.githubusercontent.com/71626073/160231042-114b6a99-4b39-42ff-a8d5-e1cf81153c94.png)

是这个模板比较早嘛？(刚才截错了)

**Comment by tanukihee** [comment]
我没有见过这个模板诶，这是新模板吗

**Comment by WangYong-Design** [comment]
whu-thesis这个是参照的哪个模板呢？可以给个链接嘛

**Comment by WangYong-Design** [comment]
![image](https://user-images.githubusercontent.com/71626073/160231179-ddaec537-70bb-42ab-9b2c-be678ee474af.png)
它的缩进的示例还是这样的，是这个模板比较老嘛

**Comment by tanukihee** [comment]
在readme里面上传了，应该是来自于本科生论文管理系统（就是选题查重的那个网页）

**Comment by WangYong-Design** [comment]
找到了，(之前选择性近视了)。
