### ISSUE TITLE
请问如何把数学公式的字体改成与word默认的Cambria Math相近的字体

### ISSUE THREAD

**Issue by ZrW00** [whutug/whu-thesis#94]
## 检查

* [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

* 操作系统
  + [x] Windows 10
  + [ ] Windows 8/8.1
  + [ ] Windows 7
  + [ ] 更早版本的 Windows
  + [ ] macOS
  + [ ] Linux（请附发行版）

* TeX 发行版
  + [x] TeX Live 2021
  + [ ] MiKTeX 
  + [ ] CTeX 套装 2.9.2.164
  + [ ] 更早版本的 CTeX 套装

* whu-thesis 版本

  <v0.6d>

## 描述问题

该模板采用的数学公式字体为unicode-math，但是在损失函数（花体字L）上表现很差

![image](https://user-images.githubusercontent.com/65750098/160974919-da6f69a3-7bc0-43da-a4e4-073a352c600c.png)

将whu-thesis.cls中的“\RequirePackage { unicode-math }”注释掉后编译花体字L与Cambria Math相近，但是文章的开头会出现：“XITSMath-Regular.otf[BoldFont=XITSMath-Bold.otf]”的字样：

![image](https://user-images.githubusercontent.com/65750098/160975051-314c4005-0fd3-4036-999e-2d22df22d55f.png)

请问如何在不出现如上所示的字样的前提下修改数学公式字体？

**Comment by sikouhjw** [comment]
```tex
\setmathfont{Cambria Math}
```

**Comment by tanukihee** [comment]
其实还需要一个类似 `fontset=none` 的设置，@xkwxdyy 加油（逃

**Comment by xkwxdyy** [comment]
> 其实还需要一个类似 `fontset=none` 的设置，@xkwxdyy 加油（逃

这几个月是真没时间了，导师催我看书（
先按死抠的方法来吧
